### ISSUE TITLE
Unable to install C/C++ IntelliSense

### ISSUE THREAD

**Issue by kramer04** [microsoft/vscode-cpptools#10272]
### Environment

- OS and version:
```
Version: 1.75.0-insider
Commit: 11238faea62d570d77afe6edfe05c8b732c44a2b
Date: 2022-12-13T05:22:26.937Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-56-generic snap. Ubuntu 22.04.1 LTS
Sandboxed: Yes
```
Trying to install  C/C++ 1.13.7

### Bug Summary and Steps to Reproduce

Bug Summary

try to install C/C++ 1.13.7 from vscode insider 1.75.0 but it failed and propose to install manually and failed too

### Debugger Configurations

```shell
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "shell",
      "label": "C/C++: g++-11 générer le fichier actif",
      "presentation": {
        "echo": true,
        "reveal": "always",
        "focus": false,
        "panel": "shared",
        "showReuseMessage": true,
        "clear": true
      },
      "command": "/usr/bin/g++",
      "args": [
        //"-g",
        "${fileWorkspaceFolder}/main.cpp",
        "-std=c++11",
        //"-I",
        //"${fileWorkspaceFolder}/include",
        "-o",
        "${fileWorkspaceFolder}/main",
        "-Wall",
        "-Wextra",
        "-O2"
      ],
      "options": {
        "cwd": "${workspaceFolder}"
      },
      "problemMatcher": [
        "$gcc"
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "detail": "compiler: /usr/bin/g++"
    }
  ]
}
```

### Debugger Logs

```shell
Log

2022-12-13 18:50:12.745 [info] Electron sandbox mode is enabled!
2022-12-13 18:50:16.110 [info] [perf] Render performance baseline is 69ms
2022-12-13 18:50:29.973 [error] Signature: UnknownError
    at yt.download (vscode-file://vscode-app/snap/code-insiders/1176/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:37:92965)
    at async V.h (vscode-file://vscode-app/snap/code-insiders/1176/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:169726)
2022-12-13 18:50:30.012 [error] UnknownError: Signature: UnknownError
    at yt.download (vscode-file://vscode-app/snap/code-insiders/1176/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:37:92965)
    at async V.h (vscode-file://vscode-app/snap/code-insiders/1176/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:169726)

```
```


### Other Extensions

No other extension

### Additional Information

_No response_

**Comment by browntarik** [comment]
I am sorry you are facing this issue. I would like to request that you file an issue with VSCode to receive better attention since we do not handle the installation of our extension. You can file an issue here: https://github.com/microsoft/vscode/issues

I will be closing this thread unless there are further concerns.
