### ISSUE TITLE
Macbook pro M1, vs code doesnt install cpp extention tools (and other tools also)

### ISSUE THREAD

**Issue by sayan-chandra** [microsoft/vscode-cpptools#10617]
errors :
1) Error while installing 'C/C++' extension. Please check the [log](command:workbench.action.showWindowLog) for more details.
logs : 
1) 2023-03-01 17:02:23.121 [error] Download: XHR failed
    at pt.download (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:37:92381)
    at async Y.h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:167162)
2023-03-01 17:02:23.131 [error] XHR failed: Download: XHR failed
    at pt.download (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:37:92381)
    at async Y.h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:167162)

**Comment by sean-mcmanus** [comment]
You should report the error to VS Code at https://github.com/microsoft/vscode/issues or try installing the vsix at https://github.com/microsoft/vscode-cpptools/releases/tag/v1.14.4 . Our extension is not responsible for installing itself.
