### ISSUE TITLE
Extensions failed to run 'Error: EACCES: permission denied, scandir '/usr/lib/ssl/private''

### ISSUE THREAD

**Issue by Crylia** [microsoft/vscode-cpptools#11506]
### Environment

- OS and Version: Pop!_OS 22.04 LTS; Kernel 6.4.6-76060406-generic
- VS Code Version: 1.82.2 abd2f3db4bdb28f9e95536dfa84d8479f1eb312d x64
- C/C++ Extension Version: 1.17.5

### Bug Summary and Steps to Reproduce

Bug Summary:

I tried to edit the includePath, but it wouldn't open the c/c++ settings page. It then gave a humongous amount of errors when I tried to save my file and the language server couldn't start anymore.
I then tried to reinstall the extension and now this error pops up
```
[Error - 17:37:41] Sending document notification textDocument/didSave failed.
AssertionError [ERR_ASSERTION]: Nicht unterstützter Client
    at DefaultClient.enqueue (/home/crylia/.vscode/extensions/ms-vscode.cpptools-1.17.5-linux-x64/dist/main.js:48475:25)
    at invoke1 (/home/crylia/.vscode/extensions/ms-vscode.cpptools-1.17.5-linux-x64/dist/main.js:54385:67)
    at DidSaveTextDocumentFeature.callback (/home/crylia/.vscode/extensions/ms-vscode.cpptools-1.17.5-linux-x64/dist/main.js:70727:33)
    at n.value (/home/crylia/.vscode/extensions/ms-vscode.cpptools-1.17.5-linux-x64/dist/main.js:70712:22)
    at m.w (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
    at m.x (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1972)
    at m.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2188)
    at $acceptModelSaved (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:109:9611)
    at i.N (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:10813)
    at i.M (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:10579)
    at i.H (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:9660)
    at i.G (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:8736)
    at n.value (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:7566)
    at m.w (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
    at m.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
    at w.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:79:13940)
    at n.value (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:135:7901)
    at m.w (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
    at m.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
    at w.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:79:13940)
    at MessagePortMain.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:135:6181)
    at MessagePortMain.emit (node:events:513:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
```

It also sometimes throws the error that is in the title, google has 0 results for any of those errors.

Steps to reproduce:
No idea

Expected behavior:
Extension to work

### Configuration and Logs

```shell
No config


-------- Diagnostics - 5.10.2023, 17:40:42
Version: 1.17.5
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "/usr/include/**",
        "/usr/include/lua5.3/",
        "/usr/include/lua5.3/*",
        "/usr/include/glib-2.0",
        "/usr/include/glib-2.0/*"
    ],
    "cStandard": "c17",
    "cppStandard": "gnu++11",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "/usr/include/glib-2.0",
            "/usr/lib/x86_64-linux-gnu/glib-2.0/include",
            "/usr/include/lua5.3",
            "/usr/include/pulse",
            "/usr/include/**",
            "/usr/lib/x86_64-linux-gnu/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.17.5.0
No active translation units.

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 47229
Number of files parsed: 2461
```

```
Taganalysedatei: /home/crylia/Dokumente/Studium/main.cpp
Leerlaufschleife: Das aktive Dokument wird erneut analysiert.
LSP: cpptools/getCodeActions: file:///home/crylia/Dokumente/Studium/main.cpp (id: 52)
LSP: cpptools/formatDocument: file:///home/crylia/Dokumente/Studium/main.cpp (id: 53)
LSP: cpptools/fileChanged: file:///home/crylia/Dokumente/Studium/main.cpp
  Taganalysedatei: /home/crylia/Dokumente/Studium/main.cpp
```
```


### Other Extensions

_No response_

### Additional context

![grafik](https://github.com/microsoft/vscode-cpptools/assets/50151522/417c4269-6e95-466a-a800-098ea885921a)
When trying to attach the cpptools process

**Comment by Colengms** [comment]
Hi @Crylia .  The error message you are seeing (`Nicht unterstützter Client`) is ultimately triggered by a failure to launch a native C++ process used by the C/C++ Extension.  That can occur if the binary is corrupted or there is some incompatibility with your host system.  (Starting with 1.17, we build Linux native binaries using the MUSL toolchain, and fully statically linked, so there should no dependency on glibc version or any shared libraries on your system at all).  If it had been working properly for you before, it may have become corrupted somehow.  I'd suggest deleting the existing directory (`/home/crylia/.vscode/extensions/ms-vscode.cpptools-1.17.5-linux-x64`) and installing the extension again. System instability might explain your prior issues as well, as I've not seen those issues reported before.

The path referred to in the image in you linked (https://github.com/microsoft/vscode-cpptools/assets/50151522/417c4269-6e95-466a-a800-098ea885921a) appears to be incorrect.  If you're trying to attach to a crashing process, as describled [here](https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv), you'll need to replace that path with a path to that file on your system: `/home/crylia/.vscode/extensions/ms-vscode.cpptools-1.17.5-linux-x64/bin/cpptools`

Assuming reinstallation avoids the `Nicht unterstützter Client` error message, can you provide specific repro instructions that we might use to replicate one of your other issues?  I'd suggest we focus on one thing at a time (maybe the very first thing that seems to be going wrong).

**Comment by Crylia** [comment]
Thank you for your reply, I'll work on it when I'm back around next week.
