### ISSUE TITLE
Exception thrown during the configure process if CppTools's IntelliSense engine is disabled

### ISSUE THREAD

**Issue by KRMisha** [microsoft/vscode-cpptools#11795]
If the `ms-vscode.cpptools` extension's IntelliSense engine is disabled (by adding `"C_Cpp.intelliSenseEngine": "disabled"` to `settings.json`), the VS Code Makefile Tools extension throws an exception during its configure process. This message shows up in the output panel:

```
Exception thrown during the configure process: Cannot read properties of undefined (reading 'ActiveClient')
```

Setting `"C_Cpp.intelliSenseEngine": "disabled"` is useful when using another extension for language support, notably `vscode-clangd`, while still retaining CppTools's other useful features such as debugging.

Here is the thrown extension's stack trace:

```
TypeError: Cannot read properties of undefined (reading 'ActiveClient')
	at Object.getActiveClient (/home/misha/.vscode/extensions/ms-vscode.cpptools-1.18.5-linux-x64/dist/src/main.js:55922:28)
	at CustomConfigurationProviderCollection.add (/home/misha/.vscode/extensions/ms-vscode.cpptools-1.18.5-linux-x64/dist/src/main.js:54821:44)
	at CppTools.registerCustomConfigurationProvider (/home/misha/.vscode/extensions/ms-vscode.cpptools-1.18.5-linux-x64/dist/src/main.js:62426:23)
	at MakefileToolsExtension.registerCppTools (<path-to-repo>/vscode-makefile-tools/out/src/extension.js:105:30)
	at async MakefileToolsExtension.registerCppToolsProvider (<path-to-repo>/vscode-makefile-tools/out/src/extension.js:66:9)
	at async <path-to-repo>/vscode-makefile-tools/out/src/make.js:1254:48
	at async Immediate.<anonymous> (<path-to-repo>/vscode-makefile-tools/out/src/util.js:845:32)
```

**Comment by KRMisha** [comment]
Thanks a lot!
