### ISSUE TITLE
Cpptools Crashing with 'didSave' and 'EACCES' Errors in VSCode

### ISSUE THREAD

**Issue by amin-abouee** [microsoft/vscode-cpptools#11833]
### Environment

- OS and Version: Ubuntu 22.04 (Linux x64 6.2.0-34-generic)
- VS Code Version: 1.85.1
- C/C++ Extension Version: 1.18.5

### Bug Summary and Steps to Reproduce

Bug Summary:

I am encountering a series of errors with cpptools in Visual Studio Code that started occurring today without any recent updates to the cpptools extension. The issues manifest in three distinct errors when I attempt to save C++ files using Ctrl+S.

Initially, on pressing Ctrl+S to save my .cpp file, I receive the following error message:
`Sending document notification textDocument/didSave failed`
This error suggests a failure in the document saving process.

Shortly after the first error, cpptools crashes with this message:
`The language server crashed. Restarting...`
It indicates an unexpected termination of the language server, triggering a restart.

The third and more critical issue appears with this error message:
```Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Error: EACCES: permission denied, scandir "/usr/lib/ssl/private" ```
This suggests a permission issue, specifically an EACCES error, preventing access to the '/usr/lib/ssl/private' directory, which leads to the failure of the C/C++ language server startup and consequently disables IntelliSense features.

I haven't made any updates to the cpp tools extension today, so it's puzzling why these issues have suddenly started. Any assistance in resolving these errors and restoring normal functionality would be greatly appreciated.

Steps to reproduce:
Just open a cpp file and save it with Ctrl+S

### Configuration and Logs

```shell
[Error - 5:46:22 PM] Sending document notification textDocument/didSave failed.
AssertionError [ERR_ASSERTION]: Unsupported client
	at DefaultClient.enqueue (/home/aabouee/.vscode/extensions/ms-vscode.cpptools-1.18.5-linux-x64/dist/src/main.js:50360:25)
	at invoke1 (/home/aabouee/.vscode/extensions/ms-vscode.cpptools-1.18.5-linux-x64/dist/src/main.js:56427:67)
	at DidSaveTextDocumentFeature.callback (/home/aabouee/.vscode/extensions/ms-vscode.cpptools-1.18.5-linux-x64/dist/src/main.js:72946:33)
	at f.value (/home/aabouee/.vscode/extensions/ms-vscode.cpptools-1.18.5-linux-x64/dist/src/main.js:72931:22)
	at n.y (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.z (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1972)
	at n.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2188)
	at m.$acceptModelSaved (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:9611)
	at l.S (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:10829)
	at l.Q (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:10595)
	at l.M (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:9685)
	at l.L (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:8764)
	at f.value (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:7567)
	at n.y (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at o.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:103:14039)
	at f.value (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:7903)
	at n.y (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at o.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:103:14039)
	at MessagePortMain.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:6183)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
[Error - 5:46:34 PM] Sending document notification textDocument/didSave failed.
AssertionError [ERR_ASSERTION]: Unsupported client
	at DefaultClient.enqueue (/home/aabouee/.vscode/extensions/ms-vscode.cpptools-1.18.5-linux-x64/dist/src/main.js:50360:25)
	at invoke1 (/home/aabouee/.vscode/extensions/ms-vscode.cpptools-1.18.5-linux-x64/dist/src/main.js:56427:67)
	at DidSaveTextDocumentFeature.callback (/home/aabouee/.vscode/extensions/ms-vscode.cpptools-1.18.5-linux-x64/dist/src/main.js:72946:33)
	at f.value (/home/aabouee/.vscode/extensions/ms-vscode.cpptools-1.18.5-linux-x64/dist/src/main.js:72931:22)
	at n.y (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.z (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1972)
	at n.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2188)
	at m.$acceptModelSaved (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:9611)
	at l.S (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:10829)
	at l.Q (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:10595)
	at l.M (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:9685)
	at l.L (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:8764)
	at f.value (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:7567)
	at n.y (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at o.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:103:14039)
	at f.value (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:7903)
	at n.y (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at o.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:103:14039)
	at MessagePortMain.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:6183)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
[Error - 5:47:07 PM] The language server crashed. Restarting...
```

### Additional context

![Screenshot from 2024-01-03 19-10-00](https://github.com/microsoft/vscode-cpptools/assets/2705755/2bacafb4-d9a0-4e61-b8e6-54209c468e9c)

**Comment by sean-mcmanus** [comment]
Can you attach to the cpptools process before the crash to get a crash call stack? See https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv

**Comment by amin-abouee** [comment]
I linked the `cpptools` with the debugger, however, it did not report any crashes. 
Nonetheless, the `cpptools-srv` is absent from the attach list, as it crashes immediately upon the initiation of Visual Studio Code.

**Comment by sean-mcmanus** [comment]
@amin-abouee Did it say it exited with code 0? cpptools-srv is for IntelliSense and shouldn't be related to the crash you're seeing.

**Comment by amin-abouee** [comment]
The debugger doesn't catch any crashes in cpptools, while the crashes are occurring on the right side as can be seen from image. This leads me to believe that the error might not be originating from cpptools, but rather from some node.js code executing elsewhere.
![Screenshot from 2024-01-03 23-15-49](https://github.com/microsoft/vscode-cpptools/assets/2705755/9834101b-0e99-4d16-87f5-9eba85272195)

**Comment by amin-abouee** [comment]
@sean-mcmanus, the issue has been resolved. The root cause was in the 
`c_cpp_properties.json` file, within the `include_path` section, I included an entry `"/usr/**/include/**"`. This was intended to cover both `/usr/local/include/**` and `/usr/include/**`, but it turned out to be the source of the problem.

**Comment by sean-mcmanus** [comment]
@amin-abouee What did you change it to? I think the correct syntax is "/usr/*/include/**". The "/*/" is a wildcard expansion and the "/**" is recursive includes.

**Comment by sean-mcmanus** [comment]
@amin-abouee Actually, you normally don't want to use "/**" with system includes, because the order is non-deterministic and the system includes usually require a specific order in order to work correctly.

**Comment by amin-abouee** [comment]
> @amin-abouee Actually, you normally don't want to use "/**" with system includes, because the order is non-deterministic and the system includes usually require a specific order in order to work correctly. Normally, you'd want to set the compilerPath and not have any system includes in the includePath.

Alright, I wasn't aware of that earlier. However, since I have certain libraries installed system-wide, particularly in `/usr/local/include`, I made some additions there and now it's functioning properly.
