### ISSUE TITLE
Installing the extension in the remote host on WSL1 fails with EACCESS on renaming

### ISSUE THREAD

**Issue by darkmattercoder** [microsoft/vscode-cpptools#11980]
I reinstalled the vscode server in my WSL1 environment. After the reinstallation, I re-installed all local extensions into the remote WSL environment as well. However, the cpptools and the cpp-extpack extensions are the two extensions which cannot be properly installed. 

All other extensions I installed into WSL were successfully installed.

It does not matter whether I start the installation from the ui or via the CLI. It always gets an EACCESS Error on renaming the extension:

```
code --install-extension /c/Users/user/Downloads/cpptools-linux.vsix
Installing extensions...
EACCES: EACCES: permission denied, rename '/home/user/.vscode-server/extensions/.da3c4b76-1cfc-470f-8ea3-260c1f44f3af' -> '/home/user/.vscode-server/extensions/ms-vscode.cpptools-1.18.5'
    at V.C (/home/user/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:77287)
    at async V.extractUserExtension (/home/user/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:74800)
    at async ue.u (/home/user/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:80893)
    at async ue.x (/home/user/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:84276)
    at async ue.h (/home/user/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:80426)
    at async ue.h (/home/user/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/server/node/server.main.js:169:83306) {
  code: 'EACCES'
}
Failed Installing Extensions: file:///c/Users/BauerJ2/Downloads/cpptools-linux.vsix
```

I tried the rough approach to `chmod -R 777` the `~/.vscode-server` directory to ensure that it does not have to do anything with file permissions but to no avail. The error persists.

Vscode Version:

```
 code --version
1.86.2
903b1e9d8990623e3d7da1df3d33db3e42d80eda
x64
``` 

Windows:
```
[System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
6      1      7601   65536
```

WSL1 Distro is debian bookworm.

I am aware of https://github.com/microsoft/WSL/issues/1956

I cannot switch to WSL2 for several reasons.

All other extensions installed without issue.

Any ideas?

**Comment by Colengms** [comment]
Hi @darkmattercoder .  It doesn't look like the C/C++ extension is successfully installed, so the issue would seem to be related to VS Code directly.  I'd suggest opening an issue in [the VS Code repo](https://github.com/microsoft/vscode/issues).  Your issue would seem to be related to user permission issues during the extension installation process.
