### ISSUE TITLE
RangeError: WebAssembly.Instance(): Out of memory: Cannot allocate Wasm memory for new instance

### ISSUE THREAD

**Issue by mdeberts** [microsoft/vscode-cpptools#12529]
Type: <b>Bug</b>

Install C/C++ and Modern Fortran
Start remote ssh in VsCode and check "Extension Hoste (Remote)"
There is enough space in the directories to expand / save files up to 20 GB that should not be the problem.

024-07-30 15:02:24.434 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
**2024-07-30 15:02:24.435 [info] ExtensionService#_doActivateExtension ms-vscode.cpptools, startup: false, activationEvent: 'onLanguage:FortranFreeForm', root cause: fortran-lang.linter-gfortran
2024-07-30 15:02:24.770 [error] Activating extension ms-vscode.cpptools failed due to an error:
2024-07-30 15:02:24.770 [error] RangeError: WebAssembly.Instance(): Out of memory: Cannot allocate Wasm memory for new instance**
	at 1298 (/hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:28534:22)
	at __webpack_require__ (/hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:116162:42)
	at 6278 (/hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:40823:16)
	at __webpack_require__ (/hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:116162:42)
	at 2277 (/hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:83848:22)
	at __webpack_require__ (/hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:116162:42)
	at 1817 (/hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:72989:20)
	at __webpack_require__ (/hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:116162:42)
	at /hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:116187:27
	at /hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:116459:3
	at Object.<anonymous> (/hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:116462:12)
	at Module._compile (node:internal/modules/cjs/loader:1376:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
	at Module.load (node:internal/modules/cjs/loader:1207:32)
	at Module._load (node:internal/modules/cjs/loader:1023:12)
	at S._load (/hpc/uhome/mdeberts/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/workbench/api/node/extensionHostProcess.js:179:6035)
	at n._load (/hpc/uhome/mdeberts/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/workbench/api/node/extensionHostProcess.js:176:31788)
	at i._load (/hpc/uhome/mdeberts/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/workbench/api/node/extensionHostProcess.js:141:34301)
	at Module.require (node:internal/modules/cjs/loader:1235:19)
	at require (node:internal/modules/helpers:176:18)
	at Function.i [as __$__nodeRequire] (/hpc/uhome/mdeberts/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/loader.js:5:98)
	at m.xb (/hpc/uhome/mdeberts/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/workbench/api/node/extensionHostProcess.js:176:32967)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 0)

Extension version: 1.21.4
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:08:12.169Z)
OS version: Linux x64 5.14.21-150500.55.68-default
Modes:
Remote OS version: Linux x64 4.18.0-477.15.1.el8_8.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 1, 1|
|Memory (System)|15.43GB (9.90GB free)|
|Process Argv|--crash-reporter-id 1fdd5797-c5e2-49c4-aef9-1589525e78ad|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma5|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: rcl|
|OS|Linux x64 4.18.0-477.15.1.el8_8.x86_64|
|CPUs|AMD EPYC 7502 32-Core Processor (64 x 3283)|
|Memory (System)|250.44GB (111.07GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
refactorc:31101458
ccplti:31103428
pythonrstrctxt:31103193
wkspc-onlycs-c:31106320

```

</details>

your clipboard because it was too large to send. Please paste.

**Comment by sean-mcmanus** [comment]
@mdeberts Does this bug repro with the Modern Fortran extension disabled?

**Comment by Thomasyse** [comment]
> @mdeberts Does this bug repro with the Modern Fortran extension disabled?

I don't install Modern Fortran and also see this error. When I reinstall 1.20.5 no error occurs.

**Comment by Colengms** [comment]
Hi @mdeberts .  Since this isn't happening for most people, can you tell us more about your remote machine?  Is there anything about how it's configured that may be non-standard or different from default?

Between those versions, we upgraded several of our dependencies (for security purposes), including webpack, which appears to be where this issue is coming from (before any of our code actually executes).

**Comment by mdeberts** [comment]
@Thomasyse @Colengms 
I also tried a reinstall of 1.20.5 and now it works.
The remote machine is a high performance computer (hpc). 
I connect to the login node via remote ssh from my linux workstation.

HPC Linux version:
NAME="Red Hat Enterprise Linux"
VERSION="8.8 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.8 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
@Colengms if you need more specific information, please write me a message, I can not post it in public.

I uninstalled Modern Fortran and opened a .cpp file.

**Uninstalled Modern Fortran
C++ Extension v 1.20.5**
**works**
2024-07-31 07:44:58.079 [info] Extension host with pid 3631549 started
2024-07-31 07:44:58.093 [info] Lock '/hpc/uhome/mdeberts/.vscode-server/data/User/workspaceStorage/fd259252b3eb06c31daff543bf236fdf/vscode.lock': Lock acquired.
2024-07-31 07:44:58.279 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-07-31 07:44:58.397 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-07-31 07:44:58.498 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-07-31 07:44:58.498 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-07-31 07:44:58.731 [info] Eager extensions activated
2024-07-31 07:44:58.732 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-07-31 07:44:58.732 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-07-31 07:44:58.732 [info] ExtensionService#_doActivateExtension genieai.chatgpt-vscode, startup: false, activationEvent: 'onStartupFinished'
2024-07-31 07:45:02.313 [info] ExtensionService#_doActivateExtension ms-vscode.cpptools, startup: false, activationEvent: 'onLanguage:cpp'

**Uninstalled Modern Fortran
C++ Extension v 1.24.1**
**error**
2024-07-31 07:46:12.044 [info] Extension host with pid 3781682 started
2024-07-31 07:46:12.044 [error] Error: EEXIST: file already exists, open '/hpc/uhome/mdeberts/.vscode-server/data/User/workspaceStorage/fd259252b3eb06c31daff543bf236fdf/vscode.lock'
2024-07-31 07:46:12.045 [info] Lock '/hpc/uhome/mdeberts/.vscode-server/data/User/workspaceStorage/fd259252b3eb06c31daff543bf236fdf/vscode.lock': Could not acquire lock, checking if the file is stale.
2024-07-31 07:46:12.055 [info] Lock '/hpc/uhome/mdeberts/.vscode-server/data/User/workspaceStorage/fd259252b3eb06c31daff543bf236fdf/vscode.lock': The lock does not look stale, elapsed: 750 ms, giving up.
2024-07-31 07:46:12.163 [info] Lock '/hpc/uhome/mdeberts/.vscode-server/data/User/workspaceStorage/fd259252b3eb06c31daff543bf236fdf-1/vscode.lock': Lock acquired.
2024-07-31 07:46:12.512 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-07-31 07:46:12.513 [info] ExtensionService#_doActivateExtension ms-vscode.cpptools, startup: false, activationEvent: 'onLanguage:cpp'
**2024-07-31 07:46:12.939 [error] Activating extension ms-vscode.cpptools failed due to an error:
2024-07-31 07:46:12.940 [error] RangeError: WebAssembly.Instance(): Out of memory: Cannot allocate Wasm memory for new instance
	at 1298 (/hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:28534:22)**
	at __webpack_require__ (/hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:116162:42)
	at 6278 (/hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:40823:16)
	at __webpack_require__ (/hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:116162:42)
	at 2277 (/hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:83848:22)
	at __webpack_require__ (/hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:116162:42)
	at 1817 (/hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:72989:20)
	at __webpack_require__ (/hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:116162:42)
	at /hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:116187:27
	at /hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:116459:3
	at Object.<anonymous> (/hpc/uhome/mdeberts/.vscode-server/extensions/ms-vscode.cpptools-1.21.4-linux-x64/dist/src/main.js:116462:12)
	at Module._compile (node:internal/modules/cjs/loader:1376:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
	at Module.load (node:internal/modules/cjs/loader:1207:32)
	at Module._load (node:internal/modules/cjs/loader:1023:12)
	at S._load (/hpc/uhome/mdeberts/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/workbench/api/node/extensionHostProcess.js:179:6035)
	at n._load (/hpc/uhome/mdeberts/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/workbench/api/node/extensionHostProcess.js:176:31788)
	at i._load (/hpc/uhome/mdeberts/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/workbench/api/node/extensionHostProcess.js:141:34301)
	at Module.require (node:internal/modules/cjs/loader:1235:19)
	at require (node:internal/modules/helpers:176:18)
	at Function.i [as __$__nodeRequire] (/hpc/uhome/mdeberts/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/loader.js:5:98)
	at m.xb (/hpc/uhome/mdeberts/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/workbench/api/node/extensionHostProcess.js:176:32967)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 0)

**Comment by kvoronin** [comment]
Same error, similar setup (but while trying to solve it, I've mode the vscode cache folder to a custom location outside my tiny home directory which has a limitation of 4 GB), no Fortran extension (just tried plain C/C++ project in the remote ssh project). Downgrading (from 1.21.4) to 1.20.5 worked.

Note: without remote ssh, everything worked on my Windows host.

**Comment by Colengms** [comment]
I suspect the issue has something to do with:

https://github.com/nodejs/node/issues/41319#issuecomment-1001025128

https://github.com/webpack/webpack/issues/15584#issuecomment-1146566931

@mdeberts , @Thomasyse , @kvoronin , Can you confirm whether or not you have a memory limit set, and whether unsetting or increasing it avoids this memory allocation issue in NodeJS?

**Comment by mdeberts** [comment]
This are my ulimits, I can not increase ulimit -v any further by myself.

![grafik](https://github.com/user-attachments/assets/36b63af1-27d9-4c8c-8347-61ec1f9a3124)

**Comment by mdeberts** [comment]
I updated to 1.21.6, and it works again - thank you. 
But I still get an WebAssembly error, which does not seem to have a negative effect for now.

Log of Extension Host (Remote)

2024-08-07 07:40:33.442 [info] Extension host with pid 975811 started
2024-08-07 07:40:33.459 [info] Lock '/hpc/uhome/mdeberts/.vscode-server/data/User/workspaceStorage/fd259252b3eb06c31daff543bf236fdf/vscode.lock': Lock acquired.
2024-08-07 07:40:33.614 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-08-07 07:40:33.615 [info] ExtensionService#_doActivateExtension ms-vscode.cpptools, startup: false, activationEvent: 'onLanguage:cpp'
2024-08-07 07:40:34.616 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-08-07 07:40:34.863 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-08-07 07:40:34.863 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-08-07 07:40:35.117 [info] Eager extensions activated
2024-08-07 07:40:35.118 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-08-07 07:40:35.118 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
**2024-08-07 07:40:35.544 [error] RangeError: WebAssembly.instantiate(): Out of memory: Cannot allocate Wasm memory for new instance
	at lazyllhttp (node:internal/deps/undici/undici:8429:32)**

**Comment by Thomasyse** [comment]
For me 1.21.6 still doesn't work.
[error] Activating extension ms-vscode.cpptools failed due to an error:
[error] RangeError: WebAssembly.Instance(): Out of memory: Cannot allocate Wasm memory for new instance
	at 1298 (.vscode-server/extensions/ms-vscode.cpptools-1.21.6/dist/src/main.js:28534:22)
	at __webpack_require__ (.vscode-server/extensions/ms-vscode.cpptools-1.21.6/dist/src/main.js:116162:42)
	at 6278 (.vscode-server/extensions/ms-vscode.cpptools-1.21.6/dist/src/main.js:40823:16)
	at __webpack_require__ (.vscode-server/extensions/ms-vscode.cpptools-1.21.6/dist/src/main.js:116162:42)
	at 2277 (.vscode-server/extensions/ms-vscode.cpptools-1.21.6/dist/src/main.js:83848:22)
	at __webpack_require__ (.vscode-server/extensions/ms-vscode.cpptools-1.21.6/dist/src/main.js:116162:42)
	at 1817 (.vscode-server/extensions/ms-vscode.cpptools-1.21.6/dist/src/main.js:72989:20)
	at __webpack_require__ (.vscode-server/extensions/ms-vscode.cpptools-1.21.6/dist/src/main.js:116162:42)
	at .vscode-server/extensions/ms-vscode.cpptools-1.21.6/dist/src/main.js:116187:27
	at .vscode-server/extensions/ms-vscode.cpptools-1.21.6/dist/src/main.js:116459:3
	at Object.<anonymous> (.vscode-server/extensions/ms-vscode.cpptools-1.21.6/dist/src/main.js:116462:12)
	at Module._compile (node:internal/modules/cjs/loader:1358:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
	at Module.load (node:internal/modules/cjs/loader:1208:32)
	at Module._load (node:internal/modules/cjs/loader:1024:12)
	at y._load (.vscode-server/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/vs/workbench/api/node/extensionHostProcess.js:177:6051)
	at i._load (.vscode-server/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/vs/workbench/api/node/extensionHostProcess.js:174:31787)
	at o._load (.vscode-server/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/vs/workbench/api/node/extensionHostProcess.js:139:34334)
	at Module.require (node:internal/modules/cjs/loader:1233:19)
	at require (node:internal/modules/helpers:179:18)
	at Function.i [as __$__nodeRequire] (.vscode-server/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/bootstrap-fork.js:3:98)
	at m.xb (.vscode-server/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/vs/workbench/api/node/extensionHostProcess.js:174:32966)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 0)

**Comment by mdeberts** [comment]
updated my upper post, since somehow connecting via remote shh from my windows machine it is not working, but if I connect via remote ssh from my linux machine it works.

**Comment by sean-mcmanus** [comment]
@mdeberts @Thomasyse Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.22.0

**Comment by mdeberts** [comment]
Thanks it’s working for me again.
Really appreciate it.

**Comment by Colengms** [comment]
Closing as fixed.
