### ISSUE TITLE
`Error: Invalid debug adapter` message from Extension Host

### ISSUE THREAD

**Issue by AIM289** [microsoft/vscode-cpptools#12912]
### Environment

- OS and version: Ubuntu 22.04 
- VS Code: v1.94.0
- C/C++ extension: v1.22.10
- OS and version of remote machine (if applicable): None
- GDB / LLDB version: GDB v12.1

### Bug Summary and Steps to Reproduce

Bug Summary:

Upon stopping any debugging session, even when using just the default launch configuration, the VS Code extension host outputs the following:

```
[error] Error: Invalid debug adapter
    at H2t.p (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:619:95)
    at H2t.$acceptDAExit (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:619:35)
    at Ult.S (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3108:41550)
    at Ult.Q (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3108:41328)
    at Ult.M (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3108:40416)
    at Ult.L (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3108:39653)
    at NQ.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3108:38314)
    at x.B (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:733)
    at x.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:951)
    at n6.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:634:10283)
    at l.onmessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3119:11714)
```

There are no issues during the debugging session itself. This message only occurs when using a `cppdbg` type launch configuration, and not with other debug adapters (I tried with CodeLLDB).

### Debugger Configurations

```
{
    "name": "(gdb) Launch",
    "type": "cppdbg",
    "request": "launch",
    "program": "${workspaceFolder}/hello_world",
    "args": [],
    "stopAtEntry": false,
    "cwd": "${fileDirname}",
    "environment": [],
    "externalConsole": false,
    "MIMode": "gdb",
    "setupCommands": [
        {
            "description": "Enable pretty-printing for gdb",
            "text": "-enable-pretty-printing",
            "ignoreFailures": true
        },
        {
            "description": "Set Disassembly Flavor to Intel",
            "text": "-gdb-set disassembly-flavor intel",
            "ignoreFailures": true
        }
    ]
}
```

### Debugger Logs

```
[error] Error: Invalid debug adapter
    at H2t.p (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:619:95)
    at H2t.$acceptDAExit (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:619:35)
    at Ult.S (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3108:41550)
    at Ult.Q (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3108:41328)
    at Ult.M (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3108:40416)
    at Ult.L (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3108:39653)
    at NQ.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3108:38314)
    at x.B (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:733)
    at x.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:951)
    at n6.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:634:10283)
    at l.onmessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3119:11714)
```

**Comment by sean-mcmanus** [comment]
@AIM289 Is it just an issue with the error logging on shutdown or is some functionality broken as a result?

**Comment by AIM289** [comment]
> [@AIM289](https://github.com/AIM289) Is it just an issue with the error logging on shutdown or is some functionality broken as a result?

@sean-mcmanus I have no issues with the functionality. I am working on a VS Code extension for which the automated tests involve starting and stopping debug sessions, so this message appears everywhere in the logs. Just a minor annoyance I thought may be worth bringing to your attention.
