### ISSUE TITLE
Error: Request textDocument/documentSymbol failed.

### ISSUE THREAD

**Issue by astepanov83** [microsoft/vscode-cpptools#1373]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.10.0-42-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
empty-indent|Dmi|0.2.0
githistory|don|0.2.3
gitlens|eam|7.1.0
cpptools|ms-|0.14.5
vscode-icons|rob|7.19.0
cmake|twx|0.0.17
vscode-lldb|vad|0.7.3
cmake-tools|vec|0.10.4

[stacktrace.txt](https://github.com/Microsoft/vscode-cpptools/files/1584919/stacktrace.txt)
---

I was using VS code and at some moment it started lagging. Around 10 seconds passed and the following (added to attachments) appeared in the Output. I could continue working without problems. But decided to report this anyway. I really cannot describe steps to reproduce, it was in the middle of typing code or moving the mouse over text. I was developing C++ code with CMake.

The whole output is in the attachment. But looks like it consists of the same message repeated many times:

> [Error - 6:18:49 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/alex/.vscode/extensions/ms-vscode.cpptools-0.14.5/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/home/alex/.vscode/extensions/ms-vscode.cpptools-0.14.5/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/home/alex/.vscode/extensions/ms-vscode.cpptools-0.14.5/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/home/alex/.vscode/extensions/ms-vscode.cpptools-0.14.5/node_modules/vscode-languageclient/lib/main.js:78:15)
	at closeHandler (/home/alex/.vscode/extensions/ms-vscode.cpptools-0.14.5/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/home/alex/.vscode/extensions/ms-vscode.cpptools-0.14.5/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/home/alex/.vscode/extensions/ms-vscode.cpptools-0.14.5/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/home/alex/.vscode/extensions/ms-vscode.cpptools-0.14.5/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/home/alex/.vscode/extensions/ms-vscode.cpptools-0.14.5/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/home/alex/.vscode/extensions/ms-vscode.cpptools-0.14.5/node_modules/vscode-jsonrpc/lib/events.js:135:36)

**Comment by bobbrow** [comment]
Do you see any Microsoft.VSCode.CPP.* processes running? I'm curious as to whether the language server is ever running or not on this distro.  This stack implies that the language server protocol module is unable to establish a reliable connection to our extension processes.  We have code that tells the extension to give up after a number of failures, but it doesn't seem to be applied in your case so I should revisit this.

**Comment by astepanov83** [comment]
Sorry for late reply.

I don't remember if they were running at the moment of the bug. The plugin is always enabled. I also can see processes right now:

alex@KU1604VM:~$ ps ax | grep Microsoft
 34571 ?        Sl     1:34 /home/alex/.vscode/extensions/ms-vscode.cpptools-0.14.6/bin/Microsoft.VSCode.CPP.Extension.linux
 37634 ?        Sl     0:00 /home/alex/.vscode/extensions/ms-vscode.cpptools-0.14.6/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 34571 4
 69623 ?        Sl     0:12 /home/alex/.vscode/extensions/ms-vscode.cpptools-0.14.6/bin/Microsoft.VSCode.CPP.Extension.linux
 69674 ?        Sl     0:01 /home/alex/.vscode/extensions/ms-vscode.cpptools-0.14.6/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 69623 0

No signs of the bug since then.

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.
