### ISSUE TITLE
Failed to install VS Code C++ Insiders March 2018 release

### ISSUE THREAD

**Issue by daldr-ntml** [microsoft/vscode-cpptools#1680]
Running VS Code 1.21.0 on Windows 10 with Cpp Tools 0.15.0 installed.

Clicked on http://landinghub.visualstudio.com/e1t/c/*W95g2QS3lvCpnW90Jvym8xvv-M0/*N3zCT3t8zJN2W9fQMg76CSFkz0/5/f18dQhb0SmhS9ctymFW8Xlp2N2qwv1SN2sthYc5Z1dNMf5w2dXD6prW7cmS1s8xX29mW626LvD96Ls9jW5DrmzD7dDrBLW982Z8y95DnKzW7lDX0N97cNCNW97QBs_6bwHsDW7dDMwV8nNzQrN50FkqfdPgL4W4sNsF_4sglTyW69_ncj7lF8h0W17F5lc1WwdlNW8Y_CSy1CGSgwW4bJ02h4b_rKwW7MbC5J4N8F9gW5KQ7zP1tBhzBW1N58dB7nY0byW2XVdyK7xR9_sW2Vjhb05bPQ0kW7v4x2t5kG09VW7lYt772R4SCCW2GGqc92JDgVLW1-kxTr5WnM8TW5-2sjB7ZzDyKW7GLjPj2LG_MKW7XPwVp717sW1W1xslTg7q7b6cW1-gCRD7vZstnW1Mk4BJ1gqfcdW7HQNtb2Mq8hYW1fyTg01-cV7TW6jVTWf7Lzd7wW24bGF51HmN_FW1lml2x1CcdpRW1WXpYB84vxbFW7H28lL2gD6DFW7ZKxXf1z8XKrW777R_d1Cs-V5W7KLHcL1mp3F4W4KfDzc72Vff2W6kxyZl2bzNQYW5-kFYs2_YDGRW33FYct30TkcSW1TSGbZ31XGpjW30Y4Nw1CksCfW7gYswV3K_tbTW89xKnf8CrcDTW7-5Sln5Q2Q_yW6LkY4K88XzZhW5bbDYK4Pv86fM5XPb2Hqpv1102

Chose to install, but installation failed:

13/03/2018 11:19:11 - Microsoft VSIX Installer
13/03/2018 11:19:11 - -------------------------------------------
13/03/2018 11:19:11 - vsixinstaller.exe version:
13/03/2018 11:19:11 - 15.6.152+ge95e4dd1ce
13/03/2018 11:19:11 - -------------------------------------------
13/03/2018 11:19:11 - Command line parameters:
13/03/2018 11:19:11 - C:\program files (x86)\microsoft visual studio\installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\daldrich\AppData\Local\Packages\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\TempState\Downloads\cpptools-win32.vsix
13/03/2018 11:19:11 - -------------------------------------------
13/03/2018 11:19:11 - Microsoft VSIX Installer
13/03/2018 11:19:11 - -------------------------------------------
13/03/2018 11:19:12 - Initializing Install...
13/03/2018 11:19:13 - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: Element 'Identity' has invalid value for attribute 'Version' ---> System.FormatException: Input string was not in a correct format.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.<>c.<ExtractManifestData>b__64_1(String s)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ExtractManifestData(PackageManifest manifest)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadPackageManifest(XmlReader reader)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadManifest(Stream manifestStream)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath)
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by sean-mcmanus** [comment]
I don't know what that link is, but it doesn't belong to our cpptools product. It looks like some Visual Studio thing. Please try https://code.visualstudio.com/ , and then https://github.com/Microsoft/vscode-cpptools/releases/download/v0.16.0-insiders/cpptools-win32.vsix (use the Install from VSIX command).

Our extension only works in VS Code and not Visual Studio. The vsix format is different.

**Comment by daldr-ntml** [comment]
I get the same error when I click https://github.com/Microsoft/vscode-cpptools/releases/download/v0.16.0-insiders/cpptools-win32.vsix and invoke the vsix file. Please reopen this issue.

![image](https://user-images.githubusercontent.com/7724321/37392270-963c0ee4-2765-11e8-94dc-a46f51fff776.png)

**Comment by bobbrow** [comment]
Invoking the vsix will attempt to open it in visual studio, not vs code. This vsix won't work in visual studio. To install it you need to go to the extension manager in vs code, click the '...' then 'install from vsix'.

**Comment by daldr-ntml** [comment]
Thank you. It's working now.

**Comment by sean-mcmanus** [comment]
I've added an instruction line on the release page explaining how to install the vsix to prevent others from being confused.
