### ISSUE TITLE
CppTools Debugger says "Debug adapter process has terminated unexpectedly" on Arch Linux

### ISSUE THREAD

**Issue by Azero-NG** [microsoft/vscode-cpptools#1719]
1. System:
```
cat /proc/version
Linux version 4.15.9-1-ARCH (builduser@heftig-13420) (gcc version 7.3.0 (GCC)) #1 SMP PREEMPT Sun Mar 11 17:54:33 UTC 2018
```

2. vs code:
1.21.1-1
3. cpptolls:
0.15.0
4. other extension:
none

5. launch.json
```
{
    "version": "0.2.0",
    "configurations": [
    {
        "name": "(gdb) Launch",
        "type": "cppdbg",
        "request": "launch",
        "program": "${workspaceFolder}/a.out",
        "args": [],
        "stopAtEntry": false,
        "cwd": "${workspaceFolder}",
        "environment": [],
        "externalConsole": true,
        "MIMode": "gdb",
        "setupCommands": [
            {
                "description": "Enable pretty-printing for gdb",
                "text": "-enable-pretty-printing",
                "ignoreFailures": true
            }
        ]
    },
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```
6.cpp file
```
#include <iostream>
using namespace std;
int main(){
    cout<<"cpp tools test";
}

```

7. a.out
g++ test.cpp -g

8.error 

```
index.js:5 [uncaught exception]: Error: read ECONNRESET
onError @ index.js:5
index.js:5 Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at Pipe.onread (net.js:581:26)
onError @ index.js:5
events.js:163 Uncaught Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at Pipe.onread (net.js:581:26)
/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:2207 调Debug adapter process has terminated unexpectedly
e.onDidNotificationChange @ /opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:2207
index.js:5 [uncaught exception]: Error: read ECONNRESET
onError @ index.js:5
index.js:5 Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at Pipe.onread (net.js:581:26)
onError @ index.js:5
events.js:163 Uncaught Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at Pipe.onread (net.js:581:26)
/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:2207 Debug adapter process has terminated unexpectedly
e.onDidNotificationChange @ /opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:2207
```

**Comment by pieandcakes** [comment]
I'm asking VS Code for more info on how this can be debugged as it looks like it is happening on other extensions too. I'll keep you posted or you can look at the linked item

**Comment by pieandcakes** [comment]
@Azero-NG It looks like their response is that the extension did not install correctly and their suggestion is to reinstall the extension by the following process:

1. Uninstall the extension
2. Go to your `~/.vscode/extensions` folder and make sure that the extension is gone
3. reinstall the extension.

Can you try that and see if it fixes the problem?

Thanks!

**Comment by Azero-NG** [comment]
It's ok.Thank you very much!
