### ISSUE TITLE
Extension fails silently to install if extensions-home-folder is missing execution rights on Windows

### ISSUE THREAD

**Issue by ankostis** [microsoft/vscode-cpptools#1873]
The extension (in VSCode-1.22.2 ) cannot work under Windows if folder `%USERPROFILE%\.vscode\extensions` has not *execution* rights.
This problem can be solved using `--extensionHomePath` option.

The real problem is that there is no log record explaining this installation problem when it happens!

Below are the relevant logs,  after having waited for at least 5':

### after *install*:
```
[2018-04-25 18:59:45.056] [sharedprocess] [info] Scanned user extensions: 0
[2018-04-25 18:59:45.219] [sharedprocess] [info] Scanned system extensions: 69
[2018-04-25 18:59:47.152] [sharedprocess] [info] Scanned user extensions: 0
[2018-04-25 18:59:47.154] [sharedprocess] [info] Scanned user extensions: 0
[2018-04-25 18:59:47.191] [sharedprocess] [info] Scanned system extensions: 69
[2018-04-25 18:59:51.990] [sharedprocess] [info] Scanned user extensions: 0
[2018-04-25 18:59:58.192] [sharedprocess] [info] Scanned user extensions: 0
[2018-04-25 18:59:58.195] [sharedprocess] [info] Scanned user extensions: 0
[2018-04-25 18:59:58.195] [sharedprocess] [info] Scanned user extensions: 0
[2018-04-25 18:59:58.280] [sharedprocess] [info] Scanned system extensions: 69
[2018-04-25 18:59:58.283] [sharedprocess] [info] Scanned system extensions: 69
[2018-04-25 19:00:15.607] [sharedprocess] [info] Installing extension: cpptools
[2018-04-25 19:00:16.257] [sharedprocess] [info] Downloaded extension: cpptools
[2018-04-25 19:00:21.298] [sharedprocess] [info] Extracted extension to C:\Users\username\.vscode\extensions\.ms-vscode.cpptools-0.16.1: ms-vscode.cpptools-0.16.1
[2018-04-25 19:00:21.300] [sharedprocess] [info] Renamed to C:\Users\username\.vscode\extensions\ms-vscode.cpptools-0.16.1
[2018-04-25 19:00:21.300] [sharedprocess] [info] Installation completed. ms-vscode.cpptools-0.16.1
[2018-04-25 19:00:21.398] [sharedprocess] [info] Extensions installed successfully: ms-vscode.cpptools
[2018-04-25 19:00:21.543] [sharedprocess] [info] Scanned user extensions: 1
[2018-04-25 19:00:21.576] [sharedprocess] [info] Scanned system extensions: 69
[2018-04-25 19:00:25.027] [sharedprocess] [info] Starting to clean up unused language packs.
```
### after *reload*:
```
[2018-04-25 19:03:40.888] [sharedprocess] [info] Scanned user extensions: 1
[2018-04-25 19:03:40.889] [sharedprocess] [info] Scanned user extensions: 1
[2018-04-25 19:03:40.895] [sharedprocess] [info] Scanned user extensions: 1
[2018-04-25 19:03:40.909] [sharedprocess] [info] Scanned user extensions: 1
[2018-04-25 19:03:40.910] [sharedprocess] [info] Scanned user extensions: 1
[2018-04-25 19:03:40.988] [sharedprocess] [info] Scanned system extensions: 69
[2018-04-25 19:03:40.993] [sharedprocess] [info] Scanned system extensions: 69
[2018-04-25 19:03:40.998] [sharedprocess] [info] Scanned system extensions: 69
[2018-04-25 19:03:44.133] [sharedprocess] [info] Scanned user extensions: 1
```

## Log (Extension), after *reload*:
```
[2018-04-25 18:59:48.645] [exthost1] [info] extension host started
[2018-04-25 18:59:48.669] [exthost1] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
...
[2018-04-25 19:03:42.396] [exthost1] [info] ExtensionService#loadCommonJSModule c:\AFolder\VSCode-x64-1.22.2\resources\app\extensions\merge-conflict\out\extension
[2018-04-25 19:03:42.420] [exthost1] [info] ExtensionService#_doActivateExtension ms-vscode.cpptools {"startup":true,"activationEvent":"*"}
[2018-04-25 19:03:42.420] [exthost1] [info] ExtensionService#loadCommonJSModule C:\Users\username\.vscode\extensions\ms-vscode.cpptools-0.16.1\out\src\main
[2018-04-25 19:03:42.733] [exthost1] [info] eager extensions activated
[2018-04-25 19:03:42.745] [exthost1] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"activationEvent":"onLanguage:jsonc"}
[2018-04-25 19:03:42.745] [exthost1] [info] ExtensionService#loadCommonJSModule c:\AFolder\VSCode-x64-1.22.2\resources\app\extensions\configuration-editing\out\extension
[2018-04-25 19:03:42.758] [exthost1] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"activationEvent":"onLanguage:jsonc"}
[2018-04-25 19:03:42.758] [exthost1] [info] ExtensionService#loadCommonJSModule c:\AFolder\VSCode-x64-1.22.2\resources\app\extensions\json-language-features\client\out\jsonMain
```
### after *reload*:
```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' (5225 KB) .................... Done!
Downloading package 'ClangFormat (Windows)' (796 KB) .................... Done!
Downloading package 'Visual Studio Windows Debugger' (12072 KB) .................... Done!

Installing package 'C/C++ language components (Windows)'
Installing package 'ClangFormat (Windows)'
Installing package 'Visual Studio Windows Debugger'

Finished installing dependencies
```

### after *restart*
```
Finished installing dependencies
```

### after *reload*, `level=Info`
```
[C:\Users\username\.vscode\extensions\ms-vscode.cpptools-0.16.1]: Command `workbench.action.gotoSymbol` appears multiple times in the `commands` section.
extensionService.ts:852 [C:\Users\username\.vscode\extensions\ms-vscode.cpptools-0.16.1]: Command `workbench.action.showAllSymbols` appears multiple times in the `commands` section.
console.ts:136 [Extension Host] activating extension
console.ts:136 [Extension Host] starting language server
notificationsAlerts.ts:39 Unable to start the C/C++ language server. IntelliSense features will be disabled.
e.onDidNotificationChange @ notificationsAlerts.ts:39
```
### after *restart*, `level=verbose`
```
[C:\Users\username\.vscode\extensions\ms-vscode.cpptools-0.16.1]: Command `workbench.action.gotoSymbol` appears multiple times in the `commands` section.
/D:/Apps/VSCode-x64-1.22.2/resources/app/out/vs/workbench/workbench.main.js:2868 [C:\Users\username\.vscode\extensions\ms-vscode.cpptools-0.16.1]: Command `workbench.action.showAllSymbols` appears multiple times in the `commands` section.
15/D:/Apps/VSCode-x64-1.22.2/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] TypeError: Cannot read property 'provideDecoration' of undefined
	at c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:513:498
	at c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:525
	at new n.Class.derive._oncancel (c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:76:378)
	at Object.t.asWinJsPromise (c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:488)
	at c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:513:463
	at Array.map (native)
	at e.$provideDecorations (c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:513:387)
	at e._doInvokeHandler (c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:560:395)
	at e._invokeHandler (c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:560:113)
	at e._receiveRequest (c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:559:237)
	at e._receiveOneMessage (c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:559:6)
	at c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:558:75
	at c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:560:929
	at c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:30
	at e.fire (c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:344)
	at Socket.<anonymous> (c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:143:1008)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
t.log @ /D:/Apps/VSCode-x64-1.22.2/resources/app/out/vs/workbench/workbench.main.js:260
/D:/Apps/VSCode-x64-1.22.2/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] activating extension
45/D:/Apps/VSCode-x64-1.22.2/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] TypeError: Cannot read property 'provideDecoration' of undefined
	at c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:513:498
	at c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:525
	at new n.Class.derive._oncancel (c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:76:378)
	at Object.t.asWinJsPromise (c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:488)
	at c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:513:463
	at Array.map (native)
	at e.$provideDecorations (c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:513:387)
	at e._doInvokeHandler (c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:560:395)
	at e._invokeHandler (c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:560:113)
	at e._receiveRequest (c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:559:237)
	at e._receiveOneMessage (c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:559:6)
	at c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:558:75
	at c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:560:929
	at c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:30
	at e.fire (c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:344)
	at Socket.<anonymous> (c:\AFolder\VSCode-x64-1.22.2\resources\app\out\vs\workbench\node\extensionHostProcess.js:143:1008)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
t.log @ /D:/Apps/VSCode-x64-1.22.2/resources/app/out/vs/workbench/workbench.main.js:260
```
The only indication i got that something is not working is in the last two DevTools console logs.

**Comment by bobbrow** [comment]
Did you get a notification that said the language server could not be started?  If the extension crashes or fails to launch multiple times in a 5 minute window, you are supposed to get a notification.

**Comment by ankostis** [comment]
My apologies for not pasting the logs, had to leave our building in a hurry yesterday.
I've updated just now the opening post with all logs, as advised, after having waited for at least 5'.

Some comments:
- You are right, there is an error, but only on Chrome's Dev tools console.
- Unfortunately, there isn't any message in any of the vscode OUTPUT panes.
- Additionally, the message ` Unable to start the C/C++ language server. IntelliSense features will be disabled.` is only visible for the 1st time after installation.
- Eventually, none of the messages i collected helped me to debug the permissions problem i had.

**Comment by bobbrow** [comment]
Thanks for the information.  I added additional logging for the failure scenario and changed the policy to show the message once per session instead of once in forever.

**Comment by bobbrow** [comment]
The messaging for this scenario has been updated in 0.17.0.
