### ISSUE TITLE
Unable to launch in ubuntu

### ISSUE THREAD

**Issue by wpp2014** [microsoft/vscode-cpptools#188]
bash: 无法设定终端进程组(-1): 对设备不适当的 ioctl 操作
bash: 此 shell 中无任务控制
Error: watch /home/wpp/.config/Code/User ENOSPC
    at exports._errnoException (util.js:890:11)
    at FSWatcher.start (fs.js:1323:19)
    at Object.fs.watch (fs.js:1351:11)
    at t.e.registerWatchers (/home/wpp/Desktop/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:7:164)
    at t.e (/home/wpp/Desktop/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:6:31426)
    at new t (/home/wpp/Desktop/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:8:976)
    at v (/home/wpp/Desktop/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:4:19369)
    at t._createInstance (/home/wpp/Desktop/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:7:24479)
    at t._createAndCacheServiceInstance (/home/wpp/Desktop/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:7:25454)
    at t._getOrCreateServiceInstance (/home/wpp/Desktop/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:7:24640)

**Comment by jacdavis** [comment]
Thanks for reporting this issue. 

We are not able to repro this issue with this information. Which version of Ubuntu are you running and on one processor architecture? Which version of GDB are you using? Are you running the standard installed version of bash on this Ubuntu? 

ENOSPC is normally the error posix systems return when a device is out of disk space and/or memory. Can you confirm that you have a reasonable amount of disk space available?

**Comment by wpp2014** [comment]
My Ubuntu is 16.04 x86_64 and the gdb's version is 7.11.1。The  vscode I used is 1.4.0。

**Comment by delmyers** [comment]
@wpp2014, have you confirmed that you have enough memory and disk space on your machine to perform this operation?

**Comment by wpp2014** [comment]
My machine has machine and disk space. I tried on different machine and I encountered the same problem.

**Comment by edumunoz** [comment]
Hi @wpp2014 

This error is coming from VSCode (not the C/C++ extension) and I assume when you said you can't launch on Ubuntu, you meant you can't open VSCode.

Here's some documentation on how to fix that problem
https://code.visualstudio.com/docs/setup/linux

(Ctrl+F for `ENOSPC`)

Let us know if that helps. If the problem is with the VSCode itself and not the extension, you can search for existing issues or create a new one here https://github.com/microsoft/vscode/issues

**Comment by wpp2014** [comment]
I think the problem is with the VSCode itself and not the extension. Thank you.

**Comment by pieandcakes** [comment]
@wpp2014 you can find VSCode's issue page at https://github.com/microsoft/vscode/issues. If the document that Ed mentioned above doesn't work, please file an issue there.
