### ISSUE TITLE
extension crashed in diff view

### ISSUE THREAD

**Issue by liwangqian** [microsoft/vscode-cpptools#2018]
Issue Type: <b>Bug</b>

[Error - 10:43:43] Request textDocument/definition failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\xxxxxxxxx\.vscode\extensions\ms-vscode.cpptools-0.17.1\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\xxxxxxxxx\.vscode\extensions\ms-vscode.cpptools-0.17.1\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\xxxxxxxxx\.vscode\extensions\ms-vscode.cpptools-0.17.1\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\xxxxxxxxx\.vscode\extensions\ms-vscode.cpptools-0.17.1\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\xxxxxxxxx\.vscode\extensions\ms-vscode.cpptools-0.17.1\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\xxxxxxxxx\.vscode\extensions\ms-vscode.cpptools-0.17.1\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\xxxxxxxxx\.vscode\extensions\ms-vscode.cpptools-0.17.1\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\xxxxxxxxx\.vscode\extensions\ms-vscode.cpptools-0.17.1\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\xxxxxxxxx\.vscode\extensions\ms-vscode.cpptools-0.17.1\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\xxxxxxxxx\.vscode\extensions\ms-vscode.cpptools-0.17.1\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at StreamMessageReader.AbstractMessageReader.fireClose (C:\Users\xxxxxxxxx\.vscode\extensions\ms-vscode.cpptools-0.17.1\node_modules\vscode-jsonrpc\lib\messageReader.js:135:27)
	at Socket.<anonymous> (C:\Users\xxxxxxxxx\.vscode\extensions\ms-vscode.cpptools-0.17.1\node_modules\vscode-jsonrpc\lib\messageReader.js:188:62)
	at emitOne (events.js:101:20)
	at Socket.emit (events.js:191:7)
	at Pipe._handle.close [as _onclose] (net.js:510:12)

Extension version: 0.17.1
VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.1.7601

**Comment by sean-mcmanus** [comment]
The main process crashed. I believe it's a duplicate of https://github.com/Microsoft/vscode-cpptools/issues/2006 . Removing recursive includes (i.e. "**") from your includePath should make it more stable. Or using 0.17.0 (see https://github.com/Microsoft/vscode-cpptools/releases ). We're working on releasing a more stable version.

**Comment by sean-mcmanus** [comment]
We have an insider build you can try that may have the fix: https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.2-insiders . The official release is planned tomorrow unless we get delayed by finding more bugs.

UPDATE: 0.17.3 fixed a bunch of issues which could cause this. Let us know if you still have issues.

**Comment by liwangqian** [comment]
thanks
