### ISSUE TITLE
The language server crashed 5 times in the last 3 minutes. It will not be restarted.

### ISSUE THREAD

**Issue by dust2015** [microsoft/vscode-cpptools#2158]
System Environment：
      Processor：Intel(R)Core(TM) i5-7500 @ 3.40GHz 3.41 GHz
      Installed memory(RAM): 8.00GB(7.89 usable)
      System type 64-bit operating system, x64-base processor
      Edition   Windows 10 Pro
      Version 1709
      OS Build 16299.492
software info:
      C/C++ IntelliSense 0.17.4

Problem recurrence steps：
       1. install the  C/C++ IntelliSense 0.17.4
       2. restart vscode
 
Exception log：

[Error - 12:31:02 PM] Connection to server got closed. Server will not be restarted.
[Error - 12:31:02 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at StreamMessageWriter.AbstractMessageWriter.fireClose (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-jsonrpc\lib\messageWriter.js:57:27)
	at Socket.<anonymous> (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-jsonrpc\lib\messageWriter.js:79:63)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at Pipe._handle.close [as _onclose] (net.js:554:12)
[Error - 12:31:02 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at StreamMessageWriter.AbstractMessageWriter.fireClose (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-jsonrpc\lib\messageWriter.js:57:27)
	at Socket.<anonymous> (C:\Users\jgu3\.vscode-insiders\extensions\ms-vscode.cpptools-0.17.4\node_modules\vscode-jsonrpc\lib\messageWriter.js:79:63)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at Pipe._handle.close [as _onclose] (net.js:554:12)

**Comment by dust2015** [comment]
@sean-mcmanus

**Comment by sean-mcmanus** [comment]
That info is not helpful -- we need a call stack of the crashing process, Microsoft.VSCode.CPP.Extension.exe . Can you attach to the process with a debugger before the crash occurs.

We should be releasing 0.17.5 today, which may have a fix.

**Comment by goodloop** [comment]
same thing happens on mac version with extension 0.17.5

**Comment by sean-mcmanus** [comment]
@goodloop The previous crash was fixed. It's the same symptom (crashing) but a different cause. We fixed some crashes in our pending 0.17.6 update for today (it fixes our highest hitting crashes, so it most likely fixes your issue). If you're still hitting the crashes in that release, please provide the crash logs from you user Library/Logs/DiagnosticReports folder (just the crashing call stack, not the entire log).

**Comment by goodloop** [comment]
@sean-mcmanus looks good for me with 0.17.6.  Thanks!

**Comment by bobbrow** [comment]
Let us know if you are continuing to hit this.
