### ISSUE TITLE
Error appears, but intellisense works

### ISSUE THREAD

**Issue by cmh1027** [microsoft/vscode-cpptools#2179]
![gif](https://user-images.githubusercontent.com/22341329/41815461-b07c9e18-77a6-11e8-9db3-87baa74464c4.gif)
As you can see, there's a squiggle under the iostream header, saying cannot open source file "corecrt.h"
And this is the same as every header file.
However, intellisense works even though the squiggle appears. I can ignore it and just use it, but I think that I should let you know this strange behavior.

![default](https://user-images.githubusercontent.com/22341329/41815462-b0a557c2-77a6-11e8-9ac3-4e75bf20fd1c.PNG)
With a squiggle, there is an error message.

```
[Error - 12:09:10] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\Coder\.vscode\extensions\ms-vscode.cpptools-0.17.5\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\Coder\.vscode\extensions\ms-vscode.cpptools-0.17.5\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\Coder\.vscode\extensions\ms-vscode.cpptools-0.17.5\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\Coder\.vscode\extensions\ms-vscode.cpptools-0.17.5\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\Coder\.vscode\extensions\ms-vscode.cpptools-0.17.5\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\Coder\.vscode\extensions\ms-vscode.cpptools-0.17.5\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\Coder\.vscode\extensions\ms-vscode.cpptools-0.17.5\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\Coder\.vscode\extensions\ms-vscode.cpptools-0.17.5\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\Coder\.vscode\extensions\ms-vscode.cpptools-0.17.5\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\Coder\.vscode\extensions\ms-vscode.cpptools-0.17.5\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at StreamMessageWriter.AbstractMessageWriter.fireClose (C:\Users\Coder\.vscode\extensions\ms-vscode.cpptools-0.17.5\node_modules\vscode-jsonrpc\lib\messageWriter.js:57:27)
	at Socket.<anonymous> (C:\Users\Coder\.vscode\extensions\ms-vscode.cpptools-0.17.5\node_modules\vscode-jsonrpc\lib\messageWriter.js:79:63)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at Pipe._handle.close [as _onclose] (net.js:510:12)
```

And this is my configuration.

```
{
    "configurations": [
        {
            "name": "Win32",
            "intelliSenseMode": "clang-x64",
            "includePath": [
                "${workspaceRoot}",
                "c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../include/c++/7.2.0",
                "c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../include/c++/7.2.0/x86_64-w64-mingw32",
                "c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../include/c++/7.2.0/backward",
                "c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include",
                "c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include-fixed",
                "c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "__GNUC__=7",
                "__cdecl=__attribute__((__cdecl__))",
                "__SIZE_TYPE__=unsigned int"
            ],
            "browse": {
                "path": [
                    "${workspaceRoot}",
                    "c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../include/c++/7.2.0",
                    "c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../include/c++/7.2.0/x86_64-w64-mingw32",
                    "c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../include/c++/7.2.0/backward",
                    "c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include",
                    "c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include-fixed",
                    "c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/include"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 3
}
```

**Comment by bobbrow** [comment]
Can you try using the "compilerPath" property in `c_cpp_properties.json` instead of manually listing the system include paths and defines?

Something like this:
```
{
    "configurations": [
        {
            "name": "Win32",
            "intelliSenseMode": "clang-x64",
            "includePath": [
                "${workspaceRoot}"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "compilerPath": "c:/mingw/bin/g++.exe",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 3
}
```
Also, make sure you've updated to the latest version of the extension: 0.17.5.  I expected to see `"version": 4` in your config file.

**Comment by cmh1027** [comment]
I changed my configuration, but it still shows a squiggle. with a same error message.
And I just found one more thing.
![abc](https://user-images.githubusercontent.com/22341329/42078310-f17acf16-7bb6-11e8-88a0-4fd4f58225b7.gif)
It certainly seems that VS Code knows and recognizes where header files are.

**Comment by bobbrow** [comment]
It's just missing a dependency, so many of the included types will likely be available for IntelliSense.  corecrt.h is a Windows SDK header, and your GIF is showing a Visual Studio header in the auto complete list, so it seems like the extension thinks you're using Visual Studio's headers, not MinGW's.

Can you set `"C_Cpp.loggingLevel": "Debug"`, reload the folder, then share the "C/C++" logs from the Output Window?  **(note: there may be personal info in there, so redact anything that you don't want made public)**

**Comment by cmh1027** [comment]
I can not understand what you mean by "share the "C/C++" logs from the Output Window"
Do you mean this log?
```
initialized
workspace/didChangeConfiguration
IntelliSense Engine = Default.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
textDocument/didOpen
cpptools/queryCompilerDefaults
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
textDocument/codeAction
cpptools/didChangeFolderSettings
Code browsing service initialized
  Folder: C:/ will be indexed
Discovering files...
textDocument/didOpen
  Processing folder (recursive): C:/
sending compilation args for C:\USERS\CODER\DESKTOP\WORKSPACE\MERGE.CPP
  include: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE
  define: _DEBUG
  define: UNICODE
  define: _UNICODE
  stdver: --ms_c++latest
Checking for syntax errors: file:///c%3A/Users/Coder/Desktop/workspace/merge.cpp
queue_update_intellisense for files in tu of: C:\USERS\CODER\DESKTOP\WORKSPACE\MERGE.CPP
errorSquiggles count: 18
Tag Parser will be used for IntelliSense operations in: file:///c%3A/Users/Coder/Desktop/workspace/merge.cpp
textDocument/codeAction
Database safe to open
```

It seems that include path is wrong like you said.

**Comment by sean-mcmanus** [comment]
Yeah, that's the log file. You're missing the Windows SDK in your includePath, which is where correct.h is from. It looks like it's trying to use "cl.exe" as your compiler instead of mingw. Setting your compilerPath to the mingw compiler might fix it as Bob suggested earlier.

**Comment by cmh1027** [comment]
Problem is solved by adding `"C_Cpp.default.compilerPath": "c:/mingw/bin/g++.exe" ` in User settings because adding `"compilerPath": "c:/mingw/bin/g++.exe"` in c_cpp_properties.json doesn't show any change. Anyway, thanks!

**Comment by cmh1027** [comment]
```
{
    "configurations": [
        {
            "name": "Win32",
            "intelliSenseMode": "clang-x64",
            "includePath": [
                "${workspaceRoot}"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "compilerPath": "c:/mingw/bin/g++.exe",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```
I set c_cpp_properties.json like above.
But strangely,
```
initialized
workspace/didChangeConfiguration
IntelliSense Engine = Default.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
textDocument/didOpen
cpptools/queryCompilerDefaults
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
textDocument/codeAction
cpptools/didChangeFolderSettings
Code browsing service initialized
  Folder: C:/ will be indexed
Discovering files...
textDocument/didOpen
  Processing folder (recursive): C:/
  tag parsing file: C:\USERS\CODER\DESKTOP\WORKSPACE\MERGE.CPP
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\IOSTREAM
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\ISTREAM
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\OSTREAM
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\IOS
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\XLOCNUM
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\CLIMITS
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\CMATH
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\CSTDIO
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\CSTDLIB
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\STREAMBUF
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\YVALS.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\LIMITS.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\XTGMATH.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\XIOSBASE
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\XKEYCHECK.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\CRTDEFS.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\USE_ANSI.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\VCRUNTIME.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\XTR1COMMON
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\XLOCALE
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\SYSTEM_ERROR
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\SAL.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\VADEFS.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\CSTRING
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\STDEXCEPT
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\TYPEINFO
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\XLOCINFO
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\XFACET
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\CERRNO
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\CODEANALYSIS\SOURCEANNOTATIONS.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\CONCURRENCYSAL.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\EXCEPTION
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\XSTRING
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\XSTDDEF
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\VCRUNTIME_TYPEINFO.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\XLOCINFO.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\TYPE_TRAITS
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\VCRUNTIME_EXCEPTION.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\XMEMORY0
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\CSTDDEF
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\INITIALIZER_LIST
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\EH.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\VCRUNTIME_NEW.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\CSTDINT
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\LIMITS
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\NEW
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\XUTILITY
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\XATOMIC0.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\INTRIN.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\XATOMIC.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\STDINT.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\YMATH.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\CFLOAT
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\CWCHAR
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\UTILITY
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\SETJMP.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\IMMINTRIN.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\AMMINTRIN.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\MM3DNOW.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\ARMINTR.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\ARM_NEON.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\IOSFWD
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\SETJMPEX.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\WMMINTRIN.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\MMINTRIN.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\XMMINTRIN.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\NMMINTRIN.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\SMMINTRIN.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\TMMINTRIN.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\PMMINTRIN.H
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE\EMMINTRIN.H
sending compilation args for C:\USERS\CODER\DESKTOP\WORKSPACE\MERGE.CPP
  include: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\VC\INCLUDE
  define: _DEBUG
  define: UNICODE
  define: _UNICODE
  stdver: --ms_c++latest
Checking for syntax errors: file:///c%3A/Users/Coder/Desktop/workspace/merge.cpp
queue_update_intellisense for files in tu of: C:\USERS\CODER\DESKTOP\WORKSPACE\MERGE.CPP
errorSquiggles count: 19
textDocument/codeAction
Database safe to open
```
It still seems like getting files from the VS folder, not the minGW.

![gf](https://user-images.githubusercontent.com/22341329/42131578-334f96e4-7d40-11e8-8065-1fc49241e8ff.gif)

And I just found out that autocompletion doesn't always work. It just works from time to time.

**Comment by bobbrow** [comment]
Where did you save your `c_cpp_properties.json` file?  Based on the log you've shared it looks like you've opened the whole drive `C:` as the workspace folder which means the extension would be looking for the `c_cpp_properties.json` file under `C:\.vscode\c_cpp_properties.json`.  If it's not at that location, it would explain why setting `C_Cpp.default.compilerPath` works, but updating your `c_cpp_properties.json` file does not work.

**Comment by cmh1027** [comment]
![1](https://user-images.githubusercontent.com/22341329/42191004-5f91be88-7e9b-11e8-9297-d85d7e91ee29.PNG)
![2](https://user-images.githubusercontent.com/22341329/42191005-5fbb8f74-7e9b-11e8-880f-35aae9b6dca1.PNG)
The workspace is not under `C:`, but looks like above.
Do I have to set some specific path configuration, rather than just putting `c_cpp_properties.json` file in the .vscode folder which is in the same folder with Cpp files?

**Comment by bobbrow** [comment]
You have to open the `c:\users\coder\desktop\workspace` folder in VS Code, not the `C:\` folder.

**Comment by cmh1027** [comment]
Thanks! I didn't know that I have to open the folder in VS Code to use intellisense. It was my mistake.

**Comment by bobbrow** [comment]
My comment was incorrect due to a bug I was unaware of at the time.  I thought that you had opened the root folder `C:\` on your hard drive, but in fact, you had no folder open at all and the extension was mistakenly treating that as opening the root folder.

You don't *have* to open a folder in VS Code to use IntelliSense.  But in that case you will need to use the `C_Cpp.default.*` settings to configure IntelliSense since there will be no `c_cpp_properties.json` file available.
