### ISSUE TITLE
The language server crashed 5 times in the last 3 minutes. It will not be restarted.

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#2187]
Issue Type: <b>Bug</b>

This error appears after trying to save the file:

[Error - 15:09:31] Connection to server got closed. Server will not be restarted.
[Error - 15:09:31] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/andrej/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/home/andrej/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/home/andrej/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/home/andrej/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-languageclient/lib/main.js:106:15)
	at closeHandler (/home/andrej/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/home/andrej/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/home/andrej/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/home/andrej/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/home/andrej/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/home/andrej/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at StreamMessageWriter.AbstractMessageWriter.fireClose (/home/andrej/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/messageWriter.js:57:27)
	at Socket.<anonymous> (/home/andrej/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/messageWriter.js:79:63)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at Pipe._handle.close [as _onclose] (net.js:510:12)

Extension version: 0.17.5
VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:47:35.732Z)
OS version: Linux x64 4.15.0-24-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|3.68GB (0.11GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by bobbrow** [comment]
This sounds like #2173. We plan to publish an insiders package with the fix this week.

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.17.6...unless you were hitting a different crash.

**Comment by frank3141** [comment]
Still having this issue, Oct 18, 2016

**Comment by sean-mcmanus** [comment]
@frank3141 Have you tried our insider version: https://github.com/Microsoft/vscode-cpptools/releases/tag/0.19.1-insiders2 (that has at least one crash fix)? Can you attach a debugger to Microsoft.VSCode.CPP.Extension.linux and provide a call stack? The javascript errors just tell us that our process crashed.
