### ISSUE TITLE
Frequently crash with textDocument/documentSymbol request on file save

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode-cpptools#2209]
Type: LanguageService

**Describe the bug**
- OS and Version: macOS 10.13.5
- VS Code Version: 1.24.1
- C/C++ Extension Version: 0.17.5

When I'm editing a C++ source file, when I save the file, an error frequently occurs and for 5 times the language server crashes and never restarts:

```
[Error - 12:31:10 AM] Connection to server got closed. Server will not be restarted.
[Error - 12:31:10 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-languageclient/lib/main.js:106:15)
	at closeHandler (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at StreamMessageReader.AbstractMessageReader.fireClose (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/messageReader.js:135:27)
	at Socket.<anonymous> (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/messageReader.js:188:62)
	at emitOne (events.js:101:20)
	at Socket.emit (events.js:191:7)
	at Pipe._handle.close [as _onclose] (net.js:510:12)
[Error - 12:31:10 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-languageclient/lib/main.js:106:15)
	at closeHandler (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at StreamMessageReader.AbstractMessageReader.fireClose (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/messageReader.js:135:27)
	at Socket.<anonymous> (/Users/ken/.vscode/extensions/ms-vscode.cpptools-0.17.5/node_modules/vscode-jsonrpc/lib/messageReader.js:188:62)
	at emitOne (events.js:101:20)
	at Socket.emit (events.js:191:7)
	at Pipe._handle.close [as _onclose] (net.js:510:12)
```

Now close the folder and reopen the folder, then the intellisense client simply cannot be started.

```
Failed to create IntelliSense client. Can't create intellisense client for <my source file>
```

**Comment by sean-mcmanus** [comment]
This appears to be bug https://github.com/Microsoft/vscode-cpptools/issues/2173. We might release an insiders today with the fix (our official release mechanism is having issues).

**Comment by renkun-ken** [comment]
Glad to know that!  Looking forward to the fix.

**Comment by renkun-ken** [comment]
A simple walk-around is to modify `"${workspaceFolder}/**"` to the actual include folders `c_cpp_properties.json`.

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.17.6.

**Comment by amatosov-rbx** [comment]
I am using version 0.21.0 and getting ton of errors like this
I use `"${workspaceFolder}/Project/**"` for `includePath` and `macFrameworkPath` as configuring this manually is not feasible

**Comment by bobbrow** [comment]
@amatosov-rbx can you please open a new issue with more details about your problem?  Thank you!

**Comment by amatosov-rbx** [comment]
sure
