### ISSUE TITLE
Crash in intellisense_client_mapping::remove_client_reference

### ISSUE THREAD

**Issue by ytimenkov** [microsoft/vscode-cpptools#2284]
Type: LanguageService

**Describe the bug**
- OS and Version: CensOS 7 x64
- VS Code Version:Version: 1.25.1
- C/C++ Extension Version:0.17.7-insiders

I've got a crash dump (once, I think I was closing editors):
```
Program terminated with signal 11, Segmentation fault.
#0  0x00000000005d3750 in intellisense_client_mapping::remove_client_reference(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<intellisense_client>&) ()
(gdb) bt
#0  0x00000000005d3750 in intellisense_client_mapping::remove_client_reference(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<intellisense_client>&) ()
#1  0x00000000005d39eb in intellisense_client_mapping::remove_stale_clients() ()
#2  0x00000000005d5530 in intellisense_client_mapping::erase_from_mappings(char const*) ()
#3  0x00000000005d4c5c in intellisense_client_mapping::erase_old_clients_calls(char const*) ()
#4  0x00000000005cb75c in intellisense_client_factory::try_to_fetch(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) ()
#5  0x00000000005f8a02 in vscode::message_handler::find_intellisense_client(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::function<void (std::__1::vector<std::__1::shared_ptr<intellisense_client>, std::__1::allocator<std::__1::shared_ptr<intellisense_client> > >)>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) ()
#6  0x00000000005e7b41 in vscode::message_handler::textDocument_hover(vscode::TextDocumentPositionParams) ()
#7  0x00000000005dd119 in vscode::message_handler::dispatch(vscode::vscode_client_message&&, vscode::vscode_server_message&) ()
#8  0x00000000005db761 in vscode::message_handler::handle_message(vscode::vscode_client_message&&) ()
#9  0x0000000000604c18 in void* std::__1::__thread_proxy<std::__1::tuple<vscode::message_handler::main_loop()::$_26> >(void*) ()
#10 0x00007f63282ffe25 in start_thread (arg=0x7f632510d700) at pthread_create.c:308
#11 0x00007f632802d34d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

(gdb) disassemble
Dump of assembler code for function _ZN27intellisense_client_mapping23remove_client_referenceERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERNS0_10shared_ptrI19intellisense_clientEE:
   0x00000000005d3720 <+0>:     push   %r15
   0x00000000005d3722 <+2>:     push   %r14
   0x00000000005d3724 <+4>:     push   %r12
   0x00000000005d3726 <+6>:     push   %rbx
   0x00000000005d3727 <+7>:     push   %rax
   0x00000000005d3728 <+8>:     mov    %rsi,%r15
   0x00000000005d372b <+11>:    mov    %rdi,%rax
   0x00000000005d372e <+14>:    mov    $0x1028cf0,%edi
   0x00000000005d3733 <+19>:    mov    %rax,%rsi
   0x00000000005d3736 <+22>:    callq  0x5d29a0 <_ZNSt3__16__treeINS_12__value_typeINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEENS_6vectorINS_10shared_ptrI19intellisense_clientEENS5_ISB_EEEEEENS_19__map_value_compareIS7_SE_NS_4lessIS7_EELb1EEENS5_ISE_EEE4findIS7_EENS_15__tree_iteratorISE_PNS_11__tree_nodeISE_PvEElEERKT_>
   0x00000000005d373b <+27>:    mov    %rax,%r14
   0x00000000005d373e <+30>:    mov    0x38(%r14),%rbx
   0x00000000005d3742 <+34>:    mov    0x40(%r14),%r12
   0x00000000005d3746 <+38>:    cmp    %r12,%rbx
   0x00000000005d3749 <+41>:    je     0x5d3761 <_ZN27intellisense_client_mapping23remove_client_referenceERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERNS0_10shared_ptrI19intellisense_clientEE+65>
   0x00000000005d374b <+43>:    mov    (%r15),%rax
   0x00000000005d374e <+46>:    xchg   %ax,%ax
=> 0x00000000005d3750 <+48>:    cmp    %rax,(%rbx)
   0x00000000005d3753 <+51>:    je     0x5d3761 <_ZN27intellisense_client_mapping23remove_client_referenceERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERNS0_10shared_ptrI19intellisense_clientEE+65>

(gdb) info registers
rax            0x7f63146c8848   140063521146952
rbx            0x3      3
rcx            0xffffffcf       4294967247
rdx            0xdd     221
rsi            0x7f631c091193   140063648846227
rdi            0x7f63146c59a3   140063521135011
rbp            0x7f6314209fd8   0x7f6314209fd8
rsp            0x7f632510bde0   0x7f632510bde0
r8             0x7f631403a600   140063514273280
r9             0x7f63146840e0   140063520866528
r10            0x7f63146840f0   140063520866544
r11            0x7f63280b82d0   140063850332880
r12            0x200000001      8589934593
r13            0x7f63146b9a70   140063521086064
r14            0x1028cf8        16944376
r15            0x7f62fc247530   140063113770288
rip            0x5d3750 0x5d3750 <intellisense_client_mapping::remove_client_reference(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<intellisense_client>&)+48>
eflags         0x10283  [ CF SF IF RF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0
```

**Comment by sean-mcmanus** [comment]
Yes, we're aware of this crash. It's possible it's been fixed with https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.7-insiders . If not, we'll look into possibly fixing it later, but the hit count isn't particularly high.

**Comment by sean-mcmanus** [comment]
The crash still repros with 0.17.7. The hit count is low, but it's currently the top crash for the main process.

**Comment by Colengms** [comment]
I don't see this stack anywhere in recent crash data.  Closing.
