### ISSUE TITLE
The C/Cpp Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted

### ISSUE THREAD

**Issue by ChuckyHelse** [microsoft/vscode-cpptools#2419]
Type: LanguageService
Extension: C/C++ Microsoft - IntelliSense

I receive this error message with some projects:
> The C/Cpp Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted

This is the same as in report #430 (closed for a couple of months now), but this is still happening with the latest release 1.26.1 (July 2018).

**What's new ?**
I've discovered a common point between my cases where it crashes and when it does not, and it matches with the online reports I gathered from other users on the Web: it crashes when BOOST folder and the Windows SDK are the includePath list.

In my case, it crashes each and every time I start Visual Studio Code.

**What are the version?**
Visual Studio Code 1.26.1
Windows 7 SP1 64bit
Installed Extensions:
 * C/C++ (Microsoft) 0.17.7
Many built-in extensions are disabled

**Reproduction scenario**
1.  My relevant user settings:
```
{
    "C_Cpp.workspaceParsingPriority": "high",
    "C_Cpp.loggingLevel": "6",
    "C_Cpp.intelliSenseEngine": "Default",
    "C_Cpp.intelliSenseEngineFallback": "Disabled",
    "C_Cpp.autoAddFileAssociations": true,
}
```
2. My c_cpp_properties.json contents:
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "c:/PROGRA~2/MICROS~1.0/vc/include",
                "c:/PROGRA~2/MICROS~3/Windows/v7.1A/Include",
                ... 38 applications specific included folders ...
                "c:/PROGRA~2/VIASTO~1/BOOST-~1.58_/BOOST-~1"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "WIN32",
                "AS_XML",
                "AS_MT",
                "_MSC_VER=1800",
                "_WIN32",
                "__cplusplus",
                "_M_IX86"
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "limitSymbolsToIncludedHeaders": true
            }
        }
    ],
    "version": 4
}
```

**Something to add?**

- The number of files (>65000, in the current project) does not seem to be related with the bug.
- Of course, as the C/C++ Extension keeps crashing and restarting, it disappears from the OUTPUT list which prevents me from capturing the logs. Here is what I've found for the Log (Extension Host):
```
[2018-08-17 12:08:52.245] [renderer1] [error] Language client is not ready yet: Error: Language client is not ready yet
	at LanguageClient.sendNotification (C:\Users\Michel Nolard\.vscode\extensions\ms-vscode.cpptools-0.17.7\node_modules\vscode-languageclient\lib\client.js:1498:19)
	at didChangeConfiguration (C:\Users\Michel Nolard\.vscode\extensions\ms-vscode.cpptools-0.17.7\node_modules\vscode-languageclient\lib\client.js:1286:26)
	at ConfigurationFeature.onDidChangeConfiguration (C:\Users\Michel Nolard\.vscode\extensions\ms-vscode.cpptools-0.17.7\node_modules\vscode-languageclient\lib\client.js:1291:15)
	at vscode_1.workspace.onDidChangeConfiguration (C:\Users\Michel Nolard\.vscode\extensions\ms-vscode.cpptools-0.17.7\node_modules\vscode-languageclient\lib\client.js:1254:18)
	at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:218)
	at e.$acceptConfigurationChanged (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:563:557)
	at e._doInvokeHandler (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:671:983)
	at e._invokeHandler (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:671:701)
	at e._receiveRequest (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:670:767)
	at e._receiveOneMessage (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:670:536)
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:669:452
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:672:575
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:903
	at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:218)
	at a (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:162:713)
	at Socket._socketDataListener (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:162:932)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

**Comment by sean-mcmanus** [comment]
Our highest hitting crash with 0.17.7 on Windows was fixed with 0.17.8-insiders: https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.8-insiders . Have you tried that? We plan to release 0.18.0 soon, so we'll see what remaining crashes are high hitting. If you can attach a debugger and give us the call stack of the crash we can check what crash this is you're hitting.

**Comment by sean-mcmanus** [comment]
Can you try our latest release: 0.18.0?

**Comment by michelleangela** [comment]
Closing this issue. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
