### ISSUE TITLE
Broken down after enable 

### ISSUE THREAD

**Issue by StarPrecursor** [microsoft/vscode-cpptools#3281]
We have written the needed data in
Issue Type: <b>Bug</b>

Output:

[Error - 5:52:16 PM] Connection to server got closed. Server will not be restarted.
[Error - 5:52:16 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-languageclient\lib\client.js:2150:42)
	at LanguageClient.handleConnectionClosed (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-languageclient\lib\main.js:150:15)
	at closeHandler (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-languageclient\lib\client.js:2137:18)
	at CallbackList.invoke (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at StreamMessageReader.fireClose (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.listen.readable.on (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
[Error - 5:52:16 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-languageclient\lib\client.js:2150:42)
	at LanguageClient.handleConnectionClosed (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-languageclient\lib\main.js:150:15)
	at closeHandler (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-languageclient\lib\client.js:2137:18)
	at CallbackList.invoke (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at StreamMessageReader.fireClose (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.listen.readable.on (c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)

Extension version: 0.21.0
VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.73GB (2.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>
to your clipboard because it was too large to send. Please paste.

**Comment by sean-mcmanus** [comment]
Does this reproduce with 0.22.0-insiders2, i.e. after setting the C_Cpp.updateChannel to "Insiders" or manually installing it from https://github.com/Microsoft/vscode-cpptools/releases? We fixed an issue on Windows with certain user names.

**Comment by StarPrecursor** [comment]
Hello Sean,

It works normally now after going to 0.22.0 version.

Thank you very much!

Best,
Zhe

**Comment by michelleangela** [comment]
Closing this issue as it's resolved according to the last comment.
