### ISSUE TITLE
Connection got disposed - hover failed

### ISSUE THREAD

**Issue by bonfire62** [microsoft/vscode-cpptools#4074]
VSCode Version: 1.37.0
    OS Version: centos7

Steps to Reproduce:

1.install VSCode on linux (centos7)
2.install c/c++ extension through command line
3.ctrl+click a function

Does this issue occur when all extensions are disabled?: No
Error: Connection got disposed.
at Object.dispose (/home/kbonariii/.vscode/extensions/ms-vscode.cpptools-0.24.1/dist/main.js:2554:25)
at Object.dispose (/home/kbonariii/.vscode/extensions/ms-vscode.cpptools-0.24.1/dist/main.js:3318:35)
at LanguageClient.handleConnectionClosed (/home/kbonariii/.vscode/extensions/ms-vscode.cpptools-0.24.1/dist/main.js:5400:42)
at LanguageClient.handleConnectionClosed (/home/kbonariii/.vscode/extensions/ms-vscode.cpptools-0.24.1/dist/main.js:11816:15)
at closeHandler (/home/kbonariii/.vscode/extensions/ms-vscode.cpptools-0.24.1/dist/main.js:5387:18)
at CallbackList.invoke (/home/kbonariii/.vscode/extensions/ms-vscode.cpptools-0.24.1/dist/main.js:7527:39)
at Emitter.fire (/home/kbonariii/.vscode/extensions/ms-vscode.cpptools-0.24.1/dist/main.js:7585:36)
at closeHandler (/home/kbonariii/.vscode/extensions/ms-vscode.cpptools-0.24.1/dist/main.js:1904:26)
at CallbackList.invoke (/home/kbonariii/.vscode/extensions/ms-vscode.cpptools-0.24.1/dist/main.js:7527:39)
at Emitter.fire (/home/kbonariii/.vscode/extensions/ms-vscode.cpptools-0.24.1/dist/main.js:7585:36)
at StreamMessageReader.fireClose (/home/kbonariii/.vscode/extensions/ms-vscode.cpptools-0.24.1/dist/main.js:9867:27)
at Socket.module.exports.listen.readable.on (/home/kbonariii/.vscode/extensions/ms-vscode.cpptools-0.24.1/dist/main.js:9907:46)
at Socket.emit (events.js:187:15)
at Pipe.Socket._destroy._handle.close (net.js:606:12)

**Comment by sean-mcmanus** [comment]
It sounds like Microsoft.VSCode.CPP.Extension.linux is crashing. Are you able to attach a debugger to get a call stack or provide any more repro info? Is your architecture x64?

**Comment by bonfire62** [comment]
I had uninstalled the extension because of the error. Upon re-installation (this is the 3-4th time) it appears to be working! I have no idea why this time is different.
edit: nvm just happened again

**Comment by bonfire62** [comment]
architecture is x64

**Comment by Colengms** [comment]
Hi @bonfire64 .  Are there any additional clues, such as a particular operation that might be associated with the crash, or if this only happens when a particular file is open? Also, could you try attaching a debugger to Microsoft.VSCode.CPP.Extension.linux to capture stacks when the crash occurs?

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
