### ISSUE TITLE
Language server crashing

### ISSUE THREAD

**Issue by thpica** [microsoft/vscode-cpptools#4478]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 16.04
- VS Code Version: 1.39.2
- C/C++ Extension Version: 0.26.0
- Other extensions you installed (and if the issue persists after disabling them):
  - `vector-of-bool.cmake-tools-1.1.3`

Cannot get Intellisense to work, the log shows `Failed to read response from server: 22`.
I managed to attach to `Microsoft.VSCode.CPP.IntelliSense.Msvc.linux` before it died and got the following backtrace:

```
#0  memchr () at ../sysdeps/x86_64/memchr.S:154
#1  0x0000000000828ed4 in macro_invocation ()
#2  0x00000000007e963b in get_token ()
#3  0x000000000086ae43 in pp_directive ()
#4  0x00000000007e8c5d in get_token ()
#5  0x00000000006c13e4 in scan_nonmember_declaration ()
#6  0x00000000006c19c8 in translation_unit ()
#7  0x00000000008e33d5 in process_translation_unit ()
#8  0x0000000000625e87 in cfe_main ()
#9  0x0000000000902ee6 in cfe_main_exception_handler ()
#10 0x0000000000625f96 in edg_main ()
#11 0x00000000008fe34a in edge_compiler_main(int, char const**) ()
#12 0x00000000005afddd in preparse(int, char const**, a_scout_store*, edge::translation_unit*) ()
#13 0x000000000057c596 in a_compiler_thread::compiler_thread_routine(a_compiler_thread*) ()
#14 0x000000000097e09f in execute_native_thread_routine ()
#15 0x00007fe84b8aa6ba in start_thread (arg=0x7fe7bb7fe700) at pthread_create.c:333
#16 0x00007fe84b5e041d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
```
$ sudo gdb --pid=`pidof Microsoft.VSCode.CPP.IntelliSense.Msvc.linux`
GNU gdb (Ubuntu 8.2-0ubuntu1~16.04.1) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 20205
[New LWP 20207]
[New LWP 20208]
[New LWP 20209]
[New LWP 20210]
[New LWP 20211]
[New LWP 20212]
[New LWP 20213]
[New LWP 20214]
[New LWP 20215]
[New LWP 20216]
[New LWP 20217]
[New LWP 20218]
[New LWP 20219]
[New LWP 20220]
[New LWP 20221]
[New LWP 20222]
[New LWP 20223]
[New LWP 20224]
[New LWP 20225]
[New LWP 20226]
[New LWP 20227]
[New LWP 20228]
[New LWP 20229]
[New LWP 20230]
[New LWP 20231]
[New LWP 20232]
[New LWP 20233]
[New LWP 20234]
[New LWP 20235]
[New LWP 20236]
[New LWP 20237]
[New LWP 20238]
[New LWP 20239]
[New LWP 20240]
[New LWP 20242]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185     ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S: No such file or directory.
(gdb) c
Continuing.

Thread 36 "Microsoft.VSCod" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f4bd8ff9700 (LWP 20242)]
memchr () at ../sysdeps/x86_64/memchr.S:154
154     ../sysdeps/x86_64/memchr.S: No such file or directory.
(gdb) bt
#0  memchr () at ../sysdeps/x86_64/memchr.S:154
#1  0x0000000000828ed4 in macro_invocation ()
#2  0x00000000007e963b in get_token ()
#3  0x000000000086ae43 in pp_directive ()
#4  0x00000000007e8c5d in get_token ()
#5  0x00000000006c13e4 in scan_nonmember_declaration ()
#6  0x00000000006c19c8 in translation_unit ()
#7  0x00000000008e33d5 in process_translation_unit ()
#8  0x0000000000625e87 in cfe_main ()
#9  0x0000000000902ee6 in cfe_main_exception_handler ()
#10 0x0000000000625f96 in edg_main ()
#11 0x00000000008fe34a in edge_compiler_main(int, char const**) ()
#12 0x00000000005afddd in preparse(int, char const**, a_scout_store*, edge::translation_unit*) ()
#13 0x000000000057c596 in a_compiler_thread::compiler_thread_routine(a_compiler_thread*) ()
#14 0x000000000097e09f in execute_native_thread_routine ()
#15 0x00007f4c4464c6ba in start_thread (arg=0x7f4bd8ff9700) at pthread_create.c:333
#16 0x00007f4c4438241d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) 
```

**Comment by sean-mcmanus** [comment]
We are aware of that IntelliSense process crash, but it's not a high hitter and we don't know of a repro. Are you able to isolate the code that is causing the crash, via a binary search of removing code until it doesn't crash? That would help us get it fixed. Can you tell if it's caused by code in a gcc system header? It's trying to parse a macro and it's hitting some unexpected condition.

**Comment by sean-mcmanus** [comment]
Actually, the crash is a top hitter for Visual Studio itself on Windows, so maybe they'll be able to fix it (not sure yet).

**Comment by thpica** [comment]
Thanks @sean-mcmanus for the quick response.
I tried to narrow it down but I end up in a dead end.
I cannot disclose the source I am working on, but all the macros I use in the section crashing Intellisense come from the following library: https://github.com/msgpack/msgpack-c.
Most notably it vendors https://github.com/boostorg/preprocessor.

**Comment by sean-mcmanus** [comment]
Our code uses msgpack-c, but I wasn't able to repro any crash with 2.1.1 or 3.2 on Windows or Linux and we use a bunch of MSGPACK macros. It's possible msgpack needs to be configured with certain defines or certain include files need to be used or the msgpack macros need to be used in specific way.

**Comment by thpica** [comment]
This has not been an issue in the new versions. Closing.
