### ISSUE TITLE
crash when format C code.

### ISSUE THREAD

**Issue by wgqimut** [microsoft/vscode-cpptools#4668]
**Type: LanguageService**

**Describe the bug**
- OS and Version: local machine: MacOS 10.15.1 (19B88), remote server manjaro 18.1.3
- VS Code Version: 1.40.2
- C/C++ Extension Version: remote server 0.26.1

When I format document, the crash is occured.
stack trace is:
```
[Error - 1:28:06 PM] Connection to server got closed. Server will not be restarted.
[Error - 1:28:06 PM] Request textDocument/formatting failed.
Error: Connection got disposed.
	at Object.dispose ($HOME/.vscode-server/extensions/ms-vscode.cpptools-0.26.1/dist/main.js:2946:25)
	at Object.dispose ($HOME/.vscode-server/extensions/ms-vscode.cpptools-0.26.1/dist/main.js:3416:35)
	at LanguageClient.handleConnectionClosed ($HOME/.vscode-server/extensions/ms-vscode.cpptools-0.26.1/dist/main.js:5498:42)
	at LanguageClient.handleConnectionClosed ($HOME/.vscode-server/extensions/ms-vscode.cpptools-0.26.1/dist/main.js:15228:15)
	at closeHandler ($HOME/.vscode-server/extensions/ms-vscode.cpptools-0.26.1/dist/main.js:5485:18)
	at CallbackList.invoke ($HOME/.vscode-server/extensions/ms-vscode.cpptools-0.26.1/dist/main.js:10262:39)
	at Emitter.fire ($HOME/.vscode-server/extensions/ms-vscode.cpptools-0.26.1/dist/main.js:10320:36)
	at closeHandler ($HOME/.vscode-server/extensions/ms-vscode.cpptools-0.26.1/dist/main.js:2296:26)
	at CallbackList.invoke ($HOME/.vscode-server/extensions/ms-vscode.cpptools-0.26.1/dist/main.js:10262:39)
	at Emitter.fire ($HOME/.vscode-server/extensions/ms-vscode.cpptools-0.26.1/dist/main.js:10320:36)
	at StreamMessageReader.fireClose ($HOME/.vscode-server/extensions/ms-vscode.cpptools-0.26.1/dist/main.js:13095:27)
	at Socket.<anonymous> ($HOME/.vscode-server/extensions/ms-vscode.cpptools-0.26.1/dist/main.js:13135:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)

```

**Comment by sean-mcmanus** [comment]
We haven't seen other reports like this -- do you know what could be special about your setup other than being remote? Does it repro for all files or with certain clang_format formatting settings? Could you attach a debugger to the Microsoft.VSCode.CPP.Extension.linux process before doing the formatting to provide a call stack of the crash?

I assume it crashes with .cpp files too, right?

Are you able to run the binary $HOME/.vscode-server/extensions/ms-vscode.cpptools-0.26.1/LLVM/bin/clang-format ? Or can you change the clang_format_path to the location of a runnable clang-format binary?

**Comment by wgqimut** [comment]
when I run `$HOME/.vscode-server/extensions/ms-vscode.cpptools-0.26.1/LLVM/bin/clang-format -h`, I received error message` error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory` , cause manjaro default libtinfo version is libinfo.so.6, I install the libtinfo.so.5, problem solved!
