### ISSUE TITLE
Segmentation fault in scan_expr_full

### ISSUE THREAD

**Issue by Cre3per** [microsoft/vscode-cpptools#4905]
**Type: LanguageService**

**Describe the bug**
- OS and Version: 5.4.15-arch1-1
- VS Code Version: 1.41.1, 26076a4de974ead31f97692a0d32f90d735645c0, x64
- C/C++ Extension Version: 0.26.3
- Other extensions you installed (and if the issue persists after disabling them): CMake, Code Spell Checker, TODO Highlight. Issue persists with these extensions disabled.
- The crash occurs sporadically. The most recent one when switching files. Before that, when waiting for autocomplete suggestions. It also causes the entire system to freeze, requiring a reboot. Although this only happens with vscode, I suppose the freeze is caused by my system.

**To Reproduce**

I haven't found a reliable way of reproducing the crash.

**Expected behavior**

**Screenshots**

**Additional context**

Backtraces and registers of the last 3 crashes, starting with the most recent
(The cut-off path is "snip/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux")
```
Core was generated by `snip/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.C'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000717fb8 in scan_expr_full(an_operand*, an_operand*, int, int) ()
[Current thread is 1 (Thread 0x7fc44ffff700 (LWP 7712))]
(gdb) bt
#0  0x0000000000717fb8 in scan_expr_full(an_operand*, an_operand*, int, int) ()
#1  0x000000000070de3e in scan_expr_list(a_token_kind, int, int, int, int, int) ()
#2  0x000000000070e99b in scan_call_arguments(a_type*, a_routine*, int, an_expr_node**, int, int, int, int, a_rescan_control_block*, int, an_init_component*, an_init_component**, an_operand*, int*, a_source_position*) ()
#3  0x000000000073e480 in scan_function_call(an_operand*, an_operand*, a_rescan_control_block*, an_operand*) ()
#4  0x0000000000715ca2 in scan_expr_full(an_operand*, an_operand*, int, int) ()
#5  0x00000000007218a4 in scan_void_expression(int, int, int, a_dynamic_init**, an_init_component*) ()
#6  0x00000000008aa4ac in expression_statement(int) ()
#7  0x00000000008a47cb in statement(int, int) ()
#8  0x00000000008a3949 in compound_statement_full(int, int, int, int, int, a_type**) ()
#9  0x000000000078fa00 in scan_function_body(a_routine*, a_func_info_block*, unsigned long, a_macro_arg_fixup**, a_macro_arg_fixup**) ()
#10 0x00000000005c9ad8 in compile_fragment((anonymous namespace)::a_fragment_buffer const&, a_canonicalized_file_name, msvc::offset_t, msvc::offset_t, msvc::offset_t, bool, a_declaration_context const&, a_region_scope_info const&, std::vector<std::string, std::allocator<std::string> > const&, bool, bool, bool, bool*) ()
#11 0x00000000005c77cb in before_tu_wrapup() ()
#12 0x000000000090c91a in process_translation_unit(char const*, int, an_exported_template_file*) ()
#13 0x000000000063cec7 in cfe_main(int, char**) ()
#14 0x000000000092c4c6 in cfe_main_exception_handler(int, char**) ()
#15 0x000000000063cfd6 in edg_main(int, char**) ()
#16 0x000000000092795a in edge_compiler_main(int, char const**) ()
#17 0x00000000005c7d9b in preparse(int, char const**, a_scout_store*, edge::translation_unit*) ()
#18 0x0000000000594256 in a_compiler_thread::compiler_thread_routine(a_compiler_thread*) ()
#19 0x00000000009ab31f in execute_native_thread_routine ()
#20 0x00007fc46a15b4cf in start_thread () from /usr/lib/libpthread.so.0
#21 0x00007fc46a08a2d3 in clone () from /usr/lib/libc.so.6
```
```
rax            0x0                 0
rbx            0x7f6f5bdea5a0      140116259415456
rcx            0x7f6f3813c580      140115658917248
rdx            0x0                 0
rsi            0x7fc43d0b8a00      140480814483968
rdi            0x4d9               1241
rbp            0x0                 0x0
rsp            0x7fc44fffcb00      0x7fc44fffcb00
r8             0x0                 0
r9             0x0                 0
r10            0x0                 0
r11            0x0                 0
r12            0x0                 0
r13            0x0                 0
r14            0x7fc44fffe368      140481132487528
r15            0x1                 1
rip            0x717fb8            0x717fb8 <scan_expr_full(an_operand*, an_operand*, int, int)+16920>
eflags         0x10202             [ IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
```

```
Core was generated by `snip/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.C'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000717fb8 in scan_expr_full(an_operand*, an_operand*, int, int) ()
[Current thread is 1 (Thread 0x7f331d7fa700 (LWP 20319))]
(gdb) bt
#0  0x0000000000717fb8 in scan_expr_full(an_operand*, an_operand*, int, int) ()
#1  0x000000000070de3e in scan_expr_list(a_token_kind, int, int, int, int, int) ()
#2  0x000000000070e99b in scan_call_arguments(a_type*, a_routine*, int, an_expr_node**, int, int, int, int, a_rescan_control_block*, int, an_init_component*, an_init_component**, an_operand*, int*, a_source_position*) ()
#3  0x000000000073e480 in scan_function_call(an_operand*, an_operand*, a_rescan_control_block*, an_operand*) ()
#4  0x0000000000715ca2 in scan_expr_full(an_operand*, an_operand*, int, int) ()
#5  0x00000000007218a4 in scan_void_expression(int, int, int, a_dynamic_init**, an_init_component*) ()
#6  0x00000000008aa4ac in expression_statement(int) ()
#7  0x00000000008a47cb in statement(int, int) ()
#8  0x00000000008a3949 in compound_statement_full(int, int, int, int, int, a_type**) ()
#9  0x000000000078fa00 in scan_function_body(a_routine*, a_func_info_block*, unsigned long, a_macro_arg_fixup**, a_macro_arg_fixup**) ()
#10 0x0000000000792888 in function_definition(a_symbol_locator*, a_decl_parse_state*, a_func_info_block*, a_decl_pos_block*) ()
#11 0x00000000006d9108 in scan_nonmember_declaration(a_decl_parse_state*, a_source_range*) ()
#12 0x00000000006dd6bb in namespace_declaration(a_token_kind*, int, int, a_source_position*, a_symbol**) ()
#13 0x00000000006dd600 in namespace_declaration(a_token_kind*, int, int, a_source_position*, a_symbol**) ()
#14 0x00000000006d57f7 in scan_nonmember_declaration(a_decl_parse_state*, a_source_range*) ()
#15 0x00000000006db3bc in declaration(int, int, int, int, a_param_id*, a_source_range*) ()
#16 0x00000000005c9da3 in compile_fragment((anonymous namespace)::a_fragment_buffer const&, a_canonicalized_file_name, msvc::offset_t, msvc::offset_t, msvc::offset_t, bool, a_declaration_context const&, a_region_scope_info const&, std::vector<std::string, std::allocator<std::string> > const&, bool, bool, bool, bool*) ()
#17 0x00000000005c77cb in before_tu_wrapup() ()
#18 0x000000000090c91a in process_translation_unit(char const*, int, an_exported_template_file*) ()
#19 0x000000000063cec7 in cfe_main(int, char**) ()
#20 0x000000000092c4c6 in cfe_main_exception_handler(int, char**) ()
#21 0x000000000063cfd6 in edg_main(int, char**) ()
#22 0x000000000092795a in edge_compiler_main(int, char const**) ()
#23 0x00000000005c7d9b in preparse(int, char const**, a_scout_store*, edge::translation_unit*) ()
#24 0x0000000000594256 in a_compiler_thread::compiler_thread_routine(a_compiler_thread*) ()
#25 0x00000000009ab31f in execute_native_thread_routine ()
#26 0x00007f3326a564cf in start_thread () from /usr/lib/libpthread.so.0
#27 0x00007f33269852d3 in clone () from /usr/lib/libc.so.6
```
```
rax            0x0                 0
rbx            0x7fd4beb205b8      140551709132216
rcx            0x7fd4a82d7170      140551331344752
rdx            0x0                 0
rsi            0x7f32f15ecb70      139856774613872
rdi            0x415               1045
rbp            0x0                 0x0
rsp            0x7f331d7f6960      0x7f331d7f6960
r8             0x0                 0
r9             0x0                 0
r10            0x0                 0
r11            0x0                 0
r12            0x0                 0
r13            0x0                 0
r14            0x7f331d7f81c8      139857514955208
r15            0x1                 1
rip            0x717fb8            0x717fb8 <scan_expr_full(an_operand*, an_operand*, int, int)+16920>
eflags         0x10202             [ IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
```

```
Core was generated by `snip/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.C'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000717fb8 in scan_expr_full(an_operand*, an_operand*, int, int) ()
[Current thread is 1 (Thread 0x7f0a977fe700 (LWP 29818))]
(gdb) bt
#0  0x0000000000717fb8 in scan_expr_full(an_operand*, an_operand*, int, int) ()
#1  0x000000000070de3e in scan_expr_list(a_token_kind, int, int, int, int, int) ()
#2  0x000000000070e99b in scan_call_arguments(a_type*, a_routine*, int, an_expr_node**, int, int, int, int, a_rescan_control_block*, int, an_init_component*, an_init_component**, an_operand*, int*, a_source_position*) ()
#3  0x000000000073e480 in scan_function_call(an_operand*, an_operand*, a_rescan_control_block*, an_operand*) ()
#4  0x0000000000715ca2 in scan_expr_full(an_operand*, an_operand*, int, int) ()
#5  0x00000000007218a4 in scan_void_expression(int, int, int, a_dynamic_init**, an_init_component*) ()
#6  0x00000000008aa4ac in expression_statement(int) ()
#7  0x00000000008a47cb in statement(int, int) ()
#8  0x00000000008a3949 in compound_statement_full(int, int, int, int, int, a_type**) ()
#9  0x000000000078fa00 in scan_function_body(a_routine*, a_func_info_block*, unsigned long, a_macro_arg_fixup**, a_macro_arg_fixup**) ()
#10 0x00000000005c9ad8 in compile_fragment((anonymous namespace)::a_fragment_buffer const&, a_canonicalized_file_name, msvc::offset_t, msvc::offset_t, msvc::offset_t, bool, a_declaration_context const&, a_region_scope_info const&, std::vector<std::string, std::allocator<std::string> > const&, bool, bool, bool, bool*) ()
#11 0x00000000005c77cb in before_tu_wrapup() ()
#12 0x000000000090c91a in process_translation_unit(char const*, int, an_exported_template_file*) ()
#13 0x000000000063cec7 in cfe_main(int, char**) ()
#14 0x000000000092c4c6 in cfe_main_exception_handler(int, char**) ()
#15 0x000000000063cfd6 in edg_main(int, char**) ()
#16 0x000000000092795a in edge_compiler_main(int, char const**) ()
#17 0x00000000005c7d9b in preparse(int, char const**, a_scout_store*, edge::translation_unit*) ()
#18 0x0000000000594256 in a_compiler_thread::compiler_thread_routine(a_compiler_thread*) ()
#19 0x00000000009ab31f in execute_native_thread_routine ()
#20 0x00007f0ab8ea24cf in start_thread () from /usr/lib/libpthread.so.0
#21 0x00007f0ab8dd12d3 in clone () from /usr/lib/libc.so.6
```
```
rax            0x0                 0
rbx            0x7f6f5cb78c40      140116273630272
rcx            0x7f6f3813c580      140115658917248
rdx            0x0                 0
rsi            0x7f0a89685be0      139683231718368
rdi            0x4e8               1256
rbp            0x0                 0x0
rsp            0x7f0a977fbb00      0x7f0a977fbb00
r8             0x0                 0
r9             0x0                 0
r10            0x0                 0
r11            0x1                 1
r12            0x0                 0
r13            0x0                 0
r14            0x7f0a977fd368      139683468137320
r15            0x1                 1
rip            0x717fb8            0x717fb8 <scan_expr_full(an_operand*, an_operand*, int, int)+16920>
eflags         0x10202             [ IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
```

**Comment by sean-mcmanus** [comment]
Yes, we are aware of this crash (and related ones that possibly share the same root cause). It's caused by our parser code inherited from VS. Unfortunately, we need to find a repro in order to get a fix. Switching files can trigger a "reparse" of the previous file and making edits can also trigger a reparse.

Freezing of your system is unusual though, since normally a crash is expected to just terminate the process. My guess is that your OS may be (mis)configured to be doing something special that is resource intensive on a crash, perhaps writing a large core dump of the crashing process to disk. Perhaps monitoring your CPU, memory, and disk usage history might help diagnose the cause.
