### ISSUE TITLE
VSCode says : "Debug adapter process has terminated unexpectedly (read ECONNRESET)"

### ISSUE THREAD

**Issue by david4embedded** [microsoft/vscode-cpptools#5075]
Type: Debugger

**Describe the bug**
- OS and Version: Raspbian Buster
- VS Code Version: 1.28.2
- C/C++ Extension Version: 0.21.0
- When I try to start debugging, breakpoints are not reached with this message : 
**"Debug adapter process has terminated unexpectedly (read ECONNRESET)"**
<details>
<summary>
Launch.json 
</summary>

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Debug (gdb)",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/bin/bin",
            "preLaunchTask": "Build C++ project",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "/usr/bin/gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```
</details>

**Comment by WardenGnaw** [comment]
Could you [enable logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_logging-for-mi-debuggers) and share the output?

**Comment by david4embedded** [comment]
Hi,

I added logging settings as :+1:  ,
            "logging": {
                "trace":true,
                "traceResponse": true,
                "engineLogging": true
            }

and I can see the output being shown this way:

1. Extensions
/home/pi/.vscode/extensions/ms-vscode.cpptools-0.21.0/debugAdapters/OpenDebugAD7: line 32: mono: command not found/home/pi/.vscode/extensions/ms-vscode.cpptools-0.21.0/debugAdapters/OpenDebugAD7: line 32: mono: command not found/home/pi/.vscode/extensions/ms-vscode.cpptools-0.21.0/debugAdapters/OpenDebugAD7: line 32: mono: command not found/home/pi/.vscode/extensions/ms-vscode.cpptools-0.21.0/debugAdapters/OpenDebugAD7: line 32: mono: command not found/home/pi/.vscode/extensions/ms-vscode.cpptools-0.21.0/debugAdapters/OpenDebugAD7: line 32: mono: command not found/home/pi/.vscode/extensions/ms-vscode.cpptools-0.21.0/debugAdapters/OpenDebugAD7: line 32: mono: command not found/home/pi/.vscode/extensions/ms-vscode.cpptools-0.21.0/debugAdapters/OpenDebugAD7: line 32: mono: command not found/home/pi/.vscode/extensions/ms-vscode.cpptools-0.21.0/debugAdapters/OpenDebugAD7: line 32: mono: command not found

2. Log[main]
[2020-03-06 17:46:09.269] [main] [info] update#ctor - updates are disabled

3. Log[shared]
[2020-03-06 17:46:15.026] [sharedprocess] [info] main {"machineId":"2d050ae30f8ed83e546476ea3ca53fb4d8219916cd6584d45aab947458ca1fca"}
[2020-03-06 17:46:15.185] [sharedprocess] [info] Scanned user extensions: 0
[2020-03-06 17:46:15.363] [sharedprocess] [info] Scanned system extensions: 71
[2020-03-06 17:46:18.657] [sharedprocess] [info] Scanned user extensions: 0
[2020-03-06 17:46:18.676] [sharedprocess] [info] Scanned user extensions: 0
[2020-03-06 17:46:18.903] [sharedprocess] [info] Scanned system extensions: 71
[2020-03-06 17:46:19.813] [sharedprocess] [info] Scanned user extensions: 0
[2020-03-06 17:46:20.050] [sharedprocess] [info] Scanned system extensions: 71
[2020-03-06 17:46:22.270] [sharedprocess] [info] Scanned user extensions: 0
[2020-03-06 17:46:45.695] [sharedprocess] [info] Scanned user extensions: 0
[2020-03-06 17:46:45.834] [sharedprocess] [info] Scanned user extensions: 0
[2020-03-06 17:46:45.857] [sharedprocess] [info] Scanned user extensions: 0
[2020-03-06 17:46:45.886] [sharedprocess] [info] Scanned user extensions: 0
[2020-03-06 17:46:46.287] [sharedprocess] [info] Scanned system extensions: 71
[2020-03-06 17:46:46.300] [sharedprocess] [info] Scanned system extensions: 71
[2020-03-06 17:46:46.308] [sharedprocess] [info] Scanned system extensions: 71
[2020-03-06 17:46:50.501] [sharedprocess] [info] Installing extension: cpptools
[2020-03-06 17:46:50.511] [sharedprocess] [info] Scanned user extensions: 0
[2020-03-06 17:46:51.065] [sharedprocess] [info] Downloaded extension: cpptools /tmp/10e606c3-52f3-4950-8efb-e4a9d39c08a1
[2020-03-06 17:46:55.081] [sharedprocess] [info] Starting to clean up unused language packs.
[2020-03-06 17:46:56.816] [sharedprocess] [info] Extracted extension to /home/pi/.vscode/extensions/.ms-vscode.cpptools-0.21.0: ms-vscode.cpptools-0.21.0
[2020-03-06 17:46:56.818] [sharedprocess] [info] Renamed to /home/pi/.vscode/extensions/ms-vscode.cpptools-0.21.0
[2020-03-06 17:46:56.818] [sharedprocess] [info] Installation completed. ms-vscode.cpptools-0.21.0
[2020-03-06 17:46:56.919] [sharedprocess] [info] Extensions installed successfully: ms-vscode.cpptools
[2020-03-06 17:46:57.080] [sharedprocess] [info] Scanned user extensions: 1
[2020-03-06 17:46:57.154] [sharedprocess] [info] Scanned system extensions: 71
[2020-03-06 17:47:06.342] [sharedprocess] [info] Installing extension: vscode-clang
[2020-03-06 17:47:06.351] [sharedprocess] [info] Scanned user extensions: 1
[2020-03-06 17:47:06.462] [sharedprocess] [info] Downloaded extension: vscode-clang /tmp/a2cb5374-56ba-4dfb-96d4-69ff9079bcbd
[2020-03-06 17:47:06.637] [sharedprocess] [info] Extracted extension to /home/pi/.vscode/extensions/.mitaki28.vscode-clang-0.2.3: mitaki28.vscode-clang-0.2.3
[2020-03-06 17:47:06.638] [sharedprocess] [info] Renamed to /home/pi/.vscode/extensions/mitaki28.vscode-clang-0.2.3
[2020-03-06 17:47:06.639] [sharedprocess] [info] Installation completed. mitaki28.vscode-clang-0.2.3
[2020-03-06 17:47:06.692] [sharedprocess] [info] Extensions installed successfully: mitaki28.vscode-clang
[2020-03-06 17:47:06.879] [sharedprocess] [info] Scanned user extensions: 2
[2020-03-06 17:47:07.022] [sharedprocess] [info] Scanned system extensions: 71
[2020-03-06 17:47:14.808] [sharedprocess] [info] Installing extension: code-gnu-global
[2020-03-06 17:47:14.822] [sharedprocess] [info] Scanned user extensions: 2
[2020-03-06 17:47:14.924] [sharedprocess] [info] Downloaded extension: code-gnu-global /tmp/5f27d701-3415-4a14-b0a0-45827eeb74f9
[2020-03-06 17:47:15.485] [sharedprocess] [info] Extracted extension to /home/pi/.vscode/extensions/.austin.code-gnu-global-0.2.2: austin.code-gnu-global-0.2.2
[2020-03-06 17:47:15.487] [sharedprocess] [info] Renamed to /home/pi/.vscode/extensions/austin.code-gnu-global-0.2.2
[2020-03-06 17:47:15.487] [sharedprocess] [info] Installation completed. austin.code-gnu-global-0.2.2
[2020-03-06 17:47:17.219] [sharedprocess] [info] Extensions installed successfully: austin.code-gnu-global
[2020-03-06 17:47:17.393] [sharedprocess] [info] Scanned user extensions: 3
[2020-03-06 17:47:17.452] [sharedprocess] [info] Scanned system extensions: 71
[2020-03-06 17:47:27.853] [sharedprocess] [info] Scanned user extensions: 3
[2020-03-06 17:47:27.870] [sharedprocess] [info] Scanned user extensions: 3
[2020-03-06 17:47:27.881] [sharedprocess] [info] Scanned user extensions: 3
[2020-03-06 17:47:27.970] [sharedprocess] [info] Scanned user extensions: 3
[2020-03-06 17:47:27.982] [sharedprocess] [info] Scanned user extensions: 3
[2020-03-06 17:47:28.040] [sharedprocess] [info] Scanned user extensions: 3
[2020-03-06 17:47:28.378] [sharedprocess] [info] Scanned system extensions: 71
[2020-03-06 17:47:28.387] [sharedprocess] [info] Scanned system extensions: 71
[2020-03-06 17:47:28.397] [sharedprocess] [info] Scanned system extensions: 71
[2020-03-06 17:47:28.408] [sharedprocess] [info] Scanned system extensions: 71
[2020-03-06 17:47:29.032] [sharedprocess] [info] Scanned user extensions: 3
[2020-03-06 17:47:29.118] [sharedprocess] [info] Scanned system extensions: 71
[2020-03-06 17:47:31.306] [sharedprocess] [info] Scanned user extensions: 3
[2020-03-06 17:48:06.023] [sharedprocess] [info] Installing extension: easy-cpp-projects
[2020-03-06 17:48:06.046] [sharedprocess] [info] Scanned user extensions: 3
[2020-03-06 17:48:06.178] [sharedprocess] [info] Downloaded extension: easy-cpp-projects /tmp/a57c4ca6-6343-48d9-8472-a18e4a1f7093
[2020-03-06 17:48:06.547] [sharedprocess] [info] Extracted extension to /home/pi/.vscode/extensions/.acharluk.easy-cpp-projects-1.7.7: acharluk.easy-cpp-projects-1.7.7
[2020-03-06 17:48:06.548] [sharedprocess] [info] Renamed to /home/pi/.vscode/extensions/acharluk.easy-cpp-projects-1.7.7
[2020-03-06 17:48:06.549] [sharedprocess] [info] Installation completed. acharluk.easy-cpp-projects-1.7.7
[2020-03-06 17:48:06.637] [sharedprocess] [info] Extensions installed successfully: acharluk.easy-cpp-projects
[2020-03-06 17:48:06.816] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 17:48:06.971] [sharedprocess] [info] Scanned system extensions: 71
[2020-03-06 17:48:20.573] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 17:48:20.590] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 17:48:20.602] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 17:48:20.680] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 17:48:20.692] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 17:48:20.745] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 17:48:21.070] [sharedprocess] [info] Scanned system extensions: 71
[2020-03-06 17:48:21.079] [sharedprocess] [info] Scanned system extensions: 71
[2020-03-06 17:48:21.091] [sharedprocess] [info] Scanned system extensions: 71
[2020-03-06 17:48:21.105] [sharedprocess] [info] Scanned system extensions: 71
[2020-03-06 17:48:21.372] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 17:48:21.589] [sharedprocess] [info] Scanned system extensions: 71
[2020-03-06 17:48:22.777] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 17:53:22.976] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 17:58:23.019] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 18:03:23.062] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 18:08:23.117] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 18:13:23.172] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 18:18:23.221] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 18:23:23.273] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 18:28:23.434] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 18:33:23.481] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 18:38:23.552] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 18:43:23.590] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 18:48:23.633] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 18:53:23.681] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 18:58:23.731] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 19:03:23.787] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 19:08:23.844] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 19:13:23.887] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 19:18:23.940] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 19:23:23.991] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 19:28:24.165] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 19:33:24.213] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 19:38:24.261] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 19:43:24.314] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 19:48:24.362] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 19:53:24.413] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 19:58:24.466] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 20:03:24.528] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 20:08:24.583] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 20:13:24.621] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 20:18:24.663] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 20:23:24.722] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 20:28:24.900] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 20:33:24.951] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 20:38:24.992] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 20:43:25.044] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 20:48:25.113] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 20:53:25.163] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 20:58:25.217] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 21:03:25.266] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 21:08:25.320] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 21:13:25.368] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 21:18:25.416] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 21:23:25.467] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 21:28:25.635] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 21:33:25.681] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 21:38:25.734] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 21:43:25.787] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 21:48:25.835] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 21:53:25.889] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 21:58:25.935] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 22:03:25.985] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 22:08:26.042] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 22:13:26.091] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 22:18:26.142] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 22:23:26.190] [sharedprocess] [info] Scanned user extensions: 4
[2020-03-06 22:28:26.377] [sharedprocess] [info] Scanned user extensions: 4

3. Log[Window]
[2020-03-06 17:46:18.444] [renderer1] [error] submitURL is a required option to crashReporter.start: Error: submitURL is a required option to crashReporter.start
    at CrashReporter.start (/usr/share/code/resources/electron.asar/common/api/crash-reporter.js:43:13)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2886:81
    at Object.g [as _notify] (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:160:729)
    at Object.enter (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:164:568)
    at n.Class.derive._oncancel._run (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:165:902)
    at n.Class.derive._oncancel._error (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:165:419)
    at ReadFileContext.<anonymous> (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:205:1001)
    at ReadFileContext.callback (/usr/share/code/resources/app/node_modules.asar/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (original-fs.js:420:13)
[2020-03-06 17:46:19.734] [renderer1] [info] no standard startup: panel is active
[2020-03-06 17:47:27.798] [renderer1] [error] submitURL is a required option to crashReporter.start: Error: submitURL is a required option to crashReporter.start
    at CrashReporter.start (/usr/share/code/resources/electron.asar/common/api/crash-reporter.js:43:13)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2886:81
    at Object.g [as _notify] (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:160:729)
    at Object.enter (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:164:568)
    at n.Class.derive._oncancel._run (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:165:902)
    at n.Class.derive._oncancel._error (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:165:419)
    at ReadFileContext.<anonymous> (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:205:1001)
    at ReadFileContext.callback (/usr/share/code/resources/app/node_modules.asar/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (original-fs.js:420:13)
[2020-03-06 17:47:28.360] [renderer1] [info] no standard startup: not a new window
[2020-03-06 17:47:41.199] [renderer1] [error] Unsupported client
[2020-03-06 17:47:51.012] [renderer1] [error] Unsupported client
[2020-03-06 17:48:20.504] [renderer1] [error] submitURL is a required option to crashReporter.start: Error: submitURL is a required option to crashReporter.start
    at CrashReporter.start (/usr/share/code/resources/electron.asar/common/api/crash-reporter.js:43:13)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2886:81
    at Object.g [as _notify] (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:160:729)
    at Object.enter (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:164:568)
    at n.Class.derive._oncancel._run (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:165:902)
    at n.Class.derive._oncancel._error (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:165:419)
    at ReadFileContext.<anonymous> (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:205:1001)
    at ReadFileContext.callback (/usr/share/code/resources/app/node_modules.asar/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (original-fs.js:420:13)
[2020-03-06 17:48:20.936] [renderer1] [info] no standard startup: not a new window
[2020-03-06 17:48:25.712] [renderer1] [error] Unsupported client
[2020-03-06 17:48:38.070] [renderer1] [error] Unsupported client
[2020-03-06 17:48:49.225] [renderer1] [error] Unsupported client
[2020-03-06 17:48:53.994] [renderer1] [error] Unsupported client
[2020-03-06 17:49:03.727] [renderer1] [error] Unsupported client
[2020-03-06 17:50:40.851] [renderer1] [error] Unsupported client
[2020-03-06 22:24:14.118] [renderer1] [error] Unsupported client
[2020-03-06 22:24:18.856] [renderer1] [error] Unsupported client
[2020-03-06 22:24:23.155] [renderer1] [error] Unsupported client
[2020-03-06 22:24:55.558] [renderer1] [error] Unsupported client
[2020-03-06 22:24:58.633] [renderer1] [error] Unsupported client
[2020-03-06 22:26:12.659] [renderer1] [error] Unsupported client


4. Log[Extension Host]
[2020-03-06 17:46:21.535] [exthost] [info] extension host started
[2020-03-06 17:46:21.651] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"activationEvent":"*"}
[2020-03-06 17:46:21.652] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/debug-auto-launch/dist/extension
[2020-03-06 17:46:21.684] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2020-03-06 17:46:21.684] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/emmet/dist/extension
[2020-03-06 17:46:21.831] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2020-03-06 17:46:21.831] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/git/dist/main
[2020-03-06 17:46:22.333] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2020-03-06 17:46:22.333] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/merge-conflict/dist/extension
[2020-03-06 17:46:22.357] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-rg {"startup":true,"activationEvent":"*"}
[2020-03-06 17:46:22.357] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/search-rg/dist/extension
[2020-03-06 17:46:22.375] [exthost] [info] eager extensions activated
[2020-03-06 17:47:30.244] [exthost] [info] extension host started
[2020-03-06 17:47:30.338] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"activationEvent":"*"}
[2020-03-06 17:47:30.338] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/debug-auto-launch/dist/extension
[2020-03-06 17:47:30.362] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2020-03-06 17:47:30.362] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/emmet/dist/extension
[2020-03-06 17:47:30.536] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2020-03-06 17:47:30.536] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/git/dist/main
[2020-03-06 17:47:31.015] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2020-03-06 17:47:31.016] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/merge-conflict/dist/extension
[2020-03-06 17:47:31.038] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-rg {"startup":true,"activationEvent":"*"}
[2020-03-06 17:47:31.038] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/search-rg/dist/extension
[2020-03-06 17:47:31.065] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.cpptools {"startup":true,"activationEvent":"*"}
[2020-03-06 17:47:31.066] [exthost] [info] ExtensionService#loadCommonJSModule /home/pi/.vscode/extensions/ms-vscode.cpptools-0.21.0/out/src/main
[2020-03-06 17:47:31.610] [exthost] [info] eager extensions activated
[2020-03-06 17:47:31.622] [exthost] [info] ExtensionService#_doActivateExtension austin.code-gnu-global {"startup":false,"activationEvent":"onLanguage:cpp"}
[2020-03-06 17:47:31.622] [exthost] [info] ExtensionService#loadCommonJSModule /home/pi/.vscode/extensions/austin.code-gnu-global-0.2.2/out/src/extension
[2020-03-06 17:47:31.689] [exthost] [info] ExtensionService#_doActivateExtension mitaki28.vscode-clang {"startup":false,"activationEvent":"onLanguage:cpp"}
[2020-03-06 17:47:31.689] [exthost] [info] ExtensionService#loadCommonJSModule /home/pi/.vscode/extensions/mitaki28.vscode-clang-0.2.3/out/src/extension
[2020-03-06 17:48:23.150] [exthost] [info] extension host started
[2020-03-06 17:48:23.221] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"activationEvent":"*"}
[2020-03-06 17:48:23.221] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/debug-auto-launch/dist/extension
[2020-03-06 17:48:23.260] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2020-03-06 17:48:23.260] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/emmet/dist/extension
[2020-03-06 17:48:23.421] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2020-03-06 17:48:23.421] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/git/dist/main
[2020-03-06 17:48:23.862] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2020-03-06 17:48:23.862] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/merge-conflict/dist/extension
[2020-03-06 17:48:23.881] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-rg {"startup":true,"activationEvent":"*"}
[2020-03-06 17:48:23.881] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/search-rg/dist/extension
[2020-03-06 17:48:23.909] [exthost] [info] ExtensionService#_doActivateExtension ACharLuk.easy-cpp-projects {"startup":true,"activationEvent":"workspaceContains:.vscode/.easycpp"}
[2020-03-06 17:48:23.909] [exthost] [info] ExtensionService#loadCommonJSModule /home/pi/.vscode/extensions/acharluk.easy-cpp-projects-1.7.7/out/extension
[2020-03-06 17:48:23.938] [exthost] [info] ExtensionService#_doActivateExtension austin.code-gnu-global {"startup":false,"activationEvent":"onLanguage:cpp"}
[2020-03-06 17:48:23.938] [exthost] [info] ExtensionService#loadCommonJSModule /home/pi/.vscode/extensions/austin.code-gnu-global-0.2.2/out/src/extension
[2020-03-06 17:48:23.992] [exthost] [info] ExtensionService#_doActivateExtension mitaki28.vscode-clang {"startup":false,"activationEvent":"onLanguage:cpp"}
[2020-03-06 17:48:23.992] [exthost] [info] ExtensionService#loadCommonJSModule /home/pi/.vscode/extensions/mitaki28.vscode-clang-0.2.3/out/src/extension
[2020-03-06 17:48:24.004] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.cpptools {"startup":false,"activationEvent":"onLanguage:cpp"}
[2020-03-06 17:48:24.004] [exthost] [info] ExtensionService#loadCommonJSModule /home/pi/.vscode/extensions/ms-vscode.cpptools-0.21.0/out/src/main
[2020-03-06 17:48:24.632] [exthost] [info] eager extensions activated
[2020-03-06 17:48:38.467] [exthost] [info] ExtensionService#_doActivateExtension vscode.grunt {"startup":false,"activationEvent":"onCommand:workbench.action.tasks.runTask"}
[2020-03-06 17:48:38.467] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/grunt/dist/main
[2020-03-06 17:48:38.484] [exthost] [info] ExtensionService#_doActivateExtension vscode.gulp {"startup":false,"activationEvent":"onCommand:workbench.action.tasks.runTask"}
[2020-03-06 17:48:38.484] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/gulp/dist/main
[2020-03-06 17:48:38.496] [exthost] [info] ExtensionService#_doActivateExtension vscode.jake {"startup":false,"activationEvent":"onCommand:workbench.action.tasks.runTask"}
[2020-03-06 17:48:38.496] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/jake/dist/main
[2020-03-06 17:48:38.508] [exthost] [info] ExtensionService#_doActivateExtension vscode.npm {"startup":false,"activationEvent":"onCommand:workbench.action.tasks.runTask"}
[2020-03-06 17:48:38.508] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/npm/dist/main
[2020-03-06 17:48:38.573] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"activationEvent":"onCommand:workbench.action.tasks.runTask"}
[2020-03-06 17:48:38.573] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/typescript-language-features/dist/extension
[2020-03-06 18:00:02.996] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"activationEvent":"onLanguage:jsonc"}
[2020-03-06 18:00:02.997] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/configuration-editing/dist/extension
[2020-03-06 18:00:03.041] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"activationEvent":"onLanguage:jsonc"}
[2020-03-06 18:00:03.041] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/json-language-features/client/dist/jsonMain
