### ISSUE TITLE
Stops working after a short while

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode-cpptools#525]
After a short while (20 minutes of development?), something seems to break. I can no longer format the document or visit declarations, etc.

There is nothing specific I can see in the console, except for:

//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:142 Connection is closed.e.onUnexpectedError @ //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:142(anonymous function) @ //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:142e.onUnexpectedError @ //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30o @ //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30t.onUnexpectedExtHostError @ //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:117e.handle @ //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:116s @ //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:54f @ //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:54_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:136 [Extension Host] rejected promise not handled within 1 second

**Comment by Gruntfuggly** [comment]
This is with the latest version: 0.10.2

**Comment by sean-mcmanus** [comment]
There are multiple instability issues we are working on fixing for the next release (that also reproed in earlier versions, not new to 0.10.2), but I'm not sure if this is one of them. Is the Microsoft.VSCode.Cpp.Extension process using CPU? It sounds like either the process or the main thread has crashed.

**Comment by Gruntfuggly** [comment]
Not seeing any CPU usage. Here are some more errors from the console, though:

8x //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:142 Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at /home/nscott/.vscode/extensions/ms-vscode.cpptools-0.10.2/out/src/LanguageServer/C_Cpp.js:101:76
    at e.invoke (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:9994)
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:13526)
    at t.$acceptSelectionsChanged (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:13:26057)
    at t.e.handle (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:20690)
    at s (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:8:30686)
    at p (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:8:31363)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)e.onUnexpectedError @ //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:142
13x //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:142 Cannot read property 'map' of undefined: TypeError: Cannot read property 'map' of undefined
    at asCompletionResult (/home/nscott/.vscode/extensions/ms-vscode.cpptools-0.10.2/node_modules/vscode-languageclient/lib/protocolConverter.js:79:46)
    at process._tickCallback (internal/process/next_tick.js:103:7)e.onUnexpectedError @ //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:142
2x //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:136 [Extension Host] TypeError: Cannot read property 'forEach' of null
    at LanguageClient.cleanUp (/home/nscott/.vscode/extensions/ms-vscode.cpptools-0.10.2/node_modules/vscode-languageclient/lib/main.js:471:24)
    at LanguageClient.stop (/home/nscott/.vscode/extensions/ms-vscode.cpptools-0.10.2/node_modules/vscode-languageclient/lib/main.js:454:14)
    at LanguageClient.handleConnectionError (/home/nscott/.vscode/extensions/ms-vscode.cpptools-0.10.2/node_modules/vscode-languageclient/lib/main.js:684:18)
    at errorHandler (/home/nscott/.vscode/extensions/ms-vscode.cpptools-0.10.2/node_modules/vscode-languageclient/lib/main.js:559:19)
    at /home/nscott/.vscode/extensions/ms-vscode.cpptools-0.10.2/node_modules/vscode-languageclient/lib/main.js:45:42
    at CallbackList.invoke (/home/nscott/.vscode/extensions/ms-vscode.cpptools-0.10.2/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/events.js:103:39)
    at Emitter.fire (/home/nscott/.vscode/extensions/ms-vscode.cpptools-0.10.2/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/events.js:167:36)
    at writeErrorHandler (/home/nscott/.vscode/extensions/ms-vscode.cpptools-0.10.2/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:113:22)
    at CallbackList.invoke (/home/nscott/.vscode/extensions/ms-vscode.cpptools-0.10.2/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/events.js:103:39)
    at Emitter.fire (/home/nscott/.vscode/extensions/ms-vscode.cpptools-0.10.2/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/events.js:167:36)d.logExtensionHostMessage @ //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:136
//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:142 no adapter found: Error: no adapter found
    at t._withAdapter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:14:15321)
    at t.$provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:14:18693)
    at t.e.handle (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:20690)
    at s (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:8:30686)
    at p (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:8:31363)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)e.onUnexpectedError @ //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:142
//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:142 Connection is closed.: Error: Connection is closed.
    at throwIfClosedOrDisposed (/home/nscott/.vscode/extensions/ms-vscode.cpptools-0.10.2/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:371:19)
    at Object.sendNotification (/home/nscott/.vscode/extensions/ms-vscode.cpptools-0.10.2/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:384:13)
    at /home/nscott/.vscode/extensions/ms-vscode.cpptools-0.10.2/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:427:32
    at e.invoke (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:9994)
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:13526)
    at e.cancel (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:16272)
    at e.cancel (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:16882)
    at ._oncancel (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:17749)
    at _cancelAction (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:13938)
    at Object.enter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:9679)

**Comment by sean-mcmanus** [comment]
We have a repro with an internal project, but it doesn't repro with other projects, assuming it's the same bug in which parsing a particular file causes the failure. Using a different/smaller workspace that doesn't have the bad file or adding a files.exclude might be a workaround, but I don't have a good way yet to tell which file is causing the problem (without using a debugger). Our parsing executable doesn't output messages to the Console, but the errors about C_Cpp.js are caused by the javascript not being able to communicate with the failed engine process.

**Comment by sean-mcmanus** [comment]
Does this still repro with 0.10.3?

**Comment by UR3IQO** [comment]
@sean-mcmanus Don't know if I had the same problem, but 0.10.2 was very unstable and language service stopped after several minutes of coding. 0.10.3 is more stable, but it sill stops from time to time (4 times in the last two days). I am not sure but it seems there is some interaction with the debugger.

**Comment by sean-mcmanus** [comment]
Yes, it's a bug with signatureHelp. \<non-identifierChar\>\<whitespace\>( triggers a crash. We've fixed it and we're planning to release a fix ASAP.

**Comment by bobbrow** [comment]
The signature help bug has been fixed and is in version 0.10.4.  Please give it a try and let us know if you are still having issues.

**Comment by Gruntfuggly** [comment]
It's much better - it worked for over three hours this morning, but just stopped working again. 8-( 

Unfortunately I didn't manage to capture any error details, but if it happens again I will.

**Comment by UR3IQO** [comment]
@bobbrow I looks like the problem is gone (it was ok for the several hours yesterday).

**Comment by bobbrow** [comment]
Thanks @sov1178.  I'll close this issue.  @Gruntfuggly, we have another crash issue we haven't quite identified yet and are tracking with #430.  Please chime in on that issue if you get any additional information.  Thanks!

**Comment by aytekinar** [comment]
This problem is there, again, with
```
Version 1.17.1
Commit 1e9d36539b0ae51ac09b9d4673ebea4e447e5353
```
and cpptools `0.13.1`. After some time of development, the "Format document" option is simply gone. I need to restart VS Code to get it back working again 👎

**Comment by sean-mcmanus** [comment]
@aytekinar There's a crash with signature help that should be fixed in our pending update. We also have an issue in which our extension doesn't recover correctly after a crash.

**Comment by aytekinar** [comment]
@sean-mcmanus so you are aware of this problem and hoping that it gets fixed soon with the coming update(s)?

**Comment by sean-mcmanus** [comment]
@aytekinar We won't have a fix for the recovering after a crash issue by our next update (should be the one after that), but the crashes for the main process should be fairly low after the signature help crash is fixed.
