### ISSUE TITLE
Debugging support for unit test in vscode-remote

### ISSUE THREAD

**Issue by moshangcheng** [microsoft/vscode-cpptools#5274]
Type: Debugger

 I cannot debug test cases in vscode-remote using vscode-catch2-test-adapter. 

**Describe the bug**
- OS and Version: Mac Mojave / docker-1.13.1-102.git7f2769b.el7.centos.x86_64 /
- VS Code Version: 1.44.0
- C/C++ Extension Version: 0.27.0 
- Other extensions you installed (and if the issue persists after disabling them): 
vscode-catch2-test-adapter 2.8.13
- I can debug test cases using the same configuration in local vscode on my Mac. In vscode-remote , after failure of debugging google test cases using catch2-test-adapter, vscode debugger seems to be broken, and "g++ - Build and debug active file" doesn't work too.

**To Reproduce**

1. open vscode-remote and ssh to a remote machine
2. open terminal and git clone https://github.com/bast/gtest-demo
3. build project
4. try to debug test case

**Additional context**
[related issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/173)

```
[2020-04-09 09:09:55.546] [INFO] Debugging
[2020-04-09 09:09:55.548] [INFO] testInfo i {
  _shared: {
    log: s {
      configSection: 'catch2TestExplorer',
      workspaceFolder: { uri: [h], name: 'gtest-demo', index: 0 },
      outputChannelName: 'Test Explorer: gtest-demo',
      inspectOptions: { showProxy: true, depth: 3 },
      includeLocation: true,
      targets: [ [a] ],
      nextInspectOptions: undefined,
      configChangeSubscription: { dispose: [Function: dispose] }
    },
    workspaceFolder: {
      uri: h {
        scheme: 'file',
        authority: '',
        path: '/data0/sheng/dev/src/github.com/bast/gtest-demo',
        query: '',
        fragment: '',
        _formatted: 'file:///data0/sheng/dev/src/github.com/bast/gtest-demo',
        _fsPath: '/data0/sheng/dev/src/github.com/bast/gtest-demo'
      },
      name: 'gtest-demo',
      index: 0
    },
    testStatesEmitter: e {
      _disposed: false,
      _options: undefined,
      _leakageMon: undefined,
      _event: [Function],
      _listeners: { _first: [e], _last: [e], _size: 1 },
      _deliveryQueue: { _first: [e], _last: [e], _size: 0 }
    },
    loadWithTaskEmitter: e {
      _disposed: false,
      _options: undefined,
      _leakageMon: undefined,
      _event: [Function],
      _listeners: { _first: [e], _last: [e], _size: 1 }
    },
    sendTestEventEmitter: e {
      _disposed: false,
      _options: undefined,
      _leakageMon: undefined,
      _event: [Function],
      _listeners: { _first: [e], _last: [e], _size: 1 }
    },
    retire: e {
      _disposed: false,
      _options: undefined,
      _leakageMon: undefined,
      _event: [Function],
      _listeners: { _first: [e], _last: [e], _size: 1 }
    },
    rngSeed: null,
    execWatchTimeout: 10000,
    retireDebounceTime: 1000,
    _execRunningTimeout: 600000,
    execParsingTimeout: 5000,
    isNoThrow: false,
    enabledTestListCaching: false,
    googleTestTreatGMockWarningAs: 'nothing',
    googleTestGMockVerbose: 'default',
    _execRunningTimeoutChangeEmitter: e {
      _disposed: false,
      _options: undefined,
      _leakageMon: undefined,
      _event: [Function],
      _listeners: { _first: [e], _last: [e], _size: 0 }
    },
    onDidChangeExecRunningTimeout: [Function],
    taskPool: { _maxTaskCount: 1, _runningTaskCount: 0, _waitingTasks: [] }
  },
  testNameAsId: 'example.add',
  label: 'add',
  skipped: false,
  line: undefined,
  type: 'test',
  lastRunEvent: {
    type: 'test',
    test: [Circular],
    state: 'passed',
    message: '[ RUN      ] example.add\n[       OK ] example.add (0 ms)',
    decorations: [],
    description: '(0ms)',
    tooltip: 'Name: example.add\n\n⏱Duration: 0ms'
  },
  lastRunMilisec: 0,
  id: '4',
  origLabel: 'add',
  description: '',
  file: undefined,
  tooltip: 'Name: example.add'
} [ '4' ];
[2020-04-09 09:09:55.549] [INFO] using user defined debug config
[2020-04-09 09:09:55.550] [INFO] Debug: resolved debugConfig: {
  name: 'add (unit_tests ➡️ example)',
  request: 'launch',
  type: 'cppdbg',
  MIMode: 'gdb',
  program: '/data0/sheng/dev/src/github.com/bast/gtest-demo/build/bin/unit_tests',
  args: [
    '--gtest_color=no',
    '--gtest_filter=example.add',
    '--gtest_break_on_failure',
    '--gtest_also_run_disabled_tests'
  ],
  cwd: '/data0/sheng/dev/src/github.com/bast/gtest-demo/build/bin',
  env: {
    CPLUS_INCLUDE_PATH: '/usr/include/c++/8.3.0/',
    HOSTNAME: 'fb9154a1cb70',
    SHELL: '/bin/bash',
    HISTSIZE: '1000',
    SSH_CLIENT: '172.16.250.3 56128 22',
    CONDA_SHLVL: '1',
    CONDA_PROMPT_MODIFIER: '(base) ',
    USER: 'sheng',
    LD_LIBRARY_PATH: '/opt/rh/httpd24/root/usr/lib64/:/usr/lib64:/usr/lib:',
    CONDA_EXE: '/data0/sheng/miniconda3/bin/conda',
    _CE_CONDA: '',
    VSCODE_AGENT_FOLDER: '/data0/sheng/.vscode-server',
    MAIL: '/var/spool/mail/sheng',
    PATH: '/data0/sheng/.vscode-server/bin/2aae1f26c72891c399f860409176fe435a154b13/bin:/data0/sheng/miniconda3/bin:/data0/sheng/setup/apache-maven-3.6.0/bin:/data0/sheng/local/bin:/opt/rh/rh-git218/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/data0/sheng/.local/bin:/data0/sheng/bin:/adding/new/item/to/PATH/env',
    CONDA_PREFIX: '/data0/sheng/miniconda3',
    C_INCLUDE_PATH: '/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include',
    PWD: '/data0/sheng',
    LANG: 'en_US.UTF-8',
    TZ: 'Asia/Shanghai',
    _CE_M: '',
    HISTCONTROL: 'ignoredups',
    SHLVL: '4',
    HOME: '/data0/sheng',
    CONDA_PYTHON_EXE: '/data0/sheng/miniconda3/bin/python',
    LOGNAME: 'sheng',
    SSH_CONNECTION: '172.16.250.3 56128 172.17.0.9 22',
    CONDA_DEFAULT_ENV: 'base',
    LESSOPEN: '||/usr/bin/lesspipe.sh %s',
    _: '/data0/sheng/.vscode-server/bin/2aae1f26c72891c399f860409176fe435a154b13/node',
    VSCODE_INJECT_NODE_MODULE_LOOKUP_PATH: '/data0/sheng/.vscode-server/bin/2aae1f26c72891c399f860409176fe435a154b13/remote/node_modules',
    VSCODE_LOGS: '/data0/sheng/.vscode-server/data/logs/20200409T162543',
    AMD_ENTRYPOINT: 'vs/server/remoteExtensionHostProcess',
    PIPE_LOGGING: 'true',
    VERBOSE_LOGGING: 'true',
    VSCODE_EXTHOST_WILL_SEND_SOCKET: 'true',
    VSCODE_HANDLES_UNCAUGHT_ERRORS: 'true',
    VSCODE_LOG_STACK: 'false',
    VSCODE_NLS_CONFIG: '{"locale":"en","availableLanguages":{}}',
    VSCODE_IPC_HOOK_CLI: '/tmp/vscode-ipc-c7bd686f-62fe-406b-b997-316559a57126.sock',
    APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL: 'true',
    ExampleENV1: 'You can use variables here too, like build/bin/unit_tests'
  },
  externalConsole: false,
  'magic variable  🤦🏼‍': '7'
}
[2020-04-09 09:09:55.552] [INFO] startDebugging
[2020-04-09 09:09:57.165] [INFO] [Error: Failed starting the debug session. Maybe something wrong with "catch2TestExplorer.debugConfigTemplate".
	at /data0/sheng/.vscode-server/extensions/matepek.vscode-catch2-test-adapter-2.8.13/out/dist/main.js:22:17653
	at processTicksAndRejections (internal/process/task_queues.js:89:5)]
```

**Comment by WardenGnaw** [comment]
This repository is for the VS Code C/C++ extension. You will want to file this on [vscode-catch2-test-adapter's issues](https://github.com/matepek/vscode-catch2-test-adapter/issues) page.

**Comment by matepek** [comment]
Hello, 

I'm the developer of that extension.
According to the log my extension gets the proper command and starts the debug session with the configuration bellow.

There is no special handling at my code so I assume it should work out of the box. @WardenGnaw Please check the config, maybe it is not correct. If you think it is correct, don't you agree that vscode-cpptool, vscode-remote or vscode itself should have the bug?

```
{
  name: 'add (unit_tests ➡️ example)',
  request: 'launch',
  type: 'cppdbg',
  MIMode: 'gdb',
  program: '/data0/sheng/dev/src/github.com/bast/gtest-demo/build/bin/unit_tests',
  args: [
    '--gtest_color=no',
    '--gtest_filter=example.add',
    '--gtest_break_on_failure',
    '--gtest_also_run_disabled_tests'
  ],
  cwd: '/data0/sheng/dev/src/github.com/bast/gtest-demo/build/bin',
  env: {
    ... see first comment for details..
  },
  externalConsole: false,
  'magic variable  🤦🏼‍': '7'
}
```

**Comment by matepek** [comment]
Nevermind now. We are investigating further.
