### ISSUE TITLE
Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by miniyuan** [microsoft/vscode-cpptools#5324]
**Type: LanguageService**

**Describe the bug**
- OS and Version:windows 2008 r2 x64
- VS Code Version:1.44
- C/C++ Extension Version:0.27
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "D:\\devtools\\mingw32\bin\\g++.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by miniyuan** [comment]
Connection got disposed.: Error: Connection got disposed.
	at Object.dispose (c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:3814:25)
	at Object.dispose (c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:5393:35)
	at LanguageClient.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:7475:42)
	at LanguageClient.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:16494:15)
	at closeHandler (c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:7462:18)
	at CallbackList.invoke (c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:11264:39)
	at Emitter.fire (c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:11322:36)
	at closeHandler (c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:3164:26)
	at CallbackList.invoke (c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:11264:39)
	at Emitter.fire (c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:11322:36)
	at StreamMessageReader.fireClose (c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:14035:27)
	at Socket.<anonymous> (c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:14075:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)

**Comment by sean-mcmanus** [comment]
Our cpptools process crashed. Most likely caused by https://github.com/microsoft/vscode-cpptools/issues/5280  . We'll try to release a fix soon.

**Comment by elahehrashedi** [comment]
This issue is fixed in 0.28.0.
0.28.0 release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0

**Comment by devfchen** [comment]
seems not fix in wsl

**Comment by sean-mcmanus** [comment]
@puckchen Your crash repro may be different. Are you able to provide more repro details or attach a debugger to the cpptools process to get a crash call stack? What steps do you do that cause the "Connection to server got closed."?

**Comment by ospilos** [comment]
It works fine up to V0.25.1
It crashes as soon as I add a project into my workspace with V0.26.0 - V0.29.0

**Comment by sean-mcmanus** [comment]
@ospilos We need more repro and/or a call stack of the particular crash you are hitting (preferably in a new issue). "Connection to server got closed." is a generic symptom of the cpptools-srv process crashing.
