### ISSUE TITLE
C++ Extension totally not working

### ISSUE THREAD

**Issue by Mufassir-Chowdhury** [microsoft/vscode-cpptools#5336]
Hello!
I'm on windows 10. Using vs code 1.44.2 and c++ extension 0.27.0.
The extension was working fine until few days ago, it showed couldn't connect to server error. Now it's showing the following error. 

What should I do? 
```
[Error - 12:49:51 PM] Sending notification cpptools/activeDocumentChange failed.
Error: Connection is disposed.
	at throwIfClosedOrDisposed (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:3602:19)
	at Object.sendNotification (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:3649:13)
	at Object.sendNotification (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:5363:56)
	at LanguageClient.sendNotification (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:7055:38)
	at c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:36316:33
	at c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:36058:21
	at new Promise (<anonymous>)
	at task (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:36057:26)
	at DefaultClient.<anonymous> (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:36006:34)
	at Generator.next (<anonymous>)
	at c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:34692:71
	at new Promise (<anonymous>)
	at module.exports.__awaiter (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:34688:12)
	at nextTask (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:36004:34)
	at DefaultClient.queueTask (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:36018:24)
	at DefaultClient.notifyWhenReady (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:36060:21)
	at DefaultClient.activeDocumentChanged (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:36315:14)
	at ClientCollection.replace (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:34598:35)
	at Object.closed (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:35492:52)
	at LanguageClient.handleConnectionClosed (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:7483:55)
	at LanguageClient.handleConnectionClosed (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:16494:15)
	at closeHandler (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:7462:18)
	at CallbackList.invoke (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:11264:39)
	at Emitter.fire (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:11322:36)
	at closeHandler (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:3164:26)
	at CallbackList.invoke (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:11264:39)
	at Emitter.fire (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:11322:36)
	at StreamMessageReader.fireClose (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:14035:27)
	at Socket.<anonymous> (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:14075:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)

**Comment by michelleangela** [comment]
@Mufassir-Chowdhury 
Can you verify files `cpptools.exe` and `cpptools-srv.exe` exist under the folder `c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\bin` ? If the files are missing, please uninstall or delete the entire `ms-vscode.cpptools-0.27.0` folder and re-install the extension.

**Comment by Mufassir-Chowdhury** [comment]
> 
> 
> @Mufassir-Chowdhury
> Can you verify files `cpptools.exe` and `cpptools-srv.exe` exist under the folder `c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.27.0\bin` ? If the files are missing, please uninstall or delete the entire `ms-vscode.cpptools-0.27.0` folder and re-install the extension.

I did check. they are under the folder ending with 0.27.0 but there is another folder ending with 0.27.1 where these are missing

**Comment by sean-mcmanus** [comment]
@Mufassir-Chowdhury Are you using 0.27.0 or 0.27.1? It sounds like you're using 0.27.1 with binaries missing for some reason. Can you uninstall whatever extension you have installed, close/reopen VS Code, then install the latest 0.27.1? That should download the binaries unless there's some error. Installing the 0.27.1 offline vsix is another option: https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.1
