### ISSUE TITLE
Need help: Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by Aris1401** [microsoft/vscode-cpptools#5806]
Type: General
With Visual Studio Code I'm having the issue: **Connection to server got closed. Server will not be restarted.**

**Describe the bug**
- OS and Version: Windows 7 x86
- VS Code Version: 1.47.2
- C/C++ Extension Version: 0.29.0
- Issue: Few times after I installed the c++ tools and created the first source file, I'm getting some errors that say **Connection to server got closed. Server will not be restarted.**

**Expected behavior**
Here is the whole error message:
`[Error - 18:27:21] Connection to server got closed. Server will not be restarted.
[Error - 18:27:22] Request completionItem/resolve failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\08-PC\.vscode\extensions\ms-vscode.cpptools-0.29.0\dist\main.js:3890:25)
	at Object.dispose (c:\Users\08-PC\.vscode\extensions\ms-vscode.cpptools-0.29.0\dist\main.js:5415:35)
	at LanguageClient.handleConnectionClosed (c:\Users\08-PC\.vscode\extensions\ms-vscode.cpptools-0.29.0\dist\main.js:7497:42)
	at LanguageClient.handleConnectionClosed (c:\Users\08-PC\.vscode\extensions\ms-vscode.cpptools-0.29.0\dist\main.js:18130:15)
	at closeHandler (c:\Users\08-PC\.vscode\extensions\ms-vscode.cpptools-0.29.0\dist\main.js:7484:18)
	at CallbackList.invoke (c:\Users\08-PC\.vscode\extensions\ms-vscode.cpptools-0.29.0\dist\main.js:11876:39)
	at Emitter.fire (c:\Users\08-PC\.vscode\extensions\ms-vscode.cpptools-0.29.0\dist\main.js:11934:36)
	at closeHandler (c:\Users\08-PC\.vscode\extensions\ms-vscode.cpptools-0.29.0\dist\main.js:3240:26)
	at CallbackList.invoke (c:\Users\08-PC\.vscode\extensions\ms-vscode.cpptools-0.29.0\dist\main.js:11876:39)
	at Emitter.fire (c:\Users\08-PC\.vscode\extensions\ms-vscode.cpptools-0.29.0\dist\main.js:11934:36)
	at StreamMessageReader.fireClose (c:\Users\08-PC\.vscode\extensions\ms-vscode.cpptools-0.29.0\dist\main.js:13909:27)
	at Socket.<anonymous> (c:\Users\08-PC\.vscode\extensions\ms-vscode.cpptools-0.29.0\dist\main.js:13949:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)`

**Additional context**
I don't know if this is a bug or something like that but I need some help for fixing it.

**Comment by Colengms** [comment]
Hi @Aris1401.  Since it sounds like this is happening even with the simplest of files, could you try reinstalling the extension?  I'd suggest uninstalling it from within VS Code, removing the extension directory from `%USERPROFILE%\.vscode\extensions`, then reinstalling it.  That should ensure a fresh re-install.

If the issue continues, could you enable debug logging using `"C_Cpp.loggingLevel": "Debug"`, and provide the content of the C/C++ output channel leading up to the issue?
