### ISSUE TITLE
Language server crashes on C++20 coroutines

### ISSUE THREAD

**Issue by ytimenkov** [microsoft/vscode-cpptools#6363]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Linux Ubuntu 20.04
- VS Code Version: 1.50.1
- C/C++ Extension Version: 1.1.0-insiders2
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- boost 1.74

**Problem**
1. Code is initially parsed but problems show "no viable 'operator delete' found for coroutine state deallocation" on a function.
2. When I try to hover on any symbol or type and trigger completion LS process crashes.

Source code:
```
#include <boost/asio/awaitable.hpp>
#include <boost/asio/co_spawn.hpp>
#include <boost/asio/detached.hpp>
#include <boost/beast/core.hpp>
#include <boost/beast/http.hpp>
#include <boost/beast/version.hpp>

namespace beast = boost::beast;
namespace http = beast::http;
namespace net = boost::asio;
using net::ip::tcp;

boost::asio::awaitable<void> test_coro()
{
    auto executor = co_await net::this_coro::executor;
    tcp::acceptor acceptor{executor, {tcp::v4(), 8080}};

    for (;;)
    {
        tcp::socket socket = co_await acceptor.async_accept(net::use_awaitable);
    }
}
```

`compile_commands.json`:
```
{
  "directory": "/home/dev/eems/build/dev",
  "command": "/usr/bin/g++-10 -DBOOST_ALL_DYN_LINK -DBOOST_ASIO_NO_DEPRECATED -DBOOST_ASIO_NO_TS_EXECUTORS -DBOOST_ASIO_SEPARATE_COMPILATION -DBOOST_BEAST_SEPARATE_COMPILATION -DBOOST_BEAST_USE_STD_STRING_VIEW -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -D_GLIBCXX_USE_CXX11_ABI=1 -isystem /home/dev/.conan/data/boost/1.74.0/_/_/package/e6ed416de4dedfeb81b2621d799410e19b48b094/include -isystem /home/dev/.conan/data/zlib/1.2.11/_/_/package/558da49200df3200c150bf256292d77fa53f0163/include -isystem /home/dev/.conan/data/bzip2/1.0.8/_/_/package/cb169c49e6778c1ff124cf8bc253ee5b36a78eec/include -isystem /home/dev/.conan/data/fmt/7.0.3/_/_/package/5a5770c223c32b30354f325ae1d0960132cda041/include -isystem /home/dev/.conan/data/spdlog/1.8.0/_/_/package/e51cec4427e190c8b073a0c40a8d1f89abe1d4b3/include -isystem /home/dev/.conan/data/pugixml/1.10/_/_/package/fbad2bc3c21f634d5c14ba0fe643747a1ca553f3/include -isystem /home/dev/.conan/data/skyr-url/1.12.0/_/_/package/2b160bc07b75c70b47d26133122640a3ee14d49c/include -isystem /home/dev/.conan/data/tl-expected/1.0.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -isystem /home/dev/.conan/data/range-v3/0.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -Og -Werror -Wall  -m64 -g -fcoroutines -std=c++2a -o src/CMakeFiles/eems.dir/server.cpp.o -c /home/dev/eems/src/server.cpp",
  "file": "/home/dev/eems/src/server.cpp"
},
```

When I attached to the LS process:
```
Thread 2 "cpptools-srv" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f663c6ee700 (LWP 20906)]
0x000000000081a995 in walk_entry_and_subtree(char*, an_il_entry_kind) ()
(gdb) bt
#0  0x000000000081a995 in walk_entry_and_subtree(char*, an_il_entry_kind) ()
#1  0x000000000081d275 in walk_entry_and_subtree(char*, an_il_entry_kind) ()
#2  0x000000000081b59b in walk_entry_and_subtree(char*, an_il_entry_kind) ()
#3  0x000000000081e370 in walk_entry_and_subtree(char*, an_il_entry_kind) ()
#4  0x0000000000824ce3 in walk_entry_and_subtree(char*, an_il_entry_kind) ()
#5  0x0000000000823c9b in walk_entry_and_subtree(char*, an_il_entry_kind) ()
#6  0x0000000000822a18 in walk_entry_and_subtree(char*, an_il_entry_kind) ()
#7  0x000000000082575d in walk_routine_scope_il_full(int, void (*)(char*, an_il_entry_kind), void (*)(char*, an_il_entry_kind, unsigned long), char* (*)(char*, an_il_entry_kind), char* (*)(char*, an_il_entry_kind), int (*)(char*, an_il_entry_kind), int, int, int) ()
#8  0x000000000062466a in details::get_decl_search_index(int) ()
#9  0x00000000006249df in trees_overlapping_span(msvc::strong_typedef_t<msvc::offset_traits>, msvc::strong_typedef_t<msvc::offset_traits>, a_treenav_result*, unsigned long) ()
#10 0x00000000005c9072 in edge::scoped_query_manager::get_trees_overlapping_span(a_canonicalized_file_name, msvc::strong_typedef_t<msvc::offset_traits>, msvc::strong_typedef_t<msvc::offset_traits>, int, edge::tree_query_result_builder*) ()
#11 0x0000000000602d86 in edge::intellisense_operation::scope_at_cursor(edge::member_selection_entry**, bool) ()
#12 0x0000000000603b53 in edge::intellisense_operation::get_auto_complete_members(edge::member_selection_entry*&, edge::scope_entry*&, edge::list<edge::symbol*>*, edge::list<edge::symbol*>*, edge::list<edge::symbol*>*, edge::list<edge::symbol*>*, edge::intellisense_operation::member_list_kind, bool, bool&, bool&, bool&) ()
#13 0x0000000000598a8b in std::_Function_handler<void (edge::intellisense_operation&, bool&), edge_intellisense_server_impl::handle_completion(microsoft::cpp::intellisense::CompletionRequest const&)::{lambda(edge::intellisense_operation&, bool&)#1}>::_M_invoke(std::_Any_data const&, edge::intellisense_operation&, bool&) ()
#14 0x0000000000597940 in void edge_intellisense_operation::perform_isense_operation<bool>(char const*, microsoft::cpp::intellisense::DocumentPosition const&, std::function<void (edge::intellisense_operation&, bool&)>, bool&, snapshot::snapshot_session_t, bool, edge::allocator*) ()
#15 0x000000000057ae58 in edge_intellisense_server_impl::handle_completion(microsoft::cpp::intellisense::CompletionRequest const&) ()
#16 0x00000000005a81bc in work_queue::worker_proc() ()
#17 0x00000000009e5692 in std::_Function_handler<void (), msvc::thread_pool::enqueue(std::function<void ()>, std::future<void>*)::$_2>::_M_invoke(std::_Any_data const&) ()
#18 0x00000000009e4520 in msvc::thread_pool::do_work(unsigned long) ()
#19 0x0000000000ac2f20 in execute_native_thread_routine ()
#20 0x00007f663c91b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#21 0x00007f663c842293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Output on Debug level:
```
IntelliSense client not available, using Tag Parser for quick info.
using Tag Parser for quick info
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
IntelliSense engine is not responding. Using the Tag Parser instead.
```

Maybe related to #6251

Please let me know if I can do any further diagnostics (e.g. attach core file or run under valgrind...)

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. It's not related to https://github.com/microsoft/vscode-cpptools/issues/6251 (different crash). I've filed a bug on our shared parser code for VS at https://developercommunity.visualstudio.com/content/problem/1238527/c-intellisense-crashes-when-using-c20-co-await-wit.html .

**Comment by ytimenkov** [comment]
I see that you still have a lot of improvements pending for 1.2 release, but would it be possible to release an insiders version (or even a snapshot) which doesn't crash to have a chance to poke it during long holidays? ❤

Or is there a workaround or a way to not crash when opening file with coroutines?

**Comment by sean-mcmanus** [comment]
Sure -- sounds like a good idea to me. 1.2.0-preview is available at https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-preview. Let us know if you're still getting problems with coroutines or you experience any other regression bugs.

**Comment by ytimenkov** [comment]
![image](https://user-images.githubusercontent.com/7413219/102851482-3a21d180-441c-11eb-930e-8ab50d258cce.png)
Awesome! 🤤
