### ISSUE TITLE
IntelliSense failure with arangodb

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6458]
I'm also getting these messages in Output (logs of extension host).

- Version: 1.50.1 (user setup)
- Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
- Datum: 2020-10-13T15:06:15.712Z
- Electron: 9.2.1
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- Betriebssystem: Windows_NT x64 10.0.19041

While trying to debug the issue, there were also other messages about a timeout, but possibly unrelated (only got this once, whereas the provider FAILED message occurs way more frequent):

```
[2020-11-05 11:55:35.218] [exthost] [error] [ms-vscode.cpptools] provider FAILED
[2020-11-05 11:55:35.218] [exthost] [error] undefined
[2020-11-05 11:55:35.260] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"extensionId":{"value":"vscode.typescript-language-features","_lower":"vscode.typescript-language-features"},"activationEvent":"onLanguage:javascript"}
[2020-11-05 11:55:35.261] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Simran/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/typescript-language-features/dist/extension
[2020-11-05 11:55:35.278] [exthost] [info] ExtensionService#_doActivateExtension vscode.extension-editing {"startup":false,"extensionId":{"value":"vscode.extension-editing","_lower":"vscode.extension-editing"},"activationEvent":"onLanguage:markdown"}
[2020-11-05 11:55:35.279] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Simran/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/extension-editing/dist/extensionEditingMain
[2020-11-05 11:55:35.286] [exthost] [info] ExtensionService#_doActivateExtension vscode.markdown-language-features {"startup":false,"extensionId":{"value":"vscode.markdown-language-features","_lower":"vscode.markdown-language-features"},"activationEvent":"onLanguage:markdown"}
[2020-11-05 11:55:35.287] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Simran/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/markdown-language-features/dist/extension
[2020-11-05 11:55:36.760] [exthost] [error] onWillSaveTextDocument-listener from extension 'ms-vscode.cpptools' threw ERROR
[2020-11-05 11:55:36.760] [exthost] [error] Error: timeout
	at Timeout._onTimeout (c:\Users\Simran\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:638:581)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)
[2020-11-05 11:55:36.760] [exthost] [error] onWillSaveTextDocument-listener from extension 'ms-vscode.cpptools' threw ERROR
[2020-11-05 11:55:36.760] [exthost] [error] Error: timeout
	at Timeout._onTimeout (c:\Users\Simran\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:638:581)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)
[2020-11-05 11:55:36.760] [exthost] [error] onWillSaveTextDocument-listener from extension 'ms-vscode.cpptools' threw ERROR
[2020-11-05 11:55:36.760] [exthost] [error] Error: timeout
	at Timeout._onTimeout (c:\Users\Simran\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:638:581)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)
[2020-11-05 11:55:36.760] [exthost] [error] onWillSaveTextDocument-listener from extension 'ms-vscode.cpptools' threw ERROR
[2020-11-05 11:55:36.761] [exthost] [error] Error: timeout
	at Timeout._onTimeout (c:\Users\Simran\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:638:581)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)
```

Here's the call stack if I break on exceptions:

- Main thread

      ntdll.dll!_NtWaitForSingleObject@12() (Unbekannte Quelle:0)
      KernelBase.dll!WaitForSingleObjectEx() (Unbekannte Quelle:0)
      KernelBase.dll!GetOverlappedResult() (Unbekannte Quelle:0)
      cpptools-srv.exe!read_pipe_sync(void *,unsigned long,void *) (Unbekannte Quelle:0)
      cpptools-srv.exe!comm_pipe_win32::read(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &) (Unbekannte Quelle:0)
      cpptools-srv.exe!comm_server::wait_for_requests(void) (Unbekannte Quelle:0)
      cpptools-srv.exe!_main() (Unbekannte Quelle:0)
      cpptools-srv.exe!__scrt_common_main_seh() (Unbekannte Quelle:0)
      kernel32.dll!@BaseThreadInitThunk@12() (Unbekannte Quelle:0)
      ntdll.dll!__RtlUserThreadStart() (Unbekannte Quelle:0)
      ntdll.dll!__RtlUserThreadStart@8() (Unbekannte Quelle:0)

- 3x `ntdll.dll!TppWorkerThread`

      ntdll.dll!_NtWaitForWorkViaWorkerFactory@20() (Unbekannte Quelle:0)
      ntdll.dll!TppWorkerThread() (Unbekannte Quelle:0)
      kernel32.dll!@BaseThreadInitThunk@12() (Unbekannte Quelle:0)
      ntdll.dll!__RtlUserThreadStart() (Unbekannte Quelle:0)
      ntdll.dll!__RtlUserThreadStart@8() (Unbekannte Quelle:0)

- 8x `cpptools-srv.exe!thread_start<unsigned int(__stdcall*)(void *),1>`

      ntdll.dll!_NtWaitForMultipleObjects@20() (Unbekannte Quelle:0)
      KernelBase.dll!WaitForMultipleObjectsEx() (Unbekannte Quelle:0)
      cpptools-srv.exe!msvc::alertable_event::wait_for_multiple(class msvc::alertable_event * *,unsigned int,bool,unsigned int) (Unbekannte Quelle:0)
      cpptools-srv.exe!msvc::thread_pool::do_work(unsigned int) (Unbekannte Quelle:0)
      cpptools-srv.exe!std::thread::_Invoke<class std::tuple<class <lambda_a0cbe141f7d7ac57b80358412e72d184> >,0>(void *) (Unbekannte Quelle:0)
      cpptools-srv.exe!thread_start<unsigned int (__stdcall*)(void *),1>() (Unbekannte Quelle:0)
      kernel32.dll!@BaseThreadInitThunk@12() (Unbekannte Quelle:0)
      ntdll.dll!__RtlUserThreadStart() (Unbekannte Quelle:0)
      ntdll.dll!__RtlUserThreadStart@8() (Unbekannte Quelle:0)

- `cpptools-srv.exe!thread_start<unsigned int(__stdcall*)(void *),1>`

      ntdll.dll!_NtWaitForSingleObject@12() (Unbekannte Quelle:0)
      KernelBase.dll!WaitForSingleObjectEx() (Unbekannte Quelle:0)
      cpptools-srv.exe!__Thrd_join() (Unbekannte Quelle:0)
      cpptools-srv.exe!std::thread::join(void) (Unbekannte Quelle:0)
      cpptools-srv.exe!a_compiler_thread::~a_compiler_thread(void) (Unbekannte Quelle:0)
      cpptools-srv.exe!edge::an_edge_translation_unit_impl::reinitialize_without_fallback(bool,struct snapshot::snapshot_session_t,struct edge::file_position const &,class edge::query_action_data &) (Unbekannte Quelle:0)
      cpptools-srv.exe!edge::an_edge_translation_unit_impl::reinitialize(bool,struct snapshot::snapshot_session_t,struct edge::file_position const &,class edge::query_action_data &) (Unbekannte Quelle:0)
      cpptools-srv.exe!edge::scoped_query_manager::check_and_compile(struct edge::file_position const &,struct edge::file_position const &,struct edge::file_position const &,bool,bool) (Unbekannte Quelle:0)
      cpptools-srv.exe!edge::scoped_query_manager::update_fragment(struct edge::file_position const &,struct edge::file_position const &,struct edge::file_position const &,bool,bool,bool) (Unbekannte Quelle:0)
      cpptools-srv.exe!edge::an_edge_translation_unit_impl::update_range(struct edge::allocator *,struct snapshot::snapshot_session_t,struct edge::file_position,struct edge::file_position,struct edge::update_range_options const &,struct edge::file_position,struct msvc::strong_typedef_t<struct msvc::offset_traits> *,struct msvc::strong_typedef_t<struct msvc::offset_traits> *,class an_array_list<struct edge::update_range_action *,class std::allocator<struct edge::update_range_action *> > const &,class edge::query_action_data &) (Unbekannte Quelle:0)
      cpptools-srv.exe!edge::translation_unit::update_range(struct edge::allocator *,struct snapshot::snapshot_session_t,struct edge::file_position,struct edge::file_position,struct edge::update_range_options const &,struct edge::file_position,struct msvc::strong_typedef_t<struct msvc::offset_traits> *,struct msvc::strong_typedef_t<struct msvc::offset_traits> *,class an_array_list<struct edge::update_range_action *,class std::allocator<struct edge::update_range_action *> > const &,class edge::query_action_data &) (Unbekannte Quelle:0)
      cpptools-srv.exe!edge_intellisense_server_impl::update_range(char const *,bool,bool,bool,struct snapshot::snapshot_session_t) (Unbekannte Quelle:0)
      cpptools-srv.exe!edge_intellisense_server_impl::handle_update_intellisense(struct microsoft::cpp::intellisense::UpdateIntelliSenseRequest const &) (Unbekannte Quelle:0)
      cpptools-srv.exe!std::_Func_impl_no_alloc<class <lambda_9989b9b68229e91bc44ae358201c3e96>,void>::_Do_call(void) (Unbekannte Quelle:0)
      cpptools-srv.exe!work_queue::worker_proc(void) (Unbekannte Quelle:0)
      cpptools-srv.exe!std::_Func_impl_no_alloc<<lambda_3dc5ec28e79ec858b90655540f6191da>,void>::_Do_call() (Unbekannte Quelle:0)
      cpptools-srv.exe!msvc::thread_pool::do_work(unsigned int) (Unbekannte Quelle:0)
      cpptools-srv.exe!std::thread::_Invoke<class std::tuple<class <lambda_a0cbe141f7d7ac57b80358412e72d184> >,0>(void *) (Unbekannte Quelle:0)
      cpptools-srv.exe!thread_start<unsigned int (__stdcall*)(void *),1>() (Unbekannte Quelle:0)
      kernel32.dll!@BaseThreadInitThunk@12() (Unbekannte Quelle:0)

- `cpptools-srv.exe!thread_start<unsigned int(__stdcall*)(void *),1>`

      KernelBase.dll!_RaiseException@16() (Unbekannte Quelle:0)
      cpptools-srv.exe!__CxxThrowException@8() (Unbekannte Quelle:0)
      cpptools-srv.exe!cfe_throw(void) (Unbekannte Quelle:0)
      cpptools-srv.exe!exit_compilation(enum an_error_severity) (Unbekannte Quelle:0)
      cpptools-srv.exe!a_compiler_thread::fetch_fragment(void) (Unbekannte Quelle:0)
      cpptools-srv.exe!before_tu_wrapup(void) (Unbekannte Quelle:0)
      cpptools-srv.exe!process_translation_unit(char const *,int,struct an_exported_template_file *) (Unbekannte Quelle:0)
      cpptools-srv.exe!cfe_main(int,char * * const) (Unbekannte Quelle:0)
      cpptools-srv.exe!cfe_main_exception_handler(int,char * * const) (Unbekannte Quelle:0)
      cpptools-srv.exe!edg_main(int,char * * const) (Unbekannte Quelle:0)
      cpptools-srv.exe!invoke_edge_compiler() (Unbekannte Quelle:0)
      cpptools-srv.exe!edge_compiler_main(int,char const * * const) (Unbekannte Quelle:0)
      cpptools-srv.exe!preparse(int,char const * *,class a_scout_store *,class edge::translation_unit *) (Unbekannte Quelle:0)
      cpptools-srv.exe!a_compiler_thread::compiler_thread_routine(class a_compiler_thread *) (Unbekannte Quelle:0)
      cpptools-srv.exe!std::thread::_Invoke<class std::tuple<void (*)(class a_compiler_thread *),class a_compiler_thread *>,0,1>(void *) (Unbekannte Quelle:0)
      cpptools-srv.exe!thread_start<unsigned int (__stdcall*)(void *),1>() (Unbekannte Quelle:0)
      kernel32.dll!@BaseThreadInitThunk@12() (Unbekannte Quelle:0)
      ntdll.dll!__RtlUserThreadStart() (Unbekannte Quelle:0)
      ntdll.dll!__RtlUserThreadStart@8() (Unbekannte Quelle:0)

In the debugging console I got quite a few `WER/CrashAPI:2659: ERROR Invalid args, too  big block` messages.

In Dev Tools it logs ` ERR Ein unbekannter Fehler ist aufgetreten. Weitere Details dazu finden Sie im Protokoll.` (unknown error occurred)

This is the working copy: `git clone https://github.com/arangodb/arangodb`
The error occurs when I randomly click on .cpp or .h files in the file explorer, e.g. under arangod > IResearch.
It appears to increase the amount of cpptools-srv.exe:

![image](https://user-images.githubusercontent.com/7819991/98234977-8050cd80-1f61-11eb-9b92-c3b8f374b336.png)

I also see some of them disappear, sometimes immediately, sometimes after some idle time. The amount doesn't seem to go down to 1 however.

_Originally posted by @Simran-B in https://github.com/microsoft/vscode-cpptools/issues/5591#issuecomment-722998472_

**Comment by sean-mcmanus** [comment]
@Simran-B I'm not sure if any of those are actual errors or not (most are "expected"). Do you see a "Failed to read response from server" message in the "C/C++" output window?

**Comment by sean-mcmanus** [comment]
@Simran-B I'm not seeing a bug with arangodb with files under arangod > IResearch.
