### ISSUE TITLE
Empty string in args throws IndexOutOfRangeException since v1.1.0

### ISSUE THREAD

**Issue by langemol** [microsoft/vscode-cpptools#6522]
Type: Debugger

Since version 1.1.0 having empty strings in the args array will give an IndexOutOfRangeException when trying to Start Debugging. This worked fine in version 1.0.1.
Issue: In launch.json  `"args":[ "a","","","b"]`
Workaround: add extra escaped quotes in empty argument ` "args":[ "a","\"\"","\"\"","b"],`

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.51.1
- C/C++ Extension Version: 1.1.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

Running the debugger will give a popup with title "Visual Studio Code" and error:
>Unable to start debugging. Internal error in MIEngine. Exception of type 'System.IndexOutOfRangeException' was thrown.
>
>   at MICore.LaunchOptions.QuoteArgument(String arg)
>   at MICore.LaunchOptions.ParseArguments(IEnumerable`1 arguments, Boolean quoteArguments)
>   at MICore.LaunchOptions.InitializeLaunchOptions(LaunchOptions launch)
>   at MICore.LocalLaunchOptions.CreateFromJson(JObject parsedOptions)
>   at MICore.LaunchOptions.GetInstance(HostConfigurationStore configStore, String exePath, String args, String dir, String options, Boolean noDebug, IDeviceAppLauncherEventCallback eventCallback, TargetEngine targetEngine, Logger logger)
>   at Microsoft.MIDebugEngine.AD7Engine.Microsoft.VisualStudio.Debugger.Interop.IDebugEngineLaunch2.LaunchSuspended(String pszServer, IDebugPort2 port, String exe, String args, String dir, String env, String options, enum_LAUNCH_FLAGS launchFlags, UInt32 hStdInput, UInt32 hStdOutput, UInt32 hStdError, IDebugEventCallback2 ad7Callback, IDebugProcess2& process)

**To Reproduce**
```
{
      "name": "classic 1",
      "type": "cppdbg",
      "request": "launch", 
      "program": "${fileDirname}/${fileBasenameNoExtension}",
      "args":[ "a","","","b"],
      "stopAtEntry": true,
      "cwd": "${workspaceFolder}",
      "externalConsole": true,
      "MIMode": "gdb",
    }
```

**Comment by WardenGnaw** [comment]
Thank you for reporting this bug. 

I can reproduce the issue and we will be investigating a fix.
