### ISSUE TITLE
Unhandled exception when editing c_cpp_configuration.json

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode-cpptools#676]
I'm working on writing an extension to automatically rewrite my c_cpp_configuration.json file with an updated include path specific to my setup. When my extension erases then updates the configuration file, your extension throws an unhandled exception error, since it is trying to read configurations when they are undefined. Attached is the stack trace, and if necessary I can build some sample extension code to help reproduce this. Looking at the js, it doesn't check to see if configurationsJson is null before attempting to read it.

```
TypeError: Cannot read property 'configurations' of undefined
    at ConfigurationProperties.getConfigIndexForPlatform (C:\Users\thadh\.vscode\extensions\ms-vscode.cpptools-0.11.0\out\src\LanguageServer\C_Cpp_ConfigurationProperties.js:104:35)
    at new ConfigurationProperties (C:\Users\thadh\.vscode\extensions\ms-vscode.cpptools-0.11.0\out\src\LanguageServer\C_Cpp_ConfigurationProperties.js:176:51)
    at Object.setupConfigurationProperties (C:\Users\thadh\.vscode\extensions\ms-vscode.cpptools-0.11.0\out\src\LanguageServer\C_Cpp_ConfigurationProperties.js:401:15)
    at Object.activate (C:\Users\thadh\.vscode\extensions\ms-vscode.cpptools-0.11.0\out\src\LanguageServer\C_Cpp.js:86:62)
    at processRuntimeDependencies (C:\Users\thadh\.vscode\extensions\ms-vscode.cpptools-0.11.0\out\src\main.js:39:15)
    at util.checkLockFile.then (C:\Users\thadh\.vscode\extensions\ms-vscode.cpptools-0.11.0\out\src\main.js:147:13)
```

**Comment by ThadHouse** [comment]
Nevermind. I realized this is only getting thrown when running in the debugger, and when running normally it only pops up the error message.
