### ISSUE TITLE
After upgrade to VSCode 1.54.1 the intergration with CMake fails and no Intellisense

### ISSUE THREAD

**Issue by michalfita** [microsoft/vscode-cpptools#7114]
**Type: LanguageService**
I upgraded VS Code to 1.54.1 the following error is displayed on attempt to configure the project:
```
[rollbar] Unhandled exception: Unhandled Promise rejection: Update code model for cpptools TypeError: Cannot read property 'getApi' of undefined {}
```
And Intellisense don't work any more.

**Describe the bug**
- OS and Version: Windows 10 19041
- VS Code Version: 1.54.1
- C/C++ Extension Version: 1.2.2
- Other extensions you installed (and if the issue persists after disabling them): CMake Tools 1.6.0
- Does this issue involve using SSH remote to run the extension on a remote machine?: **No**
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**
Restart VS Code with my project open.

```json
{
    "configurations": [
        {
            "name": "ZigbeeService",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/3rdparty/zab/impl/public"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.18362.0",
            "compilerPath": "${env:LOCALAPPDATA}/GCC_ARM/armv7l-linux-musleabihf-9.1.0/bin/armv7l-linux-musleabihf-g++.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-arm",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```

**Expected behavior**

As usual, reconfigure CMake project and Intellisense working as normal with my project.

<details>
  <summary><strong>Logs</strong></summary>

There are C/C++ in the Output pane combo.
```
[2021-03-05 16:49:26.995] [exthost] [info] extension host started
[2021-03-05 16:49:27.154] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2021-03-05 16:49:27.155] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/microsoft-authentication/dist/extension.js
[2021-03-05 16:49:27.182] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.cpptools {"startup":false,"extensionId":{"value":"ms-vscode.cpptools","_lower":"ms-vscode.cpptools"},"activationEvent":"onLanguage:cpp"}
[2021-03-05 16:49:27.182] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/sesa404214/.vscode/extensions/ms-vscode.cpptools-1.2.2/dist/main
[2021-03-05 16:49:27.321] [exthost] [warning] Could not identify extension for 'vscode' require call from c:\Users\sesa404214\.vscode\extensions\ms-vscode.cpptools-1.2.2\dist\main.js. These are the extension path mappings: 
	c:\Program Files\Microsoft VS Code\resources\app\extensions\configuration-editing -> vscode.configuration-editing
	c:\Program Files\Microsoft VS Code\resources\app\extensions\css-language-features -> vscode.css-language-features
	c:\Program Files\Microsoft VS Code\resources\app\extensions\debug-auto-launch -> vscode.debug-auto-launch
	c:\Program Files\Microsoft VS Code\resources\app\extensions\debug-server-ready -> vscode.debug-server-ready
	c:\Program Files\Microsoft VS Code\resources\app\extensions\emmet -> vscode.emmet
	c:\Program Files\Microsoft VS Code\resources\app\extensions\extension-editing -> vscode.extension-editing
	c:\Program Files\Microsoft VS Code\resources\app\extensions\git -> vscode.git
	c:\Program Files\Microsoft VS Code\resources\app\extensions\git-ui -> vscode.git-ui
	c:\Program Files\Microsoft VS Code\resources\app\extensions\github -> vscode.github
	c:\Program Files\Microsoft VS Code\resources\app\extensions\github-authentication -> vscode.github-authentication
	c:\Program Files\Microsoft VS Code\resources\app\extensions\grunt -> vscode.grunt
	c:\Program Files\Microsoft VS Code\resources\app\extensions\gulp -> vscode.gulp
	c:\Program Files\Microsoft VS Code\resources\app\extensions\html-language-features -> vscode.html-language-features
	c:\Program Files\Microsoft VS Code\resources\app\extensions\image-preview -> vscode.image-preview
	c:\Program Files\Microsoft VS Code\resources\app\extensions\jake -> vscode.jake
	c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features -> vscode.json-language-features
	c:\Program Files\Microsoft VS Code\resources\app\extensions\markdown-language-features -> vscode.markdown-language-features
	c:\Program Files\Microsoft VS Code\resources\app\extensions\merge-conflict -> vscode.merge-conflict
	c:\Program Files\Microsoft VS Code\resources\app\extensions\microsoft-authentication -> vscode.microsoft-authentication
	c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode-remote.remote-wsl-recommender -> ms-vscode-remote.remote-wsl-recommender
	c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug -> ms-vscode.js-debug
	c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug-companion -> ms-vscode.js-debug-companion
	c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug -> ms-vscode.node-debug
	c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2 -> ms-vscode.node-debug2
	c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.references-view -> ms-vscode.references-view
	c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.vscode-js-profile-table -> ms-vscode.vscode-js-profile-table
	c:\Program Files\Microsoft VS Code\resources\app\extensions\npm -> vscode.npm
	c:\Program Files\Microsoft VS Code\resources\app\extensions\php-language-features -> vscode.php-language-features
	c:\Program Files\Microsoft VS Code\resources\app\extensions\search-result -> vscode.search-result
	c:\Program Files\Microsoft VS Code\resources\app\extensions\simple-browser -> vscode.simple-browser
	c:\Program Files\Microsoft VS Code\resources\app\extensions\testing-editor-contributions -> vscode.testing-editor-contributions
	c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features -> vscode.typescript-language-features
	c:\Users\SESA404214\.vscode\extensions\asabil.meson-1.3.0 -> asabil.meson
	c:\Users\SESA404214\.vscode\extensions\asciidoctor.asciidoctor-vscode-2.8.7 -> asciidoctor.asciidoctor-vscode
	c:\Users\SESA404214\.vscode\extensions\belfz.search-crates-io-1.2.1 -> belfz.search-crates-io
	c:\Users\SESA404214\.vscode\extensions\bierner.markdown-checkbox-0.1.3 -> bierner.markdown-checkbox
	c:\Users\SESA404214\.vscode\extensions\bungcip.better-toml-0.3.2 -> bungcip.better-toml
	c:\Users\SESA404214\.vscode\extensions\gruntfuggly.shifter-0.0.6 -> Gruntfuggly.shifter
	c:\Users\SESA404214\.vscode\extensions\jebbs.plantuml-2.14.3 -> jebbs.plantuml
	c:\Users\SESA404214\.vscode\extensions\matklad.rust-analyzer-0.2.505 -> matklad.rust-analyzer
	c:\Users\SESA404214\.vscode\extensions\ms-python.python-2021.2.582707922 -> ms-python.python
	c:\Users\SESA404214\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157 -> ms-toolsai.jupyter
	c:\Users\SESA404214\.vscode\extensions\ms-vscode-remote.remote-containers-0.163.0 -> ms-vscode-remote.remote-containers
	c:\Users\SESA404214\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.0 -> ms-vscode-remote.remote-ssh
	c:\Users\SESA404214\.vscode\extensions\ms-vscode-remote.remote-ssh-edit-0.65.0 -> ms-vscode-remote.remote-ssh-edit
	c:\Users\SESA404214\.vscode\extensions\ms-vscode-remote.remote-wsl-0.54.0 -> ms-vscode-remote.remote-wsl
	c:\Users\SESA404214\.vscode\extensions\ms-vscode.cmake-tools-1.6.0 -> ms-vscode.cmake-tools
	c:\Users\SESA404214\.vscode\extensions\ms-vscode.cpptools-1.2.2 -> ms-vscode.cpptools
	c:\Users\SESA404214\.vscode\extensions\ms-vscode.powershell-2021.2.2 -> ms-vscode.powershell
	c:\Users\SESA404214\.vscode\extensions\rust-lang.rust-0.7.8 -> rust-lang.rust
	c:\Users\SESA404214\.vscode\extensions\serayuzgur.crates-0.5.6 -> serayuzgur.crates
	c:\Users\SESA404214\.vscode\extensions\twxs.cmake-0.0.17 -> twxs.cmake
	c:\Users\SESA404214\.vscode\extensions\wakatime.vscode-wakatime-5.0.1 -> WakaTime.vscode-wakatime

[2021-03-05 16:49:27.378] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-03-05 16:49:27.378] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/debug-auto-launch/dist/extension
[2021-03-05 16:49:27.388] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-03-05 16:49:27.388] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/git/dist/main
[2021-03-05 16:49:27.481] [exthost] [info] ExtensionService#_doActivateExtension Gruntfuggly.shifter {"startup":true,"extensionId":{"value":"Gruntfuggly.shifter","_lower":"gruntfuggly.shifter"},"activationEvent":"*"}
[2021-03-05 16:49:27.482] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/sesa404214/.vscode/extensions/gruntfuggly.shifter-0.0.6/extension
[2021-03-05 16:49:27.500] [exthost] [info] ExtensionService#_doActivateExtension WakaTime.vscode-wakatime {"startup":true,"extensionId":{"value":"WakaTime.vscode-wakatime","_lower":"wakatime.vscode-wakatime"},"activationEvent":"*"}
[2021-03-05 16:49:27.500] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/sesa404214/.vscode/extensions/wakatime.vscode-wakatime-5.0.1/dist/extension
[2021-03-05 16:49:27.658] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.cmake-tools {"startup":true,"extensionId":{"value":"ms-vscode.cmake-tools","_lower":"ms-vscode.cmake-tools"},"activationEvent":"workspaceContains:.vscode/cmake-kits.json"}
[2021-03-05 16:49:27.658] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/sesa404214/.vscode/extensions/ms-vscode.cmake-tools-1.6.0/dist/main
[2021-03-05 16:49:27.882] [exthost] [error] Activating extension ms-vscode.cpptools failed due to an error:
[2021-03-05 16:49:27.886] [exthost] [error] Error: a DebugAdapterDescriptorFactory can only be registered from the extension that defines the 'cppvsdbg' debugger.
	at m.registerDebugAdapterDescriptorFactory (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:25505)
	at Object.registerDebugAdapterDescriptorFactory (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:37807)
	at Object.initialize (c:\Users\sesa404214\.vscode\extensions\ms-vscode.cpptools-1.2.2\dist\main.js:18300:35)
	at c:\Users\sesa404214\.vscode\extensions\ms-vscode.cpptools-1.2.2\dist\main.js:26903:27
	at Generator.next (<anonymous>)
	at c:\Users\sesa404214\.vscode\extensions\ms-vscode.cpptools-1.2.2\dist\main.js:26841:71
	at new Promise (<anonymous>)
	at module.exports.__awaiter (c:\Users\sesa404214\.vscode\extensions\ms-vscode.cpptools-1.2.2\dist\main.js:26837:12)
	at activate (c:\Users\sesa404214\.vscode\extensions\ms-vscode.cpptools-1.2.2\dist\main.js:26870:12)
	at Function._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:14037)
	at Function._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:13714)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:11746
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-03-05 16:49:28.185] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-03-05 16:49:28.185] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/github/dist/extension.js
[2021-03-05 16:49:28.200] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-03-05 16:49:28.200] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/extension.js
[2021-03-05 16:49:28.554] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":false,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"onAuthenticationRequest:github"}
[2021-03-05 16:49:28.554] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/github-authentication/dist/extension.js
[2021-03-05 16:49:28.592] [exthost] [info] eager extensions activated
[2021-03-05 16:49:28.676] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
[2021-03-05 16:49:28.676] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/emmet/dist/node/emmetNodeMain
[2021-03-05 16:49:28.698] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2021-03-05 16:49:28.698] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2021-03-05 16:49:28.704] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl-recommender {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-wsl-recommender","_lower":"ms-vscode-remote.remote-wsl-recommender"},"activationEvent":"onStartupFinished"}
[2021-03-05 16:49:28.705] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/ms-vscode-remote.remote-wsl-recommender/dist/extension.js
[2021-03-05 16:49:28.729] [exthost] [info] ExtensionService#_doActivateExtension vscode.testing-editor-contributions {"startup":false,"extensionId":{"value":"vscode.testing-editor-contributions","_lower":"vscode.testing-editor-contributions"},"activationEvent":"onStartupFinished"}
[2021-03-05 16:49:28.729] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/testing-editor-contributions/dist/extension.js
[2021-03-05 16:49:28.732] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-containers","_lower":"ms-vscode-remote.remote-containers"},"activationEvent":"onStartupFinished"}
[2021-03-05 16:49:28.732] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/sesa404214/.vscode/extensions/ms-vscode-remote.remote-containers-0.163.0/dist/extension/extension
[2021-03-05 16:49:28.889] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-wsl","_lower":"ms-vscode-remote.remote-wsl"},"activationEvent":"onStartupFinished"}
[2021-03-05 16:49:28.889] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/sesa404214/.vscode/extensions/ms-vscode-remote.remote-wsl-0.54.0/dist/extension
[2021-03-05 16:49:28.976] [exthost] [error] Activating extension ms-vscode-remote.remote-wsl failed due to an error:
[2021-03-05 16:49:28.977] [exthost] [error] Error: [nullExtensionDescription]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api nullExtensionDescription
	at f (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:74959)
	at Object.p [as checkProposedApiEnabled] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:74906)
	at Object.registerRemoteAuthorityResolver (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:35427)
	at t.activate (c:\Users\sesa404214\.vscode\extensions\ms-vscode-remote.remote-wsl-0.54.0\dist\extension.js:1:43097)
	at Function._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:14037)
	at Function._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:13714)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:11746
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Promise.all (index 0)
[2021-03-05 16:49:29.007] [exthost] [error] Activating extension ms-vscode-remote.remote-containers failed due to an error:
[2021-03-05 16:49:29.008] [exthost] [error] Error: [nullExtensionDescription]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api nullExtensionDescription
	at f (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:74959)
	at Object.p [as checkProposedApiEnabled] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:74906)
	at Object.registerRemoteAuthorityResolver (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:35427)
	at lK (c:\Users\sesa404214\.vscode\extensions\ms-vscode-remote.remote-containers-0.163.0\dist\extension\extension.js:233:22735)
	at async Promise.all (index 0)
[2021-03-05 17:02:44.342] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"extensionId":{"value":"vscode.configuration-editing","_lower":"vscode.configuration-editing"},"activationEvent":"onLanguage:json"}
[2021-03-05 17:02:44.342] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/configuration-editing/dist/configurationEditingMain
[2021-03-05 17:02:44.350] [exthost] [info] ExtensionService#_doActivateExtension vscode.extension-editing {"startup":false,"extensionId":{"value":"vscode.extension-editing","_lower":"vscode.extension-editing"},"activationEvent":"onLanguage:json"}
[2021-03-05 17:02:44.350] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/extension-editing/dist/extensionEditingMain
[2021-03-05 17:02:44.357] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"extensionId":{"value":"vscode.json-language-features","_lower":"vscode.json-language-features"},"activationEvent":"onLanguage:json"}
[2021-03-05 17:02:44.357] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/json-language-features/client/dist/node/jsonClientMain
[2021-03-05 17:02:44.393] [exthost] [info] ExtensionService#_doActivateExtension vscode.npm {"startup":false,"extensionId":{"value":"vscode.npm","_lower":"vscode.npm"},"activationEvent":"onLanguage:json"}
[2021-03-05 17:02:44.393] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/npm/dist/npmMain


```
</details>

**Screenshots**

**Additional context**

**Comment by bobbrow** [comment]
@WardenGnaw do you know anything about this?
```
[2021-03-05 16:49:27.882] [exthost] [error] Activating extension ms-vscode.cpptools failed due to an error:
[2021-03-05 16:49:27.886] [exthost] [error] Error: a DebugAdapterDescriptorFactory can only be registered from the extension that defines the 'cppvsdbg' debugger.
	at m.registerDebugAdapterDescriptorFactory (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:25505)
	at Object.registerDebugAdapterDescriptorFactory (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:37807)
	at Object.initialize (c:\Users\sesa404214\.vscode\extensions\ms-vscode.cpptools-1.2.2\dist\main.js:18300:35)
	at c:\Users\sesa404214\.vscode\extensions\ms-vscode.cpptools-1.2.2\dist\main.js:26903:27
	at Generator.next (<anonymous>)
	at c:\Users\sesa404214\.vscode\extensions\ms-vscode.cpptools-1.2.2\dist\main.js:26841:71
	at new Promise (<anonymous>)
	at module.exports.__awaiter (c:\Users\sesa404214\.vscode\extensions\ms-vscode.cpptools-1.2.2\dist\main.js:26837:12)
	at activate (c:\Users\sesa404214\.vscode\extensions\ms-vscode.cpptools-1.2.2\dist\main.js:26870:12)
	at Function._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:14037)
	at Function._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:13714)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:11746
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by WardenGnaw** [comment]
Not sure why it would complain about ms-vscode.cppools registering `cppvsdbg`, because we do define it in the package.json in https://github.com/microsoft/vscode-cpptools/blob/d2cb68506b19212ccfabe29f56eac26ccbe3db71/Extension/package.json#L1904

Would be a question for VS Code on how to get additional logs on why it did not get the definition for `cppvsdbg`.

**Comment by sean-mcmanus** [comment]
Could someone have modified the package.json or could there have been some error when you re-write the package.json for the activationEvents?

**Comment by michalfita** [comment]
Any advice what to do about this problem? Any hint which versions would be unaffected so I can rollback?

**Comment by sean-mcmanus** [comment]
This should be fixed in the latest VS Code Insiders.
