### ISSUE TITLE
Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by truongan012** [microsoft/vscode-cpptools#7292]
Type: General

**Describe the bug**
- OS and Version: macOS Big Sur (Apple Silicon M1)
- VS Code Version: 1.55.0 (Apple version)
- C/C++ Extension Version: 1.2.2

Got some error when enable the extension:
[Error - 2:48:13 PM] Connection to server got closed. Server will not be restarted.
[Error - 2:48:13 PM] Request textDocument/documentHighlight failed.
Error: Connection got disposed.
	at Object.dispose (/Users/truongan/.vscode/extensions/ms-vscode.cpptools-1.2.2/dist/main.js:6517:25)
	at Object.dispose (/Users/truongan/.vscode/extensions/ms-vscode.cpptools-1.2.2/dist/main.js:8455:35)
	at LanguageClient.handleConnectionClosed (/Users/truongan/.vscode/extensions/ms-vscode.cpptools-1.2.2/dist/main.js:10537:42)
	at LanguageClient.handleConnectionClosed (/Users/truongan/.vscode/extensions/ms-vscode.cpptools-1.2.2/dist/main.js:15316:15)
	at closeHandler (/Users/truongan/.vscode/extensions/ms-vscode.cpptools-1.2.2/dist/main.js:10524:18)
	at CallbackList.invoke (/Users/truongan/.vscode/extensions/ms-vscode.cpptools-1.2.2/dist/main.js:15680:39)
	at Emitter.fire (/Users/truongan/.vscode/extensions/ms-vscode.cpptools-1.2.2/dist/main.js:15738:36)
	at closeHandler (/Users/truongan/.vscode/extensions/ms-vscode.cpptools-1.2.2/dist/main.js:5867:26)
	at CallbackList.invoke (/Users/truongan/.vscode/extensions/ms-vscode.cpptools-1.2.2/dist/main.js:15680:39)
	at Emitter.fire (/Users/truongan/.vscode/extensions/ms-vscode.cpptools-1.2.2/dist/main.js:15738:36)
	at StreamMessageReader.fireClose (/Users/truongan/.vscode/extensions/ms-vscode.cpptools-1.2.2/dist/main.js:17677:27)
	at Socket.<anonymous> (/Users/truongan/.vscode/extensions/ms-vscode.cpptools-1.2.2/dist/main.js:17717:46)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:674:12)

**Comment by sean-mcmanus** [comment]
The cpptools process crashed. Do you have any more repro info? Are you able to get a crash call stack somehow, such as by attaching to the process before it crashes (https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv) or enabling some core dump logging or mac crash logging?

**Comment by truongan012** [comment]
Hello,
Seems issue is gone with version v1.3.0 insiders. But I still can not debug. 
Tried to do as https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv, but still can not start. Here is snapshot:

<img width="261" alt="Screen Shot 2021-04-06 at 06 21 22" src="https://user-images.githubusercontent.com/13611865/113638556-52eb8580-96a1-11eb-990e-710b07ae2dab.png">

**Comment by Colengms** [comment]
Hi @truongan012 .  We're still working on getting debugging up and running on Apple Silicon.  That is tracked by: https://github.com/microsoft/vscode-cpptools/issues/7035 

Since you mentioned the original problem is resolved, I'll go ahead and close this issue.
