### ISSUE TITLE
Problem with self-signed certificate - can't update package

### ISSUE THREAD

**Issue by ruipacheco** [microsoft/vscode-cpptools#744]
Every time I start Visual Studio Code I get the following error in the console:

```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (OS X)' Failed at stage: downloadPackages
Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)

Finished
```

Can I download the manual package from somewhere?

**Comment by sean-mcmanus** [comment]
Can you set `"http.proxyStrictSSL": false`? Manual download/installation is possible, but complicated, so not recommended.

**Comment by ruipacheco** [comment]
Seems to have worked.
