### ISSUE TITLE
Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by weiiiii0622** [microsoft/vscode-cpptools#7663]
**Issue Type: Bug**
I was trying to open a c++ project today, but it showed "Connection to server got closed. Server will not be restarted." when I started my vscode. Can anyone help me? I suspect that the problem is related to cpptools.

VScode Version: 1.43.0   Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
OS: macOS Catalina 10.15.6
C/C++ IntelliSense version: 0.28.3

[](url)
<img width="1440" alt="截圖 2021-06-08 下午4 24 25" src="https://user-images.githubusercontent.com/69110733/121235713-bbd0c300-c8c7-11eb-9c12-8035a6f5ed76.png">

**Comment by sean-mcmanus** [comment]
Your C/C++ extension is "too old", 0.28.3. Are you able to update to 1.4.0? You'll need VS Code 1.53.0 or newer.

**Comment by weiiiii0622** [comment]
I've updated the c/c++ extension to 1.4.0, and another error showed up. "The language server crashed 5 times in the last 3 minutes."

**Comment by sean-mcmanus** [comment]
Are you using the x64 or arm64 version of macOS?

Does this repro if you open a new folder and create a new test.cpp file with just `int main(){return 0;}`, i.e. are you able to somehow get it to not crash?

Are you able to somehow get a crash call stack?

**Comment by Colengms** [comment]
Hi @weiiiii0622 .  I noticed that you also have the "C++ IntelliSense" extension enabled.  That 3rd party extension provides some of the same services of the C/C++ extension, and could lead to some conflicts.  Although I don't know if it has anything to do with the issue you're seeing, I'd recommend either using one of these extensions or the other.

**Comment by firstone** [comment]
Started having same issue in the last couple of days:

Version: 1.58.1
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.6.0

Extension version: 1.5.1

**Comment by RexYuan** [comment]
I have the same issue as well on

Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:09:06.581Z (2 days ago)
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0 (2019 intel i9)

with only cpptools enabled at v1.5.1 with its output

```
[Error - 7:28:50 AM] Connection to server got closed. Server will not be restarted.
[Error - 7:28:50 AM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/Users/rexyuan/.vscode/extensions/ms-vscode.cpptools-1.5.1/dist/main.js:55448:25)
	at Object.dispose (/Users/rexyuan/.vscode/extensions/ms-vscode.cpptools-1.5.1/dist/main.js:56368:35)
	at LanguageClient.handleConnectionClosed (/Users/rexyuan/.vscode/extensions/ms-vscode.cpptools-1.5.1/dist/main.js:58450:42)
	at LanguageClient.handleConnectionClosed (/Users/rexyuan/.vscode/extensions/ms-vscode.cpptools-1.5.1/dist/main.js:59640:15)
	at closeHandler (/Users/rexyuan/.vscode/extensions/ms-vscode.cpptools-1.5.1/dist/main.js:58437:18)
	at CallbackList.invoke (/Users/rexyuan/.vscode/extensions/ms-vscode.cpptools-1.5.1/dist/main.js:54166:39)
	at Emitter.fire (/Users/rexyuan/.vscode/extensions/ms-vscode.cpptools-1.5.1/dist/main.js:54224:36)
	at closeHandler (/Users/rexyuan/.vscode/extensions/ms-vscode.cpptools-1.5.1/dist/main.js:54798:26)
	at CallbackList.invoke (/Users/rexyuan/.vscode/extensions/ms-vscode.cpptools-1.5.1/dist/main.js:54166:39)
	at Emitter.fire (/Users/rexyuan/.vscode/extensions/ms-vscode.cpptools-1.5.1/dist/main.js:54224:36)
	at StreamMessageReader.fireClose (/Users/rexyuan/.vscode/extensions/ms-vscode.cpptools-1.5.1/dist/main.js:55614:27)
	at Socket.<anonymous> (/Users/rexyuan/.vscode/extensions/ms-vscode.cpptools-1.5.1/dist/main.js:55654:46)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
```

Not sure if it's caused by a related issue.

**Comment by Colengms** [comment]
Hi @RexYuan , @firstone  .  I'd suggest opening new issues for your repros.  This is a generic error, and could be due to a number of different causes.  The cause in your case may be different from the one encountered by the user who opened this issue.

The best case scenario for us would be if you could attach a debugger to the cpptools process and catch the stack when the crash occurs.  Though, if it happens immediately after launch, that may be difficult.  Though, perhaps if you open only `c_cpp_properties.json` to cause the extension to be activated, perhaps the issue may only repro when opening a source file.

To rule out there being something wrong with the installation directory (which we've seen happen for some users), I'd suggest deleting the contents of the cpptools directory and reinstalling the extension.  The installed extension directory is usually within a `.vscode` directory in the user directory.  i.e. On macOS: `~/.vscode/extensions/ms-vscode.cpptools-1.5.1` .  The directory needs to be deleted, as simply uninstalling and reinstalling via the VS Code UI will reuse existing contents.

I'd suggest opening an new issue, and including responses in that issue.  :)
