### ISSUE TITLE
Microsoft.VSCode.CPP.Extension.linux doesn't always terminate on quit/reload

### ISSUE THREAD

**Issue by mikedld** [microsoft/vscode-cpptools#774]
After some time, with VSCode restarts and reloads along the way, I could notice orphan Microsoft.VSCode.CPP.Extension.linux processes running on my machine. Marked with yellow on the screenshot here:

![screenshot from 2017-05-26 06-55-09](https://cloud.githubusercontent.com/assets/298203/26480051/4d06146a-41e0-11e7-8d94-bd28cbfe23a5.png)

Generally I could reproduce by starting the VSCode, waiting for Microsoft.VSCode.CPP.Extension.linux process to appear, and then reloading the window or quitting.

Currently running 1.12.2 with VSCode 0.11.2 but happened on earlier versions as well (started using the extension somewhere around version 0.10).

**Comment by sean-mcmanus** [comment]
I've seen this before, but I don't have a repro yet. It's expected that the process will linger for a few seconds as it finishes up some of it's processing, but not be permanently stuck.

**Comment by mikedld** [comment]
For me, using Reload Window command produces an orphan Microsoft.VSCode.CPP.Extension.linux process with a single child Microsoft.VSCode.CPP.IntelliSense.Msvc.linux, latter being in zombie state which means that it has already terminated but parent process most probably didn't retrieve its status yet. Attaching with GDB to the parent process I'm able to get the following backtraces (which is always the same):

```
Thread 7 (Thread 0x7fb1f1ffb700 (LWP 9597)):
#0  0x00007fb202eb782d in open64 () from /lib64/libpthread.so.0
#1  0x00000000005cd78d in async_pipe_nix::read_async_impl(std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)>, std::__1::function<void (int)>) ()
#2  0x00000000005cca63 in async_pipe::read_async(std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)>, std::__1::function<void (int)>) ()
#3  0x00000000005cbccc in protobuf_server::wait_for_requests() ()
#4  0x00000000005b7d01 in void* std::__1::__thread_proxy<std::__1::tuple<intellisense_client_impl::intellisense_client_impl(std::__1::shared_ptr<browse_engine>, std::__1::shared_ptr<ProcessData>, std::__1::shared_ptr<protobuf_client>, std::__1::shared_ptr<protobuf_server>, int)::{lambda()#1}> >(std::__1::tuple<intellisense_client_impl::intellisense_client_impl(std::__1::shared_ptr<browse_engine>, std::__1::shared_ptr<ProcessData>, std::__1::shared_ptr<protobuf_client>, std::__1::shared_ptr<protobuf_server>, int)::{lambda()#1}>) ()
#5  0x00007fb202eae3f4 in start_thread () from /lib64/libpthread.so.0
#6  0x00007fb202bf892f in clone () from /lib64/libc.so.6

Thread 6 (Thread 0x7fb1f3fff700 (LWP 9444)):
#0  0x00007fb202eaf69d in pthread_join () from /lib64/libpthread.so.0
#1  0x0000000000b0f88a in std::__1::thread::join() ()
#2  0x00000000005c2a64 in intellisense_client_impl::~intellisense_client_impl() ()
#3  0x0000000000b06e67 in std::__1::__shared_weak_count::__release_shared() ()
#4  0x00000000005b4e14 in std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<intellisense_client_impl> >, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<intellisense_client_impl> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<intellisense_client_impl> > > >::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<intellisense_client_impl> >, void*>*) ()
#5  0x00000000005aea00 in intellisense_client_factory::shutdown() ()
#6  0x0000000000562c8d in message_handler::shutdown() ()
#7  0x000000000055865a in vscode::handler_base<message_handler>::dispatch(vscode::vscode_client_message&&, vscode::vscode_server_message&) ()
#8  0x0000000000557741 in vscode::handler_base<message_handler>::handle_message(vscode::vscode_client_message&&) ()
#9  0x00000000005575ad in vscode::handler_base<message_handler>::main_loop()::{lambda()#1}::operator()() const ()
#10 0x000000000055752d in void* std::__1::__thread_proxy<std::__1::tuple<vscode::handler_base<message_handler>::main_loop()::{lambda()#1}> >(std::__1::tuple<vscode::handler_base<message_handler>::main_loop()::{lambda()#1}>) ()
#11 0x00007fb202eae3f4 in start_thread () from /lib64/libpthread.so.0
#12 0x00007fb202bf892f in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x7fb200cea700 (LWP 9443)):
#0  0x00007fb202eb415f in pthread_cond_wait () from /lib64/libpthread.so.0
#1  0x0000000000ab28f5 in neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long, int&) ()
#2  0x0000000000ab1c4c in microsoft::vc::alertable_event::wait_for_multiple(microsoft::vc::alertable_event**, unsigned long, bool, unsigned int) ()
#3  0x0000000000aaecf5 in microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}::operator()() const ()
#4  0x0000000000aaec4d in void* std::__1::__thread_proxy<std::__1::tuple<microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}> >(std::__1::tuple<microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}>) ()
#5  0x00007fb202eae3f4 in start_thread () from /lib64/libpthread.so.0
#6  0x00007fb202bf892f in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7fb2014eb700 (LWP 9442)):
#0  0x00007fb202eb415f in pthread_cond_wait () from /lib64/libpthread.so.0
#1  0x0000000000ab28f5 in neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long, int&) ()
#2  0x0000000000ab1c4c in microsoft::vc::alertable_event::wait_for_multiple(microsoft::vc::alertable_event**, unsigned long, bool, unsigned int) ()
#3  0x0000000000aaecf5 in microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}::operator()() const ()
#4  0x0000000000aaec4d in void* std::__1::__thread_proxy<std::__1::tuple<microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}> >(std::__1::tuple<microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}>) ()
#5  0x00007fb202eae3f4 in start_thread () from /lib64/libpthread.so.0
#6  0x00007fb202bf892f in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7fb201cec700 (LWP 9441)):
#0  0x00007fb202eb415f in pthread_cond_wait () from /lib64/libpthread.so.0
#1  0x0000000000ab28f5 in neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long, int&) ()
#2  0x0000000000ab1c4c in microsoft::vc::alertable_event::wait_for_multiple(microsoft::vc::alertable_event**, unsigned long, bool, unsigned int) ()
#3  0x0000000000aaecf5 in microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}::operator()() const ()
#4  0x0000000000aaec4d in void* std::__1::__thread_proxy<std::__1::tuple<microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}> >(std::__1::tuple<microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}>) ()
#5  0x00007fb202eae3f4 in start_thread () from /lib64/libpthread.so.0
#6  0x00007fb202bf892f in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7fb2024ed700 (LWP 9440)):
#0  0x00007fb202eb415f in pthread_cond_wait () from /lib64/libpthread.so.0
#1  0x0000000000ab28f5 in neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long, int&) ()
#2  0x0000000000ab1c4c in microsoft::vc::alertable_event::wait_for_multiple(microsoft::vc::alertable_event**, unsigned long, bool, unsigned int) ()
#3  0x0000000000aaecf5 in microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}::operator()() const ()
#4  0x0000000000aaec4d in void* std::__1::__thread_proxy<std::__1::tuple<microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}> >(std::__1::tuple<microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}>) ()
#5  0x00007fb202eae3f4 in start_thread () from /lib64/libpthread.so.0
#6  0x00007fb202bf892f in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7fb2035b97c0 (LWP 9439)):
#0  0x00007fb202eaf69d in pthread_join () from /lib64/libpthread.so.0
#1  0x0000000000b0f88a in std::__1::thread::join() ()
#2  0x00000000005541cf in vscode::handler_base<message_handler>::main_loop() ()
#3  0x0000000000552ccd in main ()
```

In some rare cases the child survives or I notice that an already-orphaned parent process creates new child process. Attaching with GDB to this child process then gives following backtraces:

```
(gdb) thread apply all bt

Thread 6 (Thread 0x7f88d2095700 (LWP 11645)):
#0  0x00007f88d4a631fd in read () from /lib64/libpthread.so.0
#1  0x000000000051186f in async_pipe_nix::read_sync_impl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) ()
#2  0x0000000000511a3e in async_pipe_nix::read_thread_proc() ()
#3  0x000000000051245d in void* std::__1::__thread_proxy<std::__1::tuple<async_pipe_nix::ensure_read_thread()::$_0> >(void*) ()
#4  0x00007f88d4a5a3f4 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f88d47a492f in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x7f88d2896700 (LWP 11644)):
#0  0x00007f88d4a6015f in pthread_cond_wait () from /lib64/libpthread.so.0
#1  0x00000000008b6205 in neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long, int&) ()
#2  0x00000000008b555c in microsoft::vc::alertable_event::wait_for_multiple(microsoft::vc::alertable_event**, unsigned long, bool, unsigned int) ()
#3  0x00000000008b2605 in microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}::operator()() const ()
#4  0x00000000008b255d in void* std::__1::__thread_proxy<std::__1::tuple<microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}> >(std::__1::tuple<microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}>) ()
#5  0x00007f88d4a5a3f4 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f88d47a492f in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7f88d3097700 (LWP 11643)):
#0  0x00007f88d4a6015f in pthread_cond_wait () from /lib64/libpthread.so.0
#1  0x00000000008b6205 in neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long, int&) ()
#2  0x00000000008b555c in microsoft::vc::alertable_event::wait_for_multiple(microsoft::vc::alertable_event**, unsigned long, bool, unsigned int) ()
#3  0x00000000008b2605 in microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}::operator()() const ()
#4  0x00000000008b255d in void* std::__1::__thread_proxy<std::__1::tuple<microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}> >(std::__1::tuple<microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}>) ()
#5  0x00007f88d4a5a3f4 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f88d47a492f in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7f88d3898700 (LWP 11642)):
#0  0x00007f88d4a6015f in pthread_cond_wait () from /lib64/libpthread.so.0
#1  0x00000000008b6205 in neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long, int&) ()
#2  0x00000000008b555c in microsoft::vc::alertable_event::wait_for_multiple(microsoft::vc::alertable_event**, unsigned long, bool, unsigned int) ()
#3  0x00000000008b2605 in microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}::operator()() const ()
#4  0x00000000008b255d in void* std::__1::__thread_proxy<std::__1::tuple<microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}> >(std::__1::tuple<microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}>) ()
#5  0x00007f88d4a5a3f4 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f88d47a492f in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7f88d4099700 (LWP 11641)):
#0  0x00007f88d4a6015f in pthread_cond_wait () from /lib64/libpthread.so.0
#1  0x00000000008b6205 in neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long, int&) ()
#2  0x00000000008b555c in microsoft::vc::alertable_event::wait_for_multiple(microsoft::vc::alertable_event**, unsigned long, bool, unsigned int) ()
#3  0x00000000008b2605 in microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}::operator()() const ()
#4  0x00000000008b255d in void* std::__1::__thread_proxy<std::__1::tuple<microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}> >(std::__1::tuple<microsoft::vc::thread_pool::thread_pool(int)::{lambda()#1}>) ()
#5  0x00007f88d4a5a3f4 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f88d47a492f in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7f88d5165740 (LWP 11639)):
#0  0x00007f88d4a6015f in pthread_cond_wait () from /lib64/libpthread.so.0
#1  0x00000000008b6205 in neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long, int&) ()
#2  0x00000000008b555c in microsoft::vc::alertable_event::wait_for_multiple(microsoft::vc::alertable_event**, unsigned long, bool, unsigned int) ()
#3  0x0000000000504bc9 in protobuf_server::wait_for_requests() ()
#4  0x00000000005046ec in main ()
```

**Comment by Helcaraxan** [comment]
I have been observing the same but on OSX. The timeframe, considering when this issue was reported seems to correspond.

Also the analysis that it happens when reloading / quitting VSC corresponds too.

For me the main drawback is that if I do not pay attention it literally eats up the battery-life of my laptop as the process is burning at 100% CPU continuously.

**Comment by sean-mcmanus** [comment]
A fix might be in our preview .vsix at https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.15.0-insiders (the final release is planned for next week). Instead of trying to send a shutdown event to the IntelliSense process, we just terminate the process.

@Helcaraxan We fixed excessive CPU processing issues with 0.14.6. Let us know if you're still having problems with CPU usage.

**Comment by Helcaraxan** [comment]
@sean-mcmanus I have indeed not seen it since the last update. Thank you for the fix!

**Comment by mikedld** [comment]
Confirmed, recent versions seem to work fine.

Is it okay to forcefully terminate the IS processes though? In particular, could it potentially lead to IS database corruption or something?

**Comment by sean-mcmanus** [comment]
@mikedld Yes, forcing the termination of the IntelliSense process is currently always okay -- it doesn't interact with the browse database at all. The main process needs to be aborted gracefully or the symbol database might end up getting reset.
