### ISSUE TITLE
Connection to server got closed. Server will not be restarted (Windows 7)

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#8002]
Bug type: General

**Describe the bug**
- OS and Version: Windows 7 32 bit
- VS Code Version: 1.59.0(User Setup)
- C/C++ Extension Version: v1.5.1
- Other extensions you installed (and if the issue persists after disabling them):
- After installing the extension and opening a c/cpp file i get "Connection to server got closed. Server will not be restarted" in the output

**To Reproduce**
Just install the extension and open a c/cpp file

**Expected behavior**
"Connection to server got closed. Server will not be restarted."

**Screenshots*
![image](https://user-images.githubusercontent.com/68454783/129926302-bc69d504-edd8-40e2-a375-9bdbbb5a7ffb.png)

**Comment by Colengms** [comment]
Hi @AKDev21 .  Could you confirm if this happens with an empty or very minimal source file?  If a file of some complexity is involved, there may be something about that code that is required to repro the issue.

Also, could you provide your `c_cpp_properties.json` (if it exists), and the content of the "C/C++" output channel leading up to the crash?

**Comment by sean-mcmanus** [comment]
In other words, we're not reproing it on our Windows 10 machines. @michelleangela @Colengms Is someone able to test on Windows 7 (i.e. maybe via the "To Verify - Internal" tag)?

**Comment by Yety-68** [comment]
Same issue on linux.

![screenshot](https://user-images.githubusercontent.com/55661257/129975210-83cc8d67-ff21-406d-8b32-be7df3cf62f4.png)

**Comment by sean-mcmanus** [comment]
@Yety-68 "Connection to server got closed." is a general symptom of a crash. Your linux repro is most likely a different root cause. We need more repro info to investigate further (or if you can get a crash call stack via setting up a core dumper or attaching to cpptools before it crashes: https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv).

**Comment by AKDev21** [comment]
> Hi @AKDev21 . Could you confirm if this happens with an empty or very minimal source file? If a file of some complexity is involved, there may be something about that code that is required to repro the issue.
> 
> Also, could you provide your `c_cpp_properties.json` (if it exists), and the content of the "C/C++" output channel leading up to the crash?

Yes it happens with a empty as well as a simple hello world file,
I don't have c_cpp_properties.json,

# log(window)
```
[2021-08-19 09:16:31.042] [renderer3] [error] net::ERR_CERT_AUTHORITY_INVALID: Error: net::ERR_CERT_AUTHORITY_INVALID
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:109:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
[2021-08-19 09:17:13.028] [renderer3] [error] Connection got disposed.: Error: Connection got disposed.
	at Object.dispose (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:55448:25)
	at Object.dispose (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:56368:35)
	at LanguageClient.handleConnectionClosed (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:58450:42)
	at LanguageClient.handleConnectionClosed (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:59640:15)
	at closeHandler (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:58437:18)
	at CallbackList.invoke (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:54166:39)
	at Emitter.fire (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:54224:36)
	at closeHandler (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:54798:26)
	at CallbackList.invoke (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:54166:39)
	at Emitter.fire (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:54224:36)
	at StreamMessageReader.fireClose (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:55614:27)
	at Socket.<anonymous> (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:55654:46)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
```
# log(extension host)
```
[2021-08-19 09:16:32.183] [exthost] [info] extension host started
[2021-08-19 09:16:32.259] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2021-08-19 09:16:32.259] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/microsoft-authentication/dist/extension.js
[2021-08-19 09:16:32.309] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-08-19 09:16:32.309] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/debug-auto-launch/dist/extension
[2021-08-19 09:16:32.360] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-08-19 09:16:32.361] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/git/dist/main
[2021-08-19 09:16:32.464] [exthost] [info] ExtensionService#_doActivateExtension ukoloff.win-ca {"startup":true,"extensionId":{"value":"ukoloff.win-ca","_lower":"ukoloff.win-ca"},"activationEvent":"*"}
[2021-08-19 09:16:32.464] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/User/.vscode/extensions/ukoloff.win-ca-3.3.0/index.js
[2021-08-19 09:16:34.532] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-08-19 09:16:34.532] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/extension.js
[2021-08-19 09:16:34.882] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":false,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"onAuthenticationRequest:github"}
[2021-08-19 09:16:34.882] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/github-authentication/dist/extension.js
[2021-08-19 09:16:35.525] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-08-19 09:16:35.525] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/github/dist/extension.js
[2021-08-19 09:16:35.592] [exthost] [info] eager extensions activated
[2021-08-19 09:16:35.600] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
[2021-08-19 09:16:35.600] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/emmet/dist/node/emmetNodeMain
[2021-08-19 09:16:35.669] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2021-08-19 09:16:35.670] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2021-08-19 09:16:35.719] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl-recommender {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-wsl-recommender","_lower":"ms-vscode-remote.remote-wsl-recommender"},"activationEvent":"onStartupFinished"}
[2021-08-19 09:16:35.719] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode-remote.remote-wsl-recommender/dist/extension.js
[2021-08-19 09:17:04.013] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.cpptools {"startup":false,"extensionId":{"value":"ms-vscode.cpptools","_lower":"ms-vscode.cpptools"},"activationEvent":"onLanguage:c"}
[2021-08-19 09:17:04.013] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/User/.vscode/extensions/ms-vscode.cpptools-1.5.1/dist/main
[2021-08-19 09:17:13.020] [exthost] [error] [ms-vscode.cpptools] provider FAILED
[2021-08-19 09:17:13.020] [exthost] [error] Error: Connection got disposed.
	at Object.dispose (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:55448:25)
	at Object.dispose (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:56368:35)
	at LanguageClient.handleConnectionClosed (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:58450:42)
	at LanguageClient.handleConnectionClosed (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:59640:15)
	at closeHandler (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:58437:18)
	at CallbackList.invoke (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:54166:39)
	at Emitter.fire (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:54224:36)
	at closeHandler (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:54798:26)
	at CallbackList.invoke (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:54166:39)
	at Emitter.fire (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:54224:36)
	at StreamMessageReader.fireClose (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:55614:27)
	at Socket.<anonymous> (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:55654:46)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
```
# log(main)
```
[2021-08-19 09:13:19.705] [main] [info] window: using vscode-file:// protocol and V8 cache options: bypassHeatCheck
[2021-08-19 09:13:22.157] [main] [info] update#setState idle
[2021-08-19 09:13:38.618] [main] [error] [uncaught exception in main]: Error: SharedProcess: crashed (detail: crashed, code: -2147483645)
[2021-08-19 09:13:38.618] [main] [error] Error: SharedProcess: crashed (detail: crashed, code: -2147483645)
    at C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:59:69324
    at k.fire (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:16:1712)
    at C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:14:48640
    at k.fire (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:16:1712)
    at Object.<anonymous> (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:58:9532)
    at Object.emit (events.js:327:22)
[2021-08-19 09:13:52.156] [main] [info] update#setState checking for updates
[2021-08-19 09:13:52.334] [main] [error] Error: net::ERR_CERT_AUTHORITY_INVALID
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:109:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
[2021-08-19 09:13:52.335] [main] [info] update#setState idle
[2021-08-19 09:16:24.795] [main] [info] window: using vscode-file:// protocol and V8 cache options: bypassHeatCheck
```
# cpptools
```
[Error - 9:17:13 AM] Sending notification cpptools/activeDocumentChange failed.
Error: Connection is disposed.
	at throwIfClosedOrDisposed (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:55236:19)
	at Object.sendNotification (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:55283:13)
	at Object.sendNotification (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:56338:56)
	at LanguageClient.sendNotification (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:58030:38)
	at c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:42288:33
	at c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:41953:21
	at new Promise (<anonymous>)
	at task (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:41952:28)
	at DefaultClient.<anonymous> (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:41895:38)
	at Generator.next (<anonymous>)
	at c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:40525:71
	at new Promise (<anonymous>)
	at __webpack_modules__.9325.__awaiter (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:40521:12)
	at nextTask (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:41893:40)
	at DefaultClient.<anonymous> (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:41911:24)
	at Generator.next (<anonymous>)
	at c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:40525:71
	at new Promise (<anonymous>)
	at __webpack_modules__.9325.__awaiter (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:40521:12)
	at DefaultClient.queueTask (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:41891:16)
	at DefaultClient.notifyWhenLanguageClientReady (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:41955:21)
	at DefaultClient.activeDocumentChanged (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:42287:14)
	at ClientCollection.replace (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:42897:35)
	at c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:41375:67
	at Array.forEach (<anonymous>)
	at ClientCollection.forEach (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:42873:25)
	at Object.closed (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:41375:36)
	at LanguageClient.handleConnectionClosed (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:58458:55)
	at LanguageClient.handleConnectionClosed (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:59640:15)
	at closeHandler (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:58437:18)
	at CallbackList.invoke (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:54166:39)
	at Emitter.fire (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:54224:36)
	at closeHandler (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:54798:26)
	at CallbackList.invoke (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:54166:39)
	at Emitter.fire (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:54224:36)
	at StreamMessageReader.fireClose (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:55614:27)
	at Socket.<anonymous> (c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.5.1\dist\main.js:55654:46)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 9:17:13 AM] Connection to server got closed. Server will not be restarted.
```
that's all the info i have

**Comment by Yety-68** [comment]
> @Yety-68 "Connection to server got closed." is a general symptom of a crash. Your linux repro is most likely a different root cause. We need more repro info to investigate further (or if you can get a crash call stack via setting up a core dumper or attaching to cpptools before it crashes: https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv).

When I detached workspace (workspace.code-workspace) all went fine.
Follow the content of problematic workspace config file:

{
	"folders": [
		{
			"path": "../C"
		},
		{
			"path": "../C/EsamiDaSvolgere"
		},
		{
			"path": "../C/EsamiSvolti"
		}
	],
    "settings": {}
}

Multi folder linking possible problem?

Many thanks for your time!

**Comment by Colengms** [comment]
Hi @AKDev21 .  Sorry, I neglected to mention that you need to add the following setting to enable Debug output to the "C/C++" output channel: `"C_Cpp.loggingLevel": "Debug"`

Could you provide the log output to that channel, leading up to the crash?

**Comment by Colengms** [comment]
Hi @Rouvem .  We are not repro'ing this issue (on Windows 7).  Since the main process is crashing, we are hoping to find some evidence in the logs leading up to the crash.  It would help us investigate the issue if anyone encountering it could provide the following:

* After setting `"C_Cpp.loggingLevel": "Debug"`, the output of the C/C++ channel leading up to the crash.
* `c_cpp_properties.json`, and any `C_Cpp.*` settings.

Also, if the extension successfully activates prior to opening the source file (perhaps by opening `c_cpp_properties.json`), it might be possible to connect the debugger to the `cpptools.exe` process prior to opening the source file, to intercept the stack of the crash.

Confirmation of whether this is occurring with a very simple example, would also help.  If a very simple example does not repro the issue, perhaps someone could provide an isolated repro example that we could use to investigate further.
