### ISSUE TITLE
IntelliSense process failed to spawn with 1.7.0-insiders2

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#8212]
@michelleangela Succesfully installed BUT :( The IntelliSense not works! 

OUPUT C/C++ LOG
  loggingLevel: Warning 
  uv_pipe_bind failed with ret = -98
  Failed to spawn IntelliSense process:
  uv_pipe_bind failed with ret = -98
  ...

REMOTE SERVER LOG
[2021-10-01 01:18:31.114] [remoteagent] [info] Installing extension: ms-vscode.cpptools
[2021-10-01 01:18:40.926] [remoteagent] [info] Extracted extension to /home/coder/.vscode-server/extensions/.bdb263c9-088d-4682-b405-20d928178a38: ms-vscode.cpptools
[2021-10-01 01:18:41.291] [remoteagent] [info] Renamed to /home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2
[2021-10-01 01:18:41.313] [remoteagent] [info] Extracting completed. ms-vscode.cpptools
[2021-10-01 01:18:41.495] [remoteagent] [info] Extension installed successfully: ms-vscode.cpptools
[2021-10-01 01:18:48.455] [remoteagent] [info] [::ffff:127.0.0.1][4e1e5d5d][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2021-10-01 01:18:49.793] [remoteagent] [info] [::ffff:127.0.0.1][bd8459bc][ExtensionHostConnection] <688> Extension Host Process exited with code: 0, signal: null.
[2021-10-01 01:19:19.304] [remoteagent] [info] [::ffff:127.0.0.1][3d49ef36][ManagementConnection] New connection established.
[2021-10-01 01:19:21.713] [remoteagent] [info] [::ffff:127.0.0.1][5ee8013f][ExtensionHostConnection] New connection established.
[2021-10-01 01:19:21.759] [remoteagent] [info] [::ffff:127.0.0.1][5ee8013f][ExtensionHostConnection] <6350> Launched Extension Host Process.
[2021-10-01 01:23:37.705] [remoteagent] [info] [::ffff:127.0.0.1][3d49ef36][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2021-10-01 01:23:38.972] [remoteagent] [info] [::ffff:127.0.0.1][5ee8013f][ExtensionHostConnection] <6350> Extension Host Process exited with code: 0, signal: null.
[2021-10-01 01:24:09.686] [remoteagent] [info] [::ffff:127.0.0.1][571de748][ManagementConnection] New connection established.
[2021-10-01 01:24:13.488] [remoteagent] [info] [::ffff:127.0.0.1][ba3fc349][ExtensionHostConnection] New connection established.
[2021-10-01 01:24:13.518] [remoteagent] [info] [::ffff:127.0.0.1][ba3fc349][ExtensionHostConnection] <6951> Launched Extension Host Process.

_Originally posted by @EdgarRSSA in https://github.com/microsoft/vscode-cpptools/issues/8201#issuecomment-931826189_

**Comment by sean-mcmanus** [comment]
@EdgarRSSA What do you see in the terminal if you launch ~/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/bin/cpptools-srv ? It's should exit with no error. 

Can you also run `file ~/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/bin/cpptools-srv`? You should see something like `ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0`

**Comment by EdgarRSSA** [comment]
Hi, @sean-mcmanus , Show info about your questions: 

"" What do you see in the terminal if you launch ~/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/bin/cpptools-srv ? "" ---

TERMINAL BASH
**04:30:11 PM coder@28e980131f4f   ~
$ ./.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/bin/cpptools-srv**
04:33:59 PM coder@28e980131f4f   ~
$ echo "$?"
**255**

**"" You should see something like ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0 "" --- Shows Nothing :( .**

### Aditional info:

TERMINAL BASH
**04:45:45 PM coder@28e980131f4f   ~
$ /lib/x86_64-linux-gnu/libc-2.28.so**
GNU C Library **(Debian GLIBC 2.28-10) stable release version 2.28**.
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 8.3.0.
libc ABIs: UNIQUE IFUNC ABSOLUTE
For bug reporting instructions, please see:
<http://www.debian.org/Bugs/>.

**04:46:23 PM coder@28e980131f4f   ~
$ /lib/x86_64-linux-gnu/ld-2.28.so***
Usage: ld.so [OPTION]... EXECUTABLE-FILE [ARGS-FOR-PROGRAM...]
You have invoked `ld.so', the helper program for shared library executables.
This program usually lives in the file `/lib/ld.so', and special directives
in executable files using ELF shared libraries tell the system's program
loader to load the helper program from this file.  This helper program loads
the shared libraries needed by the program executable, prepares the program
to run, and runs it.  You may invoke this helper program directly from the
command line to load and run an ELF executable file; this is like executing
that file itself, but always uses this helper program from the file you
specified, instead of the helper program file specified in the executable
file you run.  This is mostly of use for maintainers to test new versions
of this helper program; chances are you did not intend to run this program.

  --list                list all dependencies and how they are resolved
  --verify              verify that given object really is a dynamically linked
                        object we can handle
  --inhibit-cache       Do not use /etc/ld.so.cache
  --library-path PATH   use given PATH instead of content of the environment
                        variable LD_LIBRARY_PATH
  --inhibit-rpath LIST  ignore RUNPATH and RPATH information in object names
                        in LIST
  --audit LIST          use objects named in LIST as auditors

**Comment by sean-mcmanus** [comment]
The binary only requires glibc 2.17 (same as 1.6.0 does), so it isn't a glibc issue. It almost sounds like the binary may be corrupted. Have you tried uninstalling the extension and reinstalling it? We haven't been able to repro this issue yet and I believe it's the only report we've seen of this so far.

**Comment by EdgarRSSA** [comment]
> Have you tried uninstalling the extension and reinstalling it? 

Yes, I rebuild all my Image and Container, and reinstall all extensions naturally .. 

My container use gcc:10 https://hub.docker.com/_/gcc

```
GNU C Library (Debian GLIBC 2.28-10) stable release version 2.28.
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 8.3.0.
libc ABIs: UNIQUE IFUNC ABSOLUTE
For bug reporting instructions, please see:
<http://www.debian.org/Bugs/>.
```


VSCODE Version

```
1.60.2
7f6ab5485bbc008386c4386d08766667e155244e
x64
```


My PC use WSL Debian 10:

`Linux version 5.10.16.3-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Apr 2 22:23:49 UTC 2021`


I seen the same issues: 
```
[2021-10-01 23:34:46.901] [exthost] [error] [ms-vscode.cpptools] provider FAILED
[2021-10-01 23:34:46.902] [exthost] [error] Error: Connection got disposed.
	at Object.dispose (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:58625:25)
	at Object.dispose (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:59545:35)
	at LanguageClient.handleConnectionClosed (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:61627:42)
	at LanguageClient.handleConnectionClosed (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:62817:15)
	at closeHandler (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:61614:18)
	at CallbackList.invoke (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:57343:39)
	at Emitter.fire (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:57401:36)
	at closeHandler (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:57975:26)
	at CallbackList.invoke (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:57343:39)
	at Emitter.fire (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:57401:36)
	at StreamMessageReader.fireClose (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:58791:27)
	at Socket.<anonymous> (/home/coder/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:58831:46)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
```

> What do you see in the terminal if you launch ~/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/bin/cpptools-srv ?

```
coder@903a7ede1f95:~$ .vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/bin/cpptools-srv
coder@903a7ede1f95:~$ echo $?
255
```

**Comment by sean-mcmanus** [comment]
I'll check if anyone else on our team can repro this...

**Comment by EdgarRSSA** [comment]
@eswartz Yep, I have the same issues too ... maybe VSCode hates WSL  X'D
