### ISSUE TITLE
Request textDocument/hover failed., Request textDocument/signatureHelp failed. in vscode

### ISSUE THREAD

**Issue by htrc2** [microsoft/vscode-cpptools#8270]
Bug type: Output

[Error - 5:23:12 PM] Connection to server got closed. Server will not be restarted.
[Error - 5:23:12 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:58625:25)
	at Object.dispose (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:59545:35)
	at LanguageClient.handleConnectionClosed (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:61627:42)
	at LanguageClient.handleConnectionClosed (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:62817:15)
	at closeHandler (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:61614:18)
	at CallbackList.invoke (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:57343:39)
	at Emitter.fire (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:57401:36)
	at closeHandler (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:57975:26)
	at CallbackList.invoke (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:57343:39)
	at Emitter.fire (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:57401:36)
	at StreamMessageWriter.fireClose (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:58952:27)
	at Socket.<anonymous> (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:58971:46)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:673:12)
Request textDocument/signatureHelp failed.
Error: Connection got disposed.
	at Object.dispose (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:58625:25)
	at Object.dispose (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:59545:35)
	at LanguageClient.handleConnectionClosed (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:61627:42)
	at LanguageClient.handleConnectionClosed (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:62817:15)
	at closeHandler (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:61614:18)
	at CallbackList.invoke (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:57343:39)
	at Emitter.fire (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:57401:36)
	at closeHandler (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:57975:26)
	at CallbackList.invoke (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:57343:39)
	at Emitter.fire (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:57401:36)
	at StreamMessageWriter.fireClose (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:58952:27)
	at Socket.<anonymous> (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:58971:46)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 5:23:12 PM] Request textDocument/signatureHelp failed.
Error: Connection got disposed.
	at Object.dispose (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:58625:25)
	at Object.dispose (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:59545:35)
	at LanguageClient.handleConnectionClosed (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:61627:42)
	at LanguageClient.handleConnectionClosed (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:62817:15)
	at closeHandler (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:61614:18)
	at CallbackList.invoke (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:57343:39)
	at Emitter.fire (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:57401:36)
	at closeHandler (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:57975:26)
	at CallbackList.invoke (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:57343:39)
	at Emitter.fire (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:57401:36)
	at StreamMessageWriter.fireClose (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:58952:27)
	at Socket.<anonymous> (/home/htrc2/.vscode-server/extensions/ms-vscode.cpptools-1.7.0-insiders2/dist/main.js:58971:46)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:673:12)

**Describe the bug**
- OS and Version: Windows 10
- VS Code 
- C/C++ 

Such a problem accured when I was writting a c++ code. Did anyone have the same problem or does anyone know how to solve it?

**Comment by michelleangela** [comment]
@htrc2 
The log shows "Connection to server got closed. Server will not be restarted." This means that the C++ language server did not restart and therefore none of the C++ IntelliSense features (such as hover and signature help) will work.

Does the language server shut down for a particular case or when a particular C++ IntelliSense feature is used? Does this happen with a particular project or does it also happen for a simple sample code?

Could you enable the language server logging and then try to reproduce the issue where the server might shut down again, and then share those logs? To enable language server logging, see https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server. 

Also, can you verify if this only happens with version 1.7.0-insiders2 and not with version 1.6.0?

**Comment by michelleangela** [comment]
>Something is wrong in cpptools output and there is only this message occured [Error - 9:46:15 AM] Connection to server got closed. Server will not be restarted

The error "Connection to server got closed. Server will not be restarted" indicates that the cpptools language server process shut down or crashed and it will not be restarted. 

Version 1.7.0 was released yesterday. Could you try uninstalling version 1.6.1 and then installing 1.7.0 of the extension? Also, 1.7.0 requires the latest version of VS Code.
