### ISSUE TITLE
Cannot read property 'timeTelemetryCollector' of undefined

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#8354]
I get this error when opening our TypeScript cpptools folder with the 1.7.1: [2021-11-01 15:24:00.182] [exthost] [error] TypeError: Cannot read property 'timeTelemetryCollector' of undefined.

I think our extension is normally not supposed to be activating in this case. Or maybe it's just not supposed to be "real activating".

**Comment by Colengms** [comment]
HI @sean-mcmanus .  I don't repro this error (in the Developer Tools console, or the `Log (Extension Host)` output channel) when opening our TypeScript folder (either the root of the repo, or the Extensions folder).  Could you clarify the repro steps?  Note that the `Log (Extension Host)` can contain content from previous sessions and other concurrent VS Code instances.

**Comment by sean-mcmanus** [comment]
Oh, yeah, looks like I'm not reproing it now. I'll re-open it if I can figure out a repro.

**Comment by franciscorba** [comment]
I got the same error.
Full log here:

`[2021-11-11 12:25:10.446] [exthost] [info] Extension host with pid 4270 started
[2021-11-11 12:25:10.487] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
[2021-11-11 12:25:10.496] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: true, activationEvent: '*'
[2021-11-11 12:25:10.498] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*', root cause: vscode.github
[2021-11-11 12:25:10.510] [exthost] [info] ExtensionService#_doActivateExtension betwo.vscode-doxygen-runner, startup: true, activationEvent: '*'
[2021-11-11 12:25:10.515] [exthost] [info] ExtensionService#_doActivateExtension GitHub.vscode-pull-request-github, startup: true, activationEvent: '*'
[2021-11-11 12:25:10.533] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python, startup: true, activationEvent: '*', root cause: ms-iot.vscode-ros
[2021-11-11 12:25:10.587] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.cpptools, startup: true, activationEvent: '*', root cause: ms-iot.vscode-ros
[2021-11-11 12:25:10.618] [exthost] [info] ExtensionService#_doActivateExtension ms-vsliveshare.vsliveshare, startup: true, activationEvent: '*'
[2021-11-11 12:25:10.729] [exthost] [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker, startup: true, activationEvent: '*'
[2021-11-11 12:25:10.908] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
[2021-11-11 12:25:11.118] [exthost] [info] ExtensionService#_doActivateExtension ms-python.vscode-pylance, startup: false, activationEvent: 'api', root cause: ms-python.python
[2021-11-11 12:25:11.462] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
[2021-11-11 12:25:11.464] [exthost] [info] ExtensionService#_doActivateExtension ms-iot.vscode-ros, startup: true, activationEvent: '*'
[2021-11-11 12:25:11.616] [exthost] [info] Eager extensions activated
[2021-11-11 12:25:11.634] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
[2021-11-11 12:25:11.636] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens, startup: false, activationEvent: 'onStartupFinished'
[2021-11-11 12:25:11.669] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers, startup: false, activationEvent: 'onStartupFinished'
[2021-11-11 12:25:11.694] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl, startup: false, activationEvent: 'onStartupFinished'
[2021-11-11 12:25:11.699] [exthost] [info] ExtensionService#_doActivateExtension zenclabs.reactpreview, startup: false, activationEvent: 'onStartupFinished'
[2021-11-11 12:25:19.993] [exthost] [info] extension host terminating: renderer closed the socket
[2021-11-11 12:25:20.002] [exthost] [error] TypeError: Cannot read property 'timeTelemetryCollector' of undefined
	at Object.deactivate (/home/francisco/.vscode/extensions/ms-vscode.cpptools-1.7.1/dist/main.js:49395:13)
	at Object.deactivate (/home/francisco/.vscode/extensions/ms-vscode.cpptools-1.7.1/dist/main.js:54453:27)
	at w._deactivate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:11449)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:9997
	at Array.map (<anonymous>)
	at w.deactivateAll (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:9985)
	at b.terminate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:735)
	at o (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:32681)
	at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:30296)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[2021-11-11 12:25:20.017] [exthost] [error] ProxyResolver#resolveProxy Canceled: Canceled
	at Object.i [as canceled] (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:5:1157)
	at n._remoteCall (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13876)
	at Proxy.x.<computed>.F.charCodeAt.x.<computed> (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:10271)
	at u.resolveProxy (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:39347)
	at Object.resolveProxy (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:58426)
	at useProxySettings (/usr/share/code/resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:159:16)
	at /usr/share/code/resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:107:13
	at /usr/share/code/resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:335:13
	at processTicksAndRejections (internal/process/task_queues.js:93:5) 
[2021-11-11 12:25:20.026] [exthost] [error] ProxyResolver#resolveProxy Canceled: Canceled
	at Object.i [as canceled] (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:5:1157)
	at n._remoteCall (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13876)
	at Proxy.x.<computed>.F.charCodeAt.x.<computed> (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:10271)
	at u.resolveProxy (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:39347)
	at Object.resolveProxy (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:58426)
	at useProxySettings (/usr/share/code/resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:159:16)
	at /usr/share/code/resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:107:13
	at /usr/share/code/resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:335:13
	at processTicksAndRejections (internal/process/task_queues.js:93:5) 
[2021-11-11 12:25:20.033] [exthost] [error] ProxyResolver#resolveProxy Canceled: Canceled
	at Object.i [as canceled] (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:5:1157)
	at n._remoteCall (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13876)
	at Proxy.x.<computed>.F.charCodeAt.x.<computed> (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:10271)
	at u.resolveProxy (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:39347)
	at Object.resolveProxy (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:58426)
	at useProxySettings (/usr/share/code/resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:159:16)
	at /usr/share/code/resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:107:13
	at /usr/share/code/resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:335:13
	at processTicksAndRejections (internal/process/task_queues.js:93:5) 
[2021-11-11 12:25:21.007] [exthost] [info] Extension host with pid 4270 exiting with code 0
[2021-11-11 12:25:21.702] [exthost] [info] Extension host with pid 4539 started
[2021-11-11 12:25:21.702] [exthost] [info] Skipping acquiring lock for /home/francisco/.config/Code/User/workspaceStorage/4b23767e8580c529216443a7b0856cd6.
[2021-11-11 12:25:21.879] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
[2021-11-11 12:25:21.884] [exthost] [info] ExtensionService#_doActivateExtension ms-vsliveshare.vsliveshare, startup: false, activationEvent: 'onFileSystem:vsls'
[2021-11-11 12:25:22.007] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
[2021-11-11 12:25:22.018] [exthost] [info] ExtensionService#_doActivateExtension GitHub.vscode-pull-request-github, startup: true, activationEvent: '*'
[2021-11-11 12:25:22.106] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
[2021-11-11 12:25:22.472] [exthost] [info] Eager extensions activated
[2021-11-11 12:25:22.497] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens, startup: false, activationEvent: 'onStartupFinished'
[2021-11-11 12:25:22.526] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers, startup: false, activationEvent: 'onStartupFinished'
[2021-11-11 12:25:22.546] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl, startup: false, activationEvent: 'onStartupFinished'
[2021-11-11 12:25:24.512] [exthost] [info] ExtensionService#_doActivateExtension betwo.vscode-doxygen-runner, startup: false, activationEvent: '*'
[2021-11-11 12:25:24.516] [exthost] [info] ExtensionService#_doActivateExtension zenclabs.reactpreview, startup: false, activationEvent: 'onStartupFinished'
[2021-11-11 12:25:33.618] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:jsonc'
[2021-11-11 12:25:33.621] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
[2021-11-11 12:25:33.637] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
[2021-11-11 12:25:34.609] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.cmake-tools, startup: false, activationEvent: 'workspaceContains:CMakeLists.txt'
[2021-11-11 12:27:17.592] [exthost] [info] ExtensionService#_doActivateExtension cschlosser.doxdocgen, startup: false, activationEvent: 'onLanguage:cpp'
[2021-11-11 12:27:17.687] [exthost] [info] ExtensionService#_doActivateExtension mine.cpplint, startup: false, activationEvent: 'onLanguage:cpp'
[2021-11-11 12:27:17.698] [exthost] [info] ExtensionService#_doActivateExtension QiuMingGe.cpp-check-lint, startup: false, activationEvent: 'onLanguage:cpp'
[2021-11-11 12:27:17.705] [exthost] [warning] DiagnosticCollection with name 'cpplint' does already exist.`

**Comment by Colengms** [comment]
Thanks @franciscorba !  That's exactly what we needed to address the issue.  :)

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/edit/1.8.0-insiders
