### ISSUE TITLE
Extension not responding for a long time

### ISSUE THREAD

**Issue by alexander-trifonov** [microsoft/vscode-cpptools#8500]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.62.3
- C/C++ Extension Version: 1.7.1
- Other extensions you installed (and if the issue persists after disabling them):
  - Remote - Containers
  - Remote - SSH
  - Remote - SSH:Editing Configuration
- If using SSH remote, specify OS of remote machine: Centos 7.5.1804
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
Extension stops working for a long period of time (1-3 mins) after any amount of file changes, then shows function description, correct intellisense and file saving to remote server works afterward.

**Steps to reproduce**

1. Edit file in c++ project for a while
2. Try to save a file on remote server by Ctrl + S or try to get function defenition by hovering over function name
3. With a huge chance it will stuck "Loading..." tooltip
```
[2021-12-02 14:32:10.350] [exthost] [error] [ms-vscode.cpptools] provider FAILED
[2021-12-02 14:32:10.350] [exthost] [error] Error: DisposableStore is missing...
	at x._convertCompletionItem (/root/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:94:182136)
	at x.resolveCompletionItem (/root/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:94:181911)
```
**Expected behavior**
Immediately file saving and showing intellisense tooltips

**Code sample and logs**

- Code sample
Happen in any projects on any VM on Centos 7.5.1804

- Configurations in `c_cpp_properties.json`
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c89",
            "intelliSenseMode": "linux-gcc-x64",
            "cppStandard": "c++17",
            "compilerArgs": []
        }
    ],
    "version": 4
}
```
- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
All confidential information was replaced with [xxx], they all are just paths
```
-------- Diagnostics - 12/7/2021, 6:22:45 PM
Version: 1.7.1
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "c89",
    "intelliSenseMode": "linux-gcc-x64",
    "cppStandard": "c++17",
    "compilerArgs": [],
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ xxx.cc ]:
    xxx.H
    xxx.H
[ xxx.cc ]:
    xxx.cc
[ xxx.cc ]:
    xxx.H
[ xxx.cc ]:
    xxx.cc
    xxx.H
Translation Unit Configurations:
[ xxx.cc ]:
    Process ID: 558
    Memory Usage: 506 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/4.8.2
        /usr/include/c++/4.8.2/x86_64-redhat-linux
        /usr/include/c++/4.8.2/backward
        /usr/lib/gcc/x86_64-redhat-linux/4.8.2/include
        /usr/local/include
        /usr/include
        /xxx/xxx/xxx
        /xxx/xxx/xxx/xxx/xxx
        
    Standard Version: c++14
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=40802
[ /xxx.cc ]: not ready
    Process ID: 1034
    Memory Usage: 5 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/4.8.2
        /usr/include/c++/4.8.2/x86_64-redhat-linux
        /usr/include/c++/4.8.2/backward
        /usr/lib/gcc/x86_64-redhat-linux/4.8.2/include
        /usr/local/include
        /usr/include
        /xxx/xxx/xxx/xxx/xxx/xxx
    Standard Version: c++14
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=40802
[ /xx/xxx/xxx/total/xxx/xxx/xxx.cc ]:
    Process ID: 1056
    Memory Usage: 568 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/4.8.2
        /usr/include/c++/4.8.2/x86_64-redhat-linux
        /usr/include/c++/4.8.2/backward
        /usr/lib/gcc/x86_64-redhat-linux/4.8.2/include
        /usr/local/include
        /usr/include
        /xxx/xxx/xxx
    Standard Version: c++14
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=40802
[ /xxx/xxx/xxx.cc ]:
    Process ID: 2158
    Memory Usage: 616 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/4.8.2
        /usr/include/c++/4.8.2/x86_64-redhat-linux
        /usr/include/c++/4.8.2/backward
        /usr/lib/gcc/x86_64-redhat-linux/4.8.2/include
        /usr/local/include
        /usr/include
        /xxx/xxxx/xxx
    Standard Version: c++14
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=40802
Total Memory Usage: 1699 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 19700

------- Potential include path issues --------
Some headers exist in multiple locations. If IntelliSense is behaving incorrectly,
try adding one of the alternate paths to the "includePath" in your configuration in
c_cpp_properties.json to override the automatic path discovery for that header.

Using: /usr/include/xxx/xxx/xxxx.hpp
    Alternative: "/xxx/xxx/xx/xx"
Using: /usr/include/xxxxx.h
    Alternative: "/xxxxs"
Using: /xxxxx.h
    Alternative: "/xxxxx"
Using: /xxxx.h
    Alternative: "/xxxxx"
```

**Additional context**
<!--
Providing call stacks:
Can't, confidential...

**Comment by sean-mcmanus** [comment]
That is not expected behavior.

It repros with any project? What are the contents of the source files when you repro it for a simple project? Does it repro if you don't include any system headers?

Is the cpptools or cpptools-srv process using CPU? Are you able to either attach a debugger to get a call stack (https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv) or get a performance log (https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues).
