### ISSUE TITLE
Ubuntu crash

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#8871]
Hi, can this issue be reopened? I'm also facing the same issue. 

System info:
WSL2 ubuntu
extension version is 1.8.4.
Windows 11

I just followed this guide: https://code.visualstudio.com/docs/cpp/config-wsl and got the "Connection to server got closed. Server will not be restarted." when I opened a `.cpp` file.

I also cleared the extension data at `~/.vscode-server/extensions` and reinstalled the extension. Didn't solve the issue.

Here is the output shown when the extension crashes for the first time:
<details>
<summary>First crash Output log</summary>
<br>

```
[Error - 2:30:23 PM] Connection to server got closed. Server will not be restarted.
[Error - 2:30:23 PM] Request textDocument/hover failed.
Error: Connection got disposed.
    at Object.dispose (/home/hoppingturtles/.vscode-server/extensions/ms-vscode.cpptools-1.8.4/dist/main.js:47722:25)
    at Object.dispose (/home/hoppingturtles/.vscode-server/extensions/ms-vscode.cpptools-1.8.4/dist/main.js:48642:35)
    at LanguageClient.handleConnectionClosed (/home/hoppingturtles/.vscode-server/extensions/ms-vscode.cpptools-1.8.4/dist/main.js:50724:42)
    at LanguageClient.handleConnectionClosed (/home/hoppingturtles/.vscode-server/extensions/ms-vscode.cpptools-1.8.4/dist/main.js:51914:15)
    at closeHandler (/home/hoppingturtles/.vscode-server/extensions/ms-vscode.cpptools-1.8.4/dist/main.js:50711:18)
    at CallbackList.invoke (/home/hoppingturtles/.vscode-server/extensions/ms-vscode.cpptools-1.8.4/dist/main.js:46440:39)
    at Emitter.fire (/home/hoppingturtles/.vscode-server/extensions/ms-vscode.cpptools-1.8.4/dist/main.js:46498:36)
    at closeHandler (/home/hoppingturtles/.vscode-server/extensions/ms-vscode.cpptools-1.8.4/dist/main.js:47072:26)
    at CallbackList.invoke (/home/hoppingturtles/.vscode-server/extensions/ms-vscode.cpptools-1.8.4/dist/main.js:46440:39)
    at Emitter.fire (/home/hoppingturtles/.vscode-server/extensions/ms-vscode.cpptools-1.8.4/dist/main.js:46498:36)
    at StreamMessageWriter.fireClose (/home/hoppingturtles/.vscode-server/extensions/ms-vscode.cpptools-1.8.4/dist/main.js:48049:27)
    at Socket.<anonymous> (/home/hoppingturtles/.vscode-server/extensions/ms-vscode.cpptools-1.8.4/dist/main.js:48068:46)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
```
</details>

for some reason, I don't get the option to select `cpptools` or `cpptools-srv` when I follow this guide, so I can't attach the debugger:
https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv

_Originally posted by @harshil21 in https://github.com/microsoft/vscode-cpptools/issues/8451#issuecomment-1040046830_

**Comment by sean-mcmanus** [comment]
You probably don't see cpptools in the process select list because the process has already crashed.

Are you able to create a workspace folder with a `.vscode/c_cpp_properties.json` file but no C/C++ files open and then attach to cpptools, and then open a file to cause the crash to get a call stack?

Also, you may want to try uninstalling the extension and re-installing it -- there is a known bug with the VS Code marketplace which can cause the wrong OS vsix to be installed in some rare cases (e.g. an arm binary).

**Comment by sean-mcmanus** [comment]
@harshil21 You may also try 1.9.0 (insiders) -- it has multiple crash fixes.
