### ISSUE TITLE
Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: TypeError: ret.replace is not a function

### ISSUE THREAD

**Issue by jmpsmash** [microsoft/vscode-cpptools#9302]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.67.1
- C/C++ Extension Version: 1.9.8
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

When starting VSCode with C++ source, the following pops up:

Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: TypeError: ret.replace is not a function

**Steps to reproduce**

**Expected behavior**

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
That is strange. The error is reported at https://github.com/microsoft/vscode-cpptools/blob/release/Extension/src/LanguageServer/client.ts#L1057 and the ret.replace seems like it's from https://github.com/microsoft/vscode-cpptools/blob/release/Extension/src/common.ts#L332, but I don't know why that would occur.

**Comment by jmpsmash** [comment]
I have tried re-installing VSCode. removed the .vscode directory as well as the extension directory. Also tried 1.10.1 pre-release and that didn't help either.

**Comment by sean-mcmanus** [comment]
When you do Help->Toggle Developer Console do you see any errors in the Console logs? In particular, do you see any call stacks with our code on it or whatever code is calling the ret.replace?

**Comment by jmpsmash** [comment]
stack trace: Error: Unsupported client                                                                                                                                                                  
at DefaultClient.<anonymous> (c:\Users\johnnie\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\dist\main.js:35470:23)                                                                             
at Generator.next (<anonymous>)                                                                                                                                                                         
at c:\Users\johnnie\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\dist\main.js:33868:71                                                                                                         
at new Promise (<anonymous>)                                                                                                                                                                            
at __webpack_modules__.9325.__awaiter (c:\Users\johnnie\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\dist\main.js:33864:12)                                                                    
at DefaultClient.queueTask (c:\Users\johnnie\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\dist\main.js:35447:16)                                                                               
at DefaultClient.notifyWhenLanguageClientReady (c:\Users\johnnie\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\dist\main.js:35511:21)                                                           
at DefaultClient.selectionChanged (c:\Users\johnnie\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\dist\main.js:35950:14)                                                                        
at onDidChangeActiveTextEditor (c:\Users\johnnie\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\dist\main.js:39500:30)                                                                           
at c:\Users\johnnie\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\dist\main.js:40444:81                                                                                                         
at c:\Users\johnnie\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\dist\main.js:35509:21                                                                                                         
at new Promise (<anonymous>)                                                                                                                                                                            
at task (c:\Users\johnnie\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\dist\main.js:35508:28)                                                                                                  
at DefaultClient.<anonymous> (c:\Users\johnnie\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\dist\main.js:35451:38)                                                                             
at Generator.next (<anonymous>)                                                                                                                                                                         
at c:\Users\johnnie\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\dist\main.js:33868:71                                                                                                         
at new Promise (<anonymous>)                                                                                                                                                                            
at __webpack_modules__.9325.__awaiter (c:\Users\johnnie\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\dist\main.js:33864:12)                                                                    
at nextTask (c:\Users\johnnie\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\dist\main.js:35449:40)                                                                                              
at DefaultClient.<anonymous> (c:\Users\johnnie\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\dist\main.js:35467:24)                                                                             
at Generator.next (<anonymous>)                                                                                                                                                                         
at fulfilled (c:\Users\johnnie\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\dist\main.js:33865:58)

**Comment by jmpsmash** [comment]
There is also this:

notificationsAlerts.ts:42 Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: TypeError: ret.replace is not a function
onDidChangeNotification @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
invoke @ event.ts:575
deliver @ event.ts:779
fire @ event.ts:740
addNotification @ notifications.ts:206
notify @ notificationService.ts:137
(anonymous) @ mainThreadMessageService.ts:86
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:473
_invokeHandler @ rpcProtocol.ts:458
_receiveRequest @ rpcProtocol.ts:374
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:575
deliver @ event.ts:779
fire @ event.ts:740
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
invoke @ event.ts:575
deliver @ event.ts:779
fire @ event.ts:740
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
O @ ipc.net.ts:60
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199

**Comment by sean-mcmanus** [comment]
The "Unsupported client" error indicates they our extension think you're running on an unsupported OS. If you're running on Windows, I don't know why this would occur.

The onDidChangeNotification is not code from our extension's call stack so I don't know where it is from. Maybe if you enable breakpoints on Caught or Uncaught exceptions it would allow you to see who's code that is. So it's possible the "ret.replace" error is coming from some external code and it's just being caught by our exception handler.

If you want to investigate on your own further, there are instructions at https://github.com/microsoft/vscode-cpptools/blob/main/Documentation/Building%20the%20Extension.md on how to run/debug the extension.

This almost sounds like a VS Code issue or something odd with your environment. Do other VS Code extensions work okay?

**Comment by Colengms** [comment]
Hi @jmpsmash .  We tracked down an occurrence of this to use of a number where a string was expected, in `c_cpp_properties.json`.  For example:

```
"defines": [ "FOO": 1 ]
```

If this is the same issue you are repro, you should be able to work around it by quoting the value, like so:

```
"defines": [ "FOO": "1" ]
```

**Comment by sean-mcmanus** [comment]
I have a pending fix at https://github.com/microsoft/vscode-cpptools/pull/9403 . It should fix all cases of the ret.replace.

**Comment by jmpsmash** [comment]
Appreciate all the help!
