### ISSUE TITLE
Parser crashes on special raw string literals (GCC: `gcc/testsuite/c-c++-common/raw-string-{13,15}.c`)

### ISSUE THREAD

**Issue by a4lg** [microsoft/vscode-cpptools#9695]
### Environment

- OS and Version: Windows 10 21H1 (Host) / Linux - Ubuntu 22.04 LTS (Remote) (both x86_64)
- VS Code Version: 1.17.0
- C/C++ Extension Version: 1.11.4
- Other extensions you installed (and if the issue persists after disabling them):  
  Reproduced after disabling all except "Remote - SSH"
- If using SSH remote, specify OS of remote machine:  Linux (Ubuntu 22.04 LTS)
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Language server executable `cpptools` generates a crash when it parses either of two GCC test files:
- `gcc/testsuite/c-c++-common/raw-string-13.c`
- `gcc/testsuite/c-c++-common/raw-string-15.c`
They are pretty much the same except testing options for GCC.

### Bug Summary and Steps to Reproduce

Bug Summary:
When a workspace directory contains either of above two files, the language server `cpptools` crashes with Segmentation Fault (`SIGSEGV`).

Steps to reproduce:
1. Copy either of two files [`raw-string-13.c`](https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=gcc/testsuite/c-c%2B%2B-common/raw-string-13.c;h=fa11edaa7aab28acfc509525849be8a60d86c309;hb=a46bca36b7b3a8a7e15b04225fb2b4f9b1bed62c) and/or [`raw-string-15.c`](https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=gcc/testsuite/c-c%2B%2B-common/raw-string-15.c;h=1d101dc8393534494913e4e77fd90cd8b1c9f6d0;hb=a46bca36b7b3a8a7e15b04225fb2b4f9b1bed62c) under the workspace
2. Let the language server to process these files (opening either of the file would be the fastest but just waiting seems to be enough)
3. See error like "The language server crashed 5 times in the last 3 minutes. It will not be restarted."

### Expected behavior

Segmentation fault does not occur (parser error is acceptable because those files use trigraphs, which is no longer default available feature).

### Code sample and Logs

```shell
// Code sample
See above links

// c_cpp_properties.json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu17",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "linux-gcc-x64"
        }
    ],
    "version": 4
}

// The Language server logging
loggingLevel: Debug
$/setTraceNotification
cpptools/didChangeCppProperties
Attempting to get defaults from C compiler in "compilerPath" property: '/usr/bin/gcc'
Compiler query command line: /usr/bin/gcc -std=gnu17 -m64 -Wp,-v -E -dM -x c /dev/null
Warning: Database safety check failed. Recreating database.
[rc=0x80004005] (DB: false, Expected: true)
Code browsing service initialized
Attempting to get defaults from C++ compiler in "compilerPath" property: '/usr/bin/gcc'
Compiler query command line: /usr/bin/gcc -std=gnu++14 -m64 -Wp,-v -E -dM -x c++ /dev/null
  Folder: /usr/include/ will be indexed
  Folder: /usr/lib/gcc/x86_64-linux-gnu/11/include/ will be indexed
  Folder: /usr/local/include/ will be indexed
  Folder: /src/gcc2/ will be indexed
cpptools/didChangeCppProperties
Attempting to get defaults from C compiler in "compilerPath" property: '/usr/bin/gcc'
Compiler query command line: /usr/bin/gcc -std=gnu17 -m64 -Wp,-v -E -dM -x c /dev/null
Warning: Database safety check failed. Recreating database.
[rc=0x80004005] (DB: false, Expected: true)
Code browsing service initialized
Attempting to get defaults from C++ compiler in "compilerPath" property: '/usr/bin/gcc'
Compiler query command line: /usr/bin/gcc -std=gnu++14 -m64 -Wp,-v -E -dM -x c++ /dev/null
  Folder: /usr/include/ will be indexed
  Folder: /usr/lib/gcc/x86_64-linux-gnu/11/include/ will be indexed
  Folder: /usr/local/include/ will be indexed
  Folder: /src/gcc2/ will be indexed
cpptools/didChangeSettings
Discovering files...
cpptools/didChangeCppProperties
Attempting to get defaults from C compiler in "compilerPath" property: '/usr/bin/gcc'
Compiler query command line: /usr/bin/gcc -std=gnu17 -m64 -Wp,-v -E -dM -x c /dev/null
Warning: Database safety check failed. Recreating database.
[rc=0x80004005] (DB: false, Expected: true)
Code browsing service initialized
Attempting to get defaults from C++ compiler in "compilerPath" property: '/usr/bin/gcc'
Compiler query command line: /usr/bin/gcc -std=gnu++14 -m64 -Wp,-v -E -dM -x c++ /dev/null
  Folder: /usr/include/ will be indexed
  Folder: /usr/lib/gcc/x86_64-linux-gnu/11/include/ will be indexed
  Folder: /usr/local/include/ will be indexed
  Folder: /src/gcc2/ will be indexed
cpptools/didChangeSettings
Discovering files...
IntelliSense Engine = Default.
Enhanced Colorization is enabled.
Error squiggles are disabled.
Autocomplete is enabled.
textDocument/didOpen: /src/gcc2/raw-string-13.c
  Processing folder (recursive): /usr/include/
cpptools/activeDocumentChange: /src/gcc2/raw-string-13.c
  tag parsing file: /src/gcc2/raw-string-13.c
cpptools/resumeParsing
cpptools/fileCreated: /src/gcc2/core.2228263
cpptools/didChangeCppProperties
Attempting to get defaults from C compiler in "compilerPath" property: '/usr/bin/gcc'
Compiler query command line: /usr/bin/gcc -std=gnu17 -m64 -Wp,-v -E -dM -x c /dev/null
Warning: Database safety check failed. Recreating database.
[rc=0x80004005] (DB: false, Expected: true)
Code browsing service initialized
Attempting to get defaults from C++ compiler in "compilerPath" property: '/usr/bin/gcc'
Compiler query command line: /usr/bin/gcc -std=gnu++14 -m64 -Wp,-v -E -dM -x c++ /dev/null
  Folder: /usr/include/ will be indexed
  Folder: /usr/lib/gcc/x86_64-linux-gnu/11/include/ will be indexed
  Folder: /usr/local/include/ will be indexed
  Folder: /src/gcc2/ will be indexed
cpptools/didChangeSettings
Discovering files...
IntelliSense Engine = Default.
Enhanced Colorization is enabled.
Error squiggles are disabled.
Autocomplete is enabled.
textDocument/didOpen: /src/gcc2/raw-string-13.c
  Processing folder (recursive): /usr/include/
cpptools/activeDocumentChange: /src/gcc2/raw-string-13.c
  tag parsing file: /src/gcc2/raw-string-13.c
cpptools/resumeParsing
cpptools/didChangeCppProperties
Attempting to get defaults from C compiler in "compilerPath" property: '/usr/bin/gcc'
Compiler query command line: /usr/bin/gcc -std=gnu17 -m64 -Wp,-v -E -dM -x c /dev/null
Warning: Database safety check failed. Recreating database.
[rc=0x80004005] (DB: false, Expected: true)
Code browsing service initialized
Attempting to get defaults from C++ compiler in "compilerPath" property: '/usr/bin/gcc'
Compiler query command line: /usr/bin/gcc -std=gnu++14 -m64 -Wp,-v -E -dM -x c++ /dev/null
  Folder: /usr/include/ will be indexed
  Folder: /usr/lib/gcc/x86_64-linux-gnu/11/include/ will be indexed
  Folder: /usr/local/include/ will be indexed
  Folder: /src/gcc2/ will be indexed
cpptools/didChangeSettings
Discovering files...
IntelliSense Engine = Default.
Enhanced Colorization is enabled.
Error squiggles are disabled.
Autocomplete is enabled.
textDocument/didOpen: /src/gcc2/raw-string-13.c
  Processing folder (recursive): /usr/include/
cpptools/activeDocumentChange: /src/gcc2/raw-string-13.c
  tag parsing file: /src/gcc2/raw-string-13.c
cpptools/resumeParsing
cpptools/fileCreated: /src/gcc2/core.2228366
```

### Additional context

Similar issue (possibly a duplicate but with different program): #9538

I saved the core file (`core.2227321`) so can submit it if requested.

Backtrace with GDB:
```
GNU gdb (Ubuntu 12.0.90-0ubuntu1) 12.0.90
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
[New LWP 2227422]
[New LWP 2227326]
[New LWP 2227347]
[New LWP 2227323]
[New LWP 2227327]
[New LWP 2227324]
[New LWP 2227328]
[New LWP 2227329]
[New LWP 2227321]
[New LWP 2227331]
[New LWP 2227325]
[New LWP 2227348]
[New LWP 2227333]
[New LWP 2227342]
[New LWP 2227330]
[New LWP 2227341]
[New LWP 2227345]
[New LWP 2227332]
[New LWP 2227336]
[New LWP 2227338]
[New LWP 2227340]
[New LWP 2227346]
[New LWP 2227339]
[New LWP 2227344]
[New LWP 2227337]
[New LWP 2227343]
[New LWP 2227334]
[New LWP 2227335]

warning: Section `.reg-xstate/2227422' in core file too small.
Core was generated by `/home/li/.vscode-server/extensions/ms-vscode.cpptools-1.11.4-linux-x64/bin/cppt'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Section `.reg-xstate/2227422' in core file too small.
#0  0x0000000000acfd8c in ?? ()
[Current thread is 1 (LWP 2227422)]
(gdb) file ~/.vscode-server/extensions/ms-vscode.cpptools-1.11.4-linux-x64/bin/cpptools
Reading symbols from ~/.vscode-server/extensions/ms-vscode.cpptools-1.11.4-linux-x64/bin/cpptools...
warning: Section `.reg-xstate/2227422' in core file too small.
(gdb) bt
#0  0x0000000000acfd8c in conv_line_loc_to_source_pos(char const*, a_source_position*) ()
#1  0x0000000000aeb133 in conv_single_char(a_char_conversion_state*, int, unsigned long*, unsigned long, int, int) ()
#2  0x0000000000aebd9c in conv_string_literal(char const*, char const*, int, unsigned long, an_error_code*, char const**, int) ()
#3  0x0000000000aec5be in concat_string_literals(a_token_cache*, unsigned char, a_cached_token*) ()
#4  0x0000000000ad9157 in concat_adjacent_string_literals(int) ()
#5  0x0000000000ac6499 in get_token() ()
#6  0x000000000085f97a in a_scout_parser_token_stream<scout_parser_cpp>::nextToken() ()
#7  0x0000000000c83898 in antlr::TokenBuffer::get_nth_active_token_index(unsigned long) ()
#8  0x0000000000c83625 in antlr::TokenBuffer::LA(unsigned int) ()
#9  0x0000000000897e7f in scout_parser_cpp_generated::statement() ()
#10 0x0000000000889d9a in scout_parser_cpp_generated::statement_block(bool, a_source_point&) ()
#11 0x0000000000897c0a in scout_parser_cpp_generated::compound_statement(bool, a_source_point&) ()
#12 0x00000000008956bc in scout_parser_cpp_generated::function_body(an_identifier const&, a_source_point&) ()
#13 0x000000000088dd09 in scout_parser_cpp_generated::init_declarator_list_or_function_definition(a_source_point const&, a_source_point&, a_type_specification&, a_declaration_info const&) ()
#14 0x0000000000888a13 in scout_parser_cpp_generated::simple_declaration(a_type_specification&, antlr::TokenRefCount<antlr::Token>, a_declaration_info const&) ()
#15 0x0000000000884291 in scout_parser_cpp_generated::property_or_event_or_simple_declaration(a_type_specification&, antlr::TokenRefCount<antlr::Token>, a_declaration_info const&) ()
#16 0x00000000008831a8 in scout_parser_cpp_generated::general_declaration(a_type_specification&, antlr::TokenRefCount<antlr::Token>, a_declaration_info const&) ()
#17 0x0000000000882a18 in scout_parser_cpp_generated::general_declaration_with_error_recovery_inner(a_type_specification&, antlr::TokenRefCount<antlr::Token>, a_declaration_info const&) ()
#18 0x00000000008827b1 in scout_parser_cpp_generated::general_declaration_with_error_recovery(a_type_specification&, antlr::TokenRefCount<antlr::Token>, a_declaration_info const&) ()
#19 0x0000000000881e7b in scout_parser_cpp_generated::declaration(antlr::TokenRefCount<antlr::Token>, a_declaration_info const&, bool) ()
#20 0x0000000000881a29 in scout_parser_cpp_generated::declarations(bool) ()
#21 0x000000000085f50a in scout_parser_base<scout_parser_cpp, scout_parser_cpp_generated, scout_parser_cpp_generatedTokenTypes>::translation_unit() ()
#22 0x000000000085cc7c in run_tag_parser() ()
#23 0x0000000000bcc599 in process_translation_unit(char const*, int, an_exported_template_file*) ()
#24 0x00000000008aeaa7 in cfe_main(int, char**) ()
#25 0x0000000000bf0c16 in cfe_main_exception_handler(int, char**) ()
#26 0x00000000008aebb6 in edg_main(int, char**) ()
#27 0x000000000085ef95 in antlr_parse_routine() ()
#28 0x0000000000e6da6a in msvc::thread_helper_t::thread_entry(void*) ()
#29 0x00007f3e81fffb43 in ?? ()
#30 0x0000000000000000 in ?? ()
(gdb)
```

**Comment by Colengms** [comment]
Hi @a4lg .  This appears to be the same issue as is being tracked by https://github.com/microsoft/vscode-cpptools/issues/9538 .  I will close this as a duplicate.  The issue associated with the stack is due to a bug in C++ front end used by IntelliSense, which is licensed from [EDG](https://www.edg.com/c).  The issue has been reported to EDG.  We expect to receive a fix once it's available.

**Comment by a4lg** [comment]
Please reopen it.

Unlike #9538, it did not solved in the C++ extension v1.12.1.  So, this is very similar to #9538 but a different issue.

**Comment by sean-mcmanus** [comment]
Thanks for letting us know -- yeah, the crash calls stacks are similar, but it still crashes. I've filed internal VS issue 1593704 .

**Comment by sean-mcmanus** [comment]
The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.12.2
