### ISSUE TITLE
Illegal operation lstat on \\server\path

### ISSUE THREAD

**Issue by TheRolfFR** [microsoft/vscode-cpptools#9880]
### Environment

- OS and Version: Windows 10 Version 1809 (build 17763.3406) @2018
- VS Code Version:
Version : 1.71.0 (user setup)
Validation : 784b0177c56c607789f9638da7b6bf3230d47a8c
Date : 2022-09-01T07:36:10.600Z
Electron : 19.0.12
Chromium : 102.0.5005.167
Node.js : 16.14.2
V8 : 10.2.154.15-electron.0
OS : Windows_NT x64 10.0.17763
Sandboxed : No
- C/C++ Extension Version: 1.13.0
- Other extensions you installed (and if the issue persists after disabling them):  It's a CPP tool specific bug as the 
- If using SSH remote, specify OS of remote machine: N/A
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc):

My machine is on Window andI'm working in a workspace on a linux server, so I think he doesn't like this much when scanning folders.

### Bug Summary and Steps to Reproduce

Bug Summary:
Apparently, it fails to scan workspace directory

Steps to reproduce:
1. Open Workspace

### Expected behavior

Should scan folder and files to get intellisense and code navigation

### Code sample and Logs

```shell
- Code sample: none
- c_cpp_properties.json: untouched
- C/C++: Log Diagnostics: No error detected
- Host extension log:

"[2022-09-15 09:53:09.907] [exthost] [error] Error: EISDIR: illegal operation on a directory, lstat '\\\\server\\path'
	at Object.realpathSync (node:fs:2490:7)
	at Object.realpathSync (node:electron/js2c/asar_bundle:5:4831)
	at new DefaultClient (c:Usersfakeuser.vscodeextensionsms-vscode.cpptools-1.13.0-win32-x64distmain.js:42724:80)
	at Object.createClient (c:Usersfakeuser.vscodeextensionsms-vscode.cpptools-1.13.0-win32-x64distmain.js:42699:12)
	at c:Usersfakeuser.vscodeextensionsms-vscode.cpptools-1.13.0-win32-x64distmain.js:45182:44
	at Array.forEach (<anonymous>)
	at new ClientCollection (c:Usersfakeuser.vscodeextensionsms-vscode.cpptools-1.13.0-win32-x64distmain.js:45181:47)
	at Object.<anonymous> (c:Usersfakeuser.vscodeextensionsms-vscode.cpptools-1.13.0-win32-x64distmain.js:48434:19)
	at Generator.next (<anonymous>)
	at c:Usersfakeuser.vscodeextensionsms-vscode.cpptools-1.13.0-win32-x64distmain.js:48283:71
	at new Promise (<anonymous>)
	at __webpack_modules__.2973.__awaiter (c:Usersfakeuser.vscodeextensionsms-vscode.cpptools-1.13.0-win32-x64distmain.js:48279:12)
	at Object.activate (c:Usersfakeuser.vscodeextensionsms-vscode.cpptools-1.13.0-win32-x64distmain.js:48422:12)
	at c:Usersfakeuser.vscodeextensionsms-vscode.cpptools-1.13.0-win32-x64distmain.js:55793:34
	at Generator.next (<anonymous>)
	at fulfilled (c:Usersfakeuser.vscodeextensionsms-vscode.cpptools-1.13.0-win32-x64distmain.js:55675:58)"

```

### Screenshots

N/A

### Additional context

N/A

**Comment by sean-mcmanus** [comment]
We only support accessing Windows paths on Windows. To access the Linux paths, you should use the Remote extensions to connect to the machine and install/run the Linux version of our extension on the remote machine. Does that solve your issue?
